gravitee-io/gravitee-management-webui

- .gitignore
- bower.json
- bower_components/ngclipboard/.bower.json
- bower_components/ngclipboard/.editorconfig
- bower_components/ngclipboard/.gitignore
- bower_components/ngclipboard/.jscsrc
- bower_components/ngclipboard/.jshintrc
- bower_components/ngclipboard/.travis.yml
- bower_components/ngclipboard/Gruntfile.js
- bower_components/ngclipboard/LICENSE
- bower_components/ngclipboard/bower.json
- bower_components/ngclipboard/contributing.md
- bower_components/ngclipboard/dist/ngclipboard.js
- bower_components/ngclipboard/dist/ngclipboard.min.js
- bower_components/ngclipboard/package.json
- bower_components/ngclipboard/src/.jshintrc
- bower_components/ngclipboard/src/ngclipboard.js
- src/app/api/admin/apikeys/apikeys.controller.js
- src/app/api/admin/apikeys/apikeys.html
- src/app/index.module.js
This feature allow user to directly copy the api-key to clipboard.
It add an anchor like right after the api-key to allow copy
- use of ngclipboard library (without flash)
Closes #10
> feat(apikey): add a way to copy apikey to clipboard

- src/app/instances/details/environment/instanceEnvironment.html
> fix: resources must have an icon on instances page

- pom.xml
the version number replacement does not work for constants.js
fix gravitee-io/issues#282
> fix: wrong version number in the ui

- src/app/api/admin/endpoint/endpointConfiguration.controller.js
> feat(gateway): HTTP Compression is enabled by default at the client side

- src/components/sidenav/submenu.html
> fix(api): Refresh API when switching to an other screen

- src/management/api/policies/policies.controller.ts
- src/management/management.module.ts
- src/services/string.service.ts
because _.kebabCase() remove special characters, _.kebabCase(/foo/.*)
and _.kebabCase(/foo) are the same. And Dragular doesn't appreciate it.
fix gravitee-io/issues#560
> fix(policies): d&d policies on paths with regex

- src/components/chart/chart.directive.ts
> fix(portal): Use browser timezone to display charts

- src/management/api/general/dialog/apiExportDialog.controller.ts
This closes https://github.com/gravitee-io/issues/issues/557
> Generate file name from ui to avoid the cases where the content-disposition header is not available

- src/portal/portal.route.ts
> fix(portal): Remove call to retrieve metadata from API homepage

- src/management/api/apis.route.ts
Because it's the same controller for general and gateway pages, we have to create a fake `resolvedTenants` object
> fix: tenants needed on the general page

- README.adoc
> Update the portal installation's readme to advise the use of yarn in order to avoid inconsistent version between different builds

- src/components/widget/widget-chart-pie.component.ts
because hits status ratio is rounded, 100% of 2xx request is sometimes wrong
fix gravitee-io/issues#826
> feat(analytics): 100% in piechart is sometimes wrong

- src/authentication/authentication.config.ts
Fixes the `redirect_uri` sent to an oauth2 authentication endpoint when
the application is hosted with some path prefix. The path prefix should
now be included in the redirect_uri.
Fixes issue #854
> Fix an issue with oauth2 redirect_uri

- src/components/contextual/_contextual-doc.component.scss
This closes gravitee-io/issues#1120
> fix: hide scrollbar of contextual documentation

- src/management/api/api-plan.html
This closes gravitee-io/issues#1221
> fix: Plan preview is not correctly displayed on low resolution

- src/portal/i18n/pt-BR.json
We are studying the possibility of using gravitee as our api gateway and wanted to contribute with the translation to our native language.
It's going to be useful for our users in testing stages and also for future brazilian (or portuguese) users.
As I'm not able to open an issue, I didn't link it to any and commited to master.
> feat(i18n): add the i18n for brazilian portuguese

- src/index.ts
This closes gravitee-io/issues#1282
> fix: The portal configuration is not overridable within an object

- src/components/dashboard/dashboard-timeframe.html
- src/components/logs/logs-timeframe.html
- src/management/api/analytics/logs/configure-logging-editor.dialog.html
This closes gravitee-io/issues#1684
> fix: Calendar widget is displayed wrong week days on analytics filters

- src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts
> fix(endpoint): display inherited HC config by default

- src/components/documentation/page-editormarkdown-viewer.component.ts
This closes gravitee-io/issues#852
> fix: use anchor in markdown pages

- src/management/api/audit/history/apiHistory.controller.ts
Closes gravitee-io/issues#1774
> fix(audit): Sharding tags must be part of API definition

- src/management/management.route.ts
This closes gravitee-io/issues#1780
> fix: Dashboard analytics is not allowing to set multiple filters

- src/management/api/portal/documentation/metadata/dialog/update.api.metadata.dialog.controller.ts
> fix(metadata): global empty date metadata cannot be overriden

- src/components/documentation/page/page-swagger.component.ts
- Set oauth2RedirectUrl even if there is no configuration page saved
- Add pathname in oauth2RedirectUrl to fix the url when gravitee management ui is not hosted on root path
Fixes https://github.com/gravitee-io/issues/issues/2011
> fix oauth2RedirectUrl

- src/management/api/proxy/apiProxy.controller.ts
This closes gravitee-io/issues#2059
> fix: Service discovery configuration is lost when deleting an endpoint

- src/components/documentation/page/page-editormarkdown.component.ts
closes gravitee-io/issues#2225
> fix(media): Do not append a trailing slash after a media upload.

- .gitignore
- src/components/dashboard/dashboard-filter.controller.ts
- src/components/dashboard/dashboard.component.ts
Use a counter on initialization to wait for both queryFilter and timeframe before sending an event to widgets.
Fix gravitee-io/issues#2194
> fix():  use query parameter to build a status filter in api analytics

- src/management/api/portal/plans/plan/plan-wizard-general.html
> fix(plans): do not overlap input fields in the plan form

- src/portal/portal.route.ts
> fix(api.header): always display configured entrypoints

- build.json
- package.json
- pom.xml
- src/management/api/portal/general/dialog/apiExport.dialog.html
since a Plan is linked to one api instead of many
Fixes gravitee-io/issues#2540
> fix(jsonExport): fixes JsonExport for 1.15 and 1.20 and creates 1.25

- src/management/api/apis.controller.ts
- src/portal/api/api-list.controller.ts
> feat: When searching for APIs, empty input does not trigger the search

- src/management/api/proxy/backend/endpoint/httpConfiguration.html
> fix(requests): do not encode/decode query parameters by default

- src/management/components/notifications/notificationsettings/notificationsettings.html
> fix(notification-config): categories overlaps with Firefox

- src/portal/api/_api.scss
> fix(api-card): logo pops up to the side if too large

- src/components/widget/line/widget-chart-line.component.ts
Closes gravitee-io/issues#3205
> fix: Widget timeline does not display the API names correctly

- themes/light-theme.json
For now, those two icon color are too closed to the background color and are not visible. it's a proposition about having more visible icons
> Changing help and notify icon color to be visible

- src/management/instances/instances.html
> fix: Empty mode is not well displayed on Gateway Instances screen

- src/management/api/analytics/logs/log.html
- src/management/management.route.ts
- src/management/platform/logs/platform-log.html
> fix: API key is displayed as a client id on the context's log

- src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts
Closes gravitee-io/issues#3865
> fix(healthcheck): All widgets are refreshed when selecting a timeframe.

- docker/config/templates/default.conf.tmpl
Closes gravitee-io/issues#4094
> docker: Use non-root ports to run nginx

- src/management/management.interceptor.ts
* add X-Xsrf-Token only if not empty
* add X-ReCaptcha-Token only if not empty
Fixes gravitee-io/issues#4628
> fix(management): do not add empty tokens in HTTP headers

- src/management/configuration/theme/theme.controller.ts
- src/management/configuration/theme/theme.html
* use the `max size upload file` parameter in the import theme form
* export the enable status of the theme and ignore it when importing theme through the UI
Fixes gravitee-io/issues#4179
> fix(theme): import/Export changes

- src/components/documentation/edit-page.component.ts
- src/components/documentation/new-page.component.ts
- src/components/identityProviders/identity-providers.component.ts
- src/components/sidenav/sidenav.component.ts
- src/management/api/portal/subscriptions/dialog/subscription.create.dialog.controller.ts
- src/management/configuration/analytics/analytics.component.ts
- src/management/configuration/api-portal-header/api-portal-header.component.ts
- src/management/configuration/api-quality-rules/api-quality-rules.component.ts
- src/management/configuration/api_logging/api_logging.component.ts
- src/management/configuration/api_logging/api_logging.controller.ts
- src/management/configuration/api_logging/api_logging.html
- src/management/configuration/application/registration/client-registration-providers.component.ts
- src/management/configuration/categories/categories.controller.ts
- src/management/configuration/configuration.route.ts
- src/management/configuration/portal/portal.component.ts
- src/management/configuration/tags/tags.component.ts
- src/management/configuration/tags/tags.controller.ts
- src/management/configuration/tags/tags.html
- src/management/management.module.ts
- src/management/management.run.ts
- src/organization/configuration/console/console.component.ts
- src/organization/organization.route.ts
- src/services/consoleSettings.service.ts
- src/services/portalSettings.service.ts
* Rename Portal and Console xxxConfigService to xxxSettingsService...
* ... and use new resources to get and save settings  (/organization/orgID/settings & organization/orgID/environments/envID/settings)
* Call the "light" console config at startup
Closes gravitee-io/issues#4804
> fix(management): Better handling of settings

- src/components/identityProviders/identity-providers.component.ts
`hasActivatedIDP` method is used to force or not the `localLogin` option.
For environments, IDP must be activated AND enabled to be taken into account.
For organizations, IDP just need to be activated.
Fixes gravitee-io/issues#4797
> fix(identity-providers): fix hasActivatedIDP method

- src/management/api/portal/subscriptions/subscription.html
> fix(management): an apikey should not be reactivated on closed plans

- src/management/api/apis.html
> fix(console): display tooltip only if email exists

- package-lock.json
- package.json
- src/management/api/design/policy-studio/policy-studio.controller.ts
* use 1.0.18 version of ui-components
* use user permissions to configure policy-studio attributes (plans and readonly-plans)
Closes gravitee-io/issues#4770
> feat(policy-studio): manage plan permissions in policy studio

- src/components/documentation/edit-page.component.ts
use media hash instead of id to find the media to remove.
Fixes gravitee-io/issues#4702
> fix(management): fix attached media removing

- src/management/api/analytics/logs/_logs.scss
- src/management/api/analytics/logs/log.component.ts
- src/management/api/analytics/logs/log.html
- src/management/management.module.ts
Closes https://github.com/gravitee-io/issues/issues/4815
The goal of this PR is to add the Query Params in the request log screen. It also:
- converts the LogComponent controller from a function to a class to have a better type checking and improve readability
- add some title to the different sections display in the request log screen: Query Params, Headers, Payload 
- reformat the html of the component in a dedicated commit as the indentation of almost all the file was 🤯 
Note: I keep the separated commits to ease the review and we will squash them before merging.
**Screenshot**
> Request Log: Display query params in log details component

- src/management/management.run.ts
Fixes https://github.com/gravitee-io/issues/issues/5030
Avoid infinite redirection loop when a component redirects directly when it inits
It is the case for companents filtered by a timerange (logs, healthcheck logs, ...).
> fix: prevent infinite redirection loop

- src/management/api/creation/steps/api-creation-step1.html
- src/management/api/creation/steps/api-creation.controller.ts
- src/management/api/portal/general/apiPortal.controller.ts
- src/management/api/portal/userGroupAccess/groups/groups.html
- src/management/configuration/groups/group/addMemberDialog.controller.ts
- src/management/configuration/groups/group/group.component.ts
- src/management/configuration/groups/group/inviteMember.dialog.html
* filters groups list when creating an API
* disables the PO role when the group is already linked to an API
Closes gravitee-io/issues#5162
> feat(management): don't link an API to a PO group

- src/management/api/analytics/apis.analytics.route.html
> fix(management): hide Logs menu if no permission

- package-lock.json
- src/index.route.ts
* Instead of using only `window.location.href`, use also `window.location.pathname` to determine the correct redirect URL
* Also add `post_logout_redirect_uri` path parameter to be able to handle the logout process correctly
Fixes gravitee-io/issues#5621
> fix(management): OIDC logout uses the right URL

- src/organization/configuration/policies/policies.controller.ts
**Issue**
https://github.com/gravitee-io/issues/issues/4460
Add a dialog to tell users that platform policies will be applied automatically after being saved.
**Screenshot**
> feat: add a dialog when saving the platform policies

- build.json
- package-lock.json
- package.json
- src/assets/logo_asciidoc.svg
- src/components/documentation/documentation-management.component.ts
- src/components/documentation/documentation.module.ts
- src/components/documentation/edit-page.component.ts
- src/components/documentation/edit-page.html
- src/components/documentation/edit-tabs/edit-link-content.components.ts
- src/components/documentation/edit-tabs/edit-page-content.components.ts
- src/components/documentation/edit-tabs/edit-page-content.html
- src/components/documentation/edit-tabs/edit-page-translations.components.ts
- src/components/documentation/new-page.component.ts
- src/components/documentation/new-page.html
- src/components/documentation/page/_page.scss
- src/components/documentation/page/page-asciidoc.component.ts
- src/components/documentation/page/page-asciidoc.html
- src/components/documentation/page/page-swagger.component.ts
- src/libraries/gv-model.directive.ts
- src/management/api/portal/apis.portal.route.ts
- src/management/api/portal/general/dialog/apiExport.dialog.html
- src/management/configuration/configuration.route.ts
- src/management/management.module.ts
- src/services/documentation.service.ts
* use gv-documentation to render asciidoc
* use gv-code to edit swagger & asciidoc
* lint fixes
* fixes link edition (due to pages refactoring)
Related to gravitee-io/issues#4717
> feat(management): handle asciidoc pages in documentation

- src/components/documentation/edit-page.html
- src/components/documentation/edit-tabs/edit-page-acls.components.ts
**Issue**
https://github.com/gravitee-io/issues/issues/5789
Display API roles in `Access Control` tab of an API doc page instead of Environment roles.
**Screenshot**
API Documentation
Global documentation
> Display API roles in Access Control tab of an API doc page

- docs/management-apis-create-steps.md
- docs/management-configuration-apiquality.md
- docs/management-configuration-portal-pages.md
- src/management/api/creation/steps/api-creation.controller.ts
Permit user to import AsciiDocs file (.adoc) on step 4 of API creation flow.
Adapt documentations too.
(see https://github.com/gravitee-io/issues/issues/5937).
> #5937 Permit user to import AsciiDocs file (.adoc) on step 4 of API creation flow.

- src/management/api/creation/steps/api-creation.controller.ts
When the API Primary Owner mode is set to "GROUP", the API creation wizard requires a PO Group in the first step.
The list of available PO groups is filled with current user groups which are filters.
Currently, this filter assumes that a "user group" is an object. But it is a simple string list with group name only.
As a consequence, the PO groups list is always empty.
This PR fixes the filter.
> fix: current user groups is a string list

- .circleci/config.yml
- sonar-project.properties
**Issue**
https://github.com/gravitee-io/issues/issues/6053
- Create a `sonar-project.properties` file at the root of the repo
- Update CircleCI config to run Sonarscanner manually as Code coverage isn't supported by automatic analysis, see https://sonarcloud.io/documentation/advanced-setup/automatic-analysis/#prerequisites.
Result from a previous commit with duplicated lines:
> Add SonarCloud analysis

- pom.xml
**Issue**
NA
Ignore sonar-project file when checking license headers
> Ignore sonar-project file when checking license headers

- sonar-project.properties
- src/organization/configuration/console/console-settings.stories.ts
**Issue**
na
Keep sonar fo storybook stories. but exclude for coverage 
see pb here : 
https://sonarcloud.io/component_measures?id=gravitee-io_gravitee-management-webui&metric=new_coverage&pullRequest=1669&selected=gravitee-io_gravitee-management-webui%3Asrc%2Fshared%2Fcomponents%2Fconfirm-dialog%2Fconfirm-dialog.stories.ts&view=list
na
na
> chore: exclude `**/*.stories.ts` only for coverage

- src/ajs-upgraded-providers.ts
- src/app.module.ts
- src/management/management.module.ajs.ts
- src/organization/configuration/organization-settings.module.ts
- src/organization/configuration/users/org-settings-users.component.html
- src/organization/configuration/users/org-settings-users.component.spec.ts
- src/organization/configuration/users/org-settings-users.component.ts
- src/organization/organization.route.ajs.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6061
Start migration of organization users page with only empty component and useful provider to handle AngularJs states $ routeStates
na
The first PR of a long series to avoid a big PR for one screen
> 6061 migrate org users list

- sonar-project.properties
- src/entities/pagedResult.ts
- src/entities/user.ts
- src/entities/user/user.fixture.ts
- src/entities/user/user.ts
- src/organization/configuration/users/org-settings-users.component.html
- src/organization/configuration/users/org-settings-users.component.spec.ts
- src/organization/configuration/users/org-settings-users.component.ts
- src/services-ngx/users.service.spec.ts
- src/services-ngx/users.service.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6061
Add service to fetch users and use it in OrgSettingsUsersComponent to display data simply
> 6061 migrate org users list step 3

- docker/Dockerfile
Closes gravitee-io/issues#6139
> fix: Upgrade Nginx base image and upgrade libgcrypt

- src/management/api/_api.scss
**Issue**
NA
Fix banner size by using `px` instead of `rem`
Before:
After:
> Fix banner size by using px instead of rem

- src/management/api/portal/subscriptions/components/apiKeyValidatedInput.component.ts
- src/management/api/portal/subscriptions/dialog/subscription.accept.dialog.controller.ts
- src/management/api/portal/subscriptions/dialog/subscription.accept.dialog.html
- src/management/api/portal/subscriptions/dialog/subscription.create.dialog.html
- src/management/api/portal/subscriptions/dialog/subscription.renew.dialog.controller.ts
- src/management/api/portal/subscriptions/dialog/subscription.renew.dialog.html
- src/management/api/portal/subscriptions/subscription.component.ts
- src/management/api/portal/subscriptions/subscription.html
- src/management/application/details/subscriptions/application-subscription.component.ts
- src/management/application/details/subscriptions/application-subscription.html
- src/management/application/details/subscriptions/application-subscriptions.controller.ts
- src/services/api.service.ts
- src/services/application.service.ts
https://github.com/gravitee-io/issues/issues/6006
Now, we permit to use the same API key for multiple subscriptions of the same application.
To know if an apiKey can be created, we have to provide 3 query parameters to the _canCreate endpoint : apiKey, apiId, and applicationId.
> feat: handle duplicate api keys

- .storybook/main.ts
- src/organization/configuration/console/org-settings-general.component.html
- src/organization/configuration/console/org-settings-general.component.scss
- src/organization/configuration/console/org-settings-general.component.spec.ts
- src/organization/configuration/console/org-settings-general.component.ts
- src/organization/configuration/organization-settings.module.ts
- src/shared/components/form-slide-toogle/__snapshots__/gio-form-slide-toggle.component.spec.ts.snap
- src/shared/components/form-slide-toogle/gio-form-label.directive.ts
- src/shared/components/form-slide-toogle/gio-form-slide-toggle.component.html
- src/shared/components/form-slide-toogle/gio-form-slide-toggle.component.scss
- src/shared/components/form-slide-toogle/gio-form-slide-toggle.component.spec.ts
- src/shared/components/form-slide-toogle/gio-form-slide-toggle.component.ts
- src/shared/components/form-slide-toogle/gio-form-slide-toggle.module.ts
- src/shared/components/form-slide-toogle/gio-form-slide-toggle.stories.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6182
Create new form-field for toggle similar to mat-form-field
Use it in settings general 
Improve settings general lock icon an tooltips
before: 
after:
before: 
after:
> Improve UX of Console Setting screen 

- .circleci/config.yml
**Issue**
NA
The `weekly-purge-azure-registry` workflow was calling `purge-master-azure-registry` without setting any environment variables, causing the job to throw, for example: https://app.circleci.com/pipelines/github/gravitee-io/gravitee-management-webui/2362/workflows/b04942e5-b025-44a1-8f3c-fdb24ac81d88/jobs/4452
I just added the needed env vars and updated the job name to match the corn expression
> Add missing env var in `weekly-purge-azure-registry` workflow

- src/ajs-upgraded-providers.ts
- src/app.module.ts
- src/entities/user/userDetails.ts
- src/organization/configuration/organization-settings.module.ts
- src/organization/configuration/users/org-settings-users.component.html
- src/organization/configuration/users/org-settings-users.component.spec.ts
- src/services/user.service.ts
- src/shared/components/gio-permission/gio-permission.directive.spec.ts
- src/shared/components/gio-permission/gio-permission.directive.ts
- src/shared/components/gio-permission/gio-permission.module.ts
- src/shared/components/gio-permission/gio-permission.service.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6204
- Introduce a GioPermission directive to hide/show an element according to a certain set of permissions.
It currently relies on the currentUser from UserService. The end goal is to reverse the dependency and make the RoleService use the GioPermission one.
- Use Permission directive in Users Org Settings screen
> Create an Angular permission directive

- src/organization/configuration/identity-providers/org-settings-identity-providers.component.html
- src/organization/configuration/identity-providers/org-settings-identity-providers.component.scss
- src/organization/configuration/identity-providers/org-settings-identity-providers.component.spec.ts
- src/organization/configuration/identity-providers/org-settings-identity-providers.component.ts
- src/services-ngx/identity-provider.service.spec.ts
- src/services-ngx/identity-provider.service.ts
- src/services-ngx/organization.service.spec.ts
- src/services-ngx/organization.service.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6058
To review and merge after https://github.com/gravitee-io/gravitee-management-webui/pull/1711
Add interaction to: 
- Activate/Deactivate an identity provider
- Delete an identity provider
- Go to the detail screen of an identity provider
https://user-images.githubusercontent.com/4112568/135093448-dbfbc41f-8d34-4806-9159-35775b0c88bf.mp4
> Migration Identity Providers settings screen

- src/shared/components/form-color-input/gio-form-color-input.component.html
- src/shared/components/form-color-input/gio-form-color-input.component.scss
- src/shared/components/form-color-input/gio-form-color-input.component.ts
- src/shared/components/form-color-input/gio-form-color-input.harness.ts
- src/shared/components/form-color-input/gio-form-color-input.module.spec.ts
- src/shared/components/form-color-input/gio-form-color-input.module.ts
- src/shared/components/form-color-input/gio-form-color-input.stories.ts
**Issue**
https://github.com/gravitee-io/issues/issues/6060
add new simple html5 input color 
> 6060 identity provider part 3

- .circleci/config.yml
Here below CCI pipeline link : it launches the new workflow "Docker_Snyk_Test" in non dry run mode, two jobs were added for this workflow :
d_apim_package_bundle_secrets
d_apim_snyktest_docker_rest
in order to fetch Azure secrets from secrethub and then build and publish docker images in azure private registry from a given release that we have to put the version in the parameter,
CCI link : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-management-webui/2180/workflows/30aaa565-f43b-490f-8daa-17e34d600b2d
Link to the azure private registry : https://portal.azure.com/#@graviteesource.com/resource/subscriptions/02ae5fba-84b0-443a-9df6-9be92297c139/resourceGroups/container-hprod/providers/Microsoft.ContainerRegistry/registries/graviteeio/repository
Link to the slab …
> adding new workflow for publishing docker images in Private azure

- src/components/widget/widget.component.ts
https://github.com/gravitee-io/issues/issues/5771
fix: fix top failed widget analytics query
Add widget specific query at the end of the chart request query built from dashboard filters.
For example, for top failed widget, it will add the "status:[500 TO 599]" at the end of the generated query.
> fix: fix top failed widget analytics query
