gravitee-io/gravitee-management-webui

src/app/api/admin/policies/apiPolicies.html, src/app/api/admin/policies/policies.controller.js, src/app/policy/policy.service.js
=> refacto(policies): rewrite policies controller

src/app/api/admin/policies/apiPolicies.html, src/app/api/admin/policies/policies.controller.js, src/app/policy/policy.scss
=> feat(api policies): unable to know which policy is selected

src/app/api/admin/policies/policies.controller.js
=> fix(policies): 404 when retreiving schema is a normal thing

src/app/api/admin/apikeys/apikeys.html, src/app/application/details/apikeys/applicationAPIKeys.html
This fix replace a span by a div with a fixed width (24px)
Closes #43
=> fix(apiKey): define a fixed width on clipboard icon container

src/app/api/admin/apiAdmin.controller.js, src/app/api/admin/apiAdmin.html, src/app/api/admin/general/apiGeneral.controller.js, src/app/api/api.scss, src/app/api/api.service.js
Unable to manually deploy API via Events.
=> feat(event) : Manually deploy API to the Gateway

src/app/api/admin/apiAdmin.controller.js, src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/monitoring.controller.js, src/app/api/admin/policies/policies.controller.js, src/app/api/admin/properties/properties.controller.js, src/app/api/api.scss, src/app/main/main.scss, src/index.html
It seems that an event is not sent when updating a policy.
It's also the case when managing Properties, Monitoring, ...
#52
=> No message 'API out of sync...' when updating a policy

src/app/api/apisList.html, src/app/application/applications.html, src/app/components/role/role.directive.js, src/app/index.module.js, src/app/user/user.service.js
API creation must be done only by users with a dedicated role (ROLE_API_PUBLISHER)
Application creation must be done only by users with a dedicated role (ROLE_API_CONSUMER)
=> Restrict contextual actions to certain users

src/app/api/admin/policies/policies.controller.js
=> fix(policies): Not able to configure api-key policy from UI

src/app/api/admin/apikeys/apikeys.html, src/app/application/details/apikeys/applicationAPIKeys.html
- fix columns offset when copy-toclipboard icon appears	9692e8b
- fix(apikey): fix add-expiration-date tooltip display d275d35: switch tooltip display from right to left to avoid "glitter"
Closes #89 #91
=> fix(apiKey): fix graphicals bugs on tooltips

src/app/api/admin/events/apiEvents.html
=> Disable rollback and diff with published API for the last event

src/app/api/admin/general/apiGeneral.html
=> feature(pipelining): Add checkbox for HTTP pipelining management

src/app/api/admin/events/apiEvents.html
=> feat(event): rollback last published event

src/app/api/admin/events/apiEvents.controller.js
=> fix(event): undeployed API is last event to compare

src/app/api/admin/events/apiEvents.controller.js, src/app/api/admin/general/apiGeneral.html
=> fix(generalAPI): update API name and version

src/app/components/sidenav/sidenav.html
=> fix(login-icon): replace logout icon by login icon

src/app/application/details/general/applicationGeneral.controller.js, src/app/application/details/general/applicationGeneral.html, src/app/application/dialog/application.dialog.html, src/app/application/dialog/applicationDialog.controller.js
=> fix(application): set correct error message if application already exists

src/app/api/admin/policies/_policies.scss
=> Overlap policy configuration input

src/app/api/apis.controller.js
=> Too much click to create the first api

src/app/api/admin/events/_apiEvents.scss, src/app/api/admin/events/apiEvents.controller.js, src/app/api/admin/events/apiEvents.html, src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/general/apiGeneral.html, src/app/api/admin/history/_apiHistory.scss, src/app/api/admin/history/apiHistory.controller.js, src/app/api/admin/history/apiHistory.html, src/app/api/api.service.js, src/app/index.module.js, src/app/index.route.js
This closes #98 and closes #99
=> Start / stopping an API must not deploy the current definition

src/app/application/details/general/applicationGeneral.controller.js
=> Application list not refreshing after created/updated an application

src/app/api/apis.controller.js, src/app/components/sidenav/sidenav.html
=> API list synchronization issue

src/app/api/apisThumbMode.html, src/app/application/applicationsThumbMode.html, src/app/components/sidenav/_sidenav.scss, src/app/index.scss, src/app/login/dialog/login.dialog.html, src/app/main/_main.scss, src/app/main/main.html, src/index.html
This closes #141 and closes #134
=> Add application default logo and set correct application card height

src/app/instances/details/monitoring/instanceMonitoring.controller.js
=> Disable autorefresh on instance monitoring on route change

bower_components/angular-schema-form/dist/schema-form.js
=> Allows to add element to list on a policy configuration

src/app/api/admin/apiAdmin.controller.js
=> Synchronize api state on creation

src/app/api/apis.controller.js, src/app/index.route.js
=> Avoid to list apis when accessing a specific api

src/app/api/admin/documentation/dialog/apiDocumentation.dialog.html
fix the upload bug
fix the size of the dialog box
fix gravitee-io/issues#90
=> fix(page): Unable to upload a documentation file under Firefox

src/app/api/admin/policies/_policies.scss, src/app/index.scss
This closes gravitee-io/issues#98
=> fix(resource): fix overlapping input form

src/app/api/admin/general/apiGeneral.controller.js, src/app/api/api.service.js
This closes https://github.com/gravitee-io/issues/issues/102
=> Allows to export also if the content-disposition header is not readable on response

src/app/components/autofocus/autofocus.directive.js, src/app/index.module.js
This closes https://github.com/gravitee-io/issues/issues/14
=> Autofocus on login username

src/app/api/admin/healthcheck/healthcheck.controller.js, src/app/api/admin/healthcheck/healthcheck.html
Set the default expectation if none is defined.
Closes gravitee-io/issues#111
=> feat(healthcheck): Expectation should contains at least one assertion to validate form

src/app/components/sidenav/sidenav.html
=> fix(portal): Refresh API definition when navigating in API configuration

src/app/api/apis.controller.js, src/app/user/user.service.js
=> fix(admin): Admin user must be able to manage all APIs and applications

src/app/api/_api.scss, src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/general/apiGeneral.html
=> feat(http): Add HTTP proxy configuration in gateway configuration

src/app/api/admin/documentation/page/apiPage.controller.js, src/app/api/admin/documentation/page/apiPage.html, src/app/components/notification/notification.service.js, src/app/index.interceptor.js
also improve notifications on API response
fix gravitee-io/issues#171
=> fix(page): create page without title

src/app/api/admin/creation/swagger/importSwagger.dialog.html, src/app/api/admin/creation/swagger/importSwaggerDialog.controller.js
=> feat(api): Create an API from a Swagger descriptor URL

src/app/api/admin/members.controller.js, src/app/api/admin/members.html, src/app/api/admin/members/addMember.dialog.html, src/app/api/admin/members/addMemberDialog.controller.js, src/app/api/admin/members/api-permissions-dialog.controller.js, src/app/api/admin/members/permissions.dialog.html, src/app/api/api.service.js, src/app/application/details/apikeys/applicationAPIKeys.html, src/app/application/details/applications.controller.js, src/app/application/details/applications.service.js, src/app/application/details/members/application-permissions-dialog.controller.js, src/app/application/details/members/applicationMembers.controller.js, src/app/application/details/members/applicationMembers.html, src/app/application/details/members/permissions.dialog.html, src/app/application/dialog/addMember.dialog.html, src/app/application/dialog/addMemberDialog.controller.js, src/app/components/sidenav/_sidenav.scss, src/app/index.module.js, src/app/user/user.service.js
=> feat(security): Improve permission management

src/app/api/admin/members/addMemberDialog.controller.js, src/app/application/dialog/addMemberDialog.controller.js
This closes gravitee-io/issues#183
=> Members must not be searched and added if they already exist 

src/app/index.module.js, src/app/index.route.js, src/app/platform/analytics/analytics.service.js, src/app/platform/dashboard/_dashboard.scss, src/app/platform/dashboard/dashboard.controller.js, src/app/platform/dashboard/dashboard.html, src/app/platform/dashboard/dashboardModel.directive.js, src/app/platform/dashboard/dashboardModel.html, src/app/platform/events/events.service.js
This closes gravitee-io/issues#113
=> feat(dashboard): add admin dashboard with API events and global analytics

src/app/api/apisThumbMode.html, src/app/application/applicationsThumbMode.html, src/app/main/_main.scss
This closes gravitee-io/issues#178
=> fix(api-picture): fix api icon overlay issue

bower.json, bower_components/angular-mocks/.bower.json, bower_components/angular-mocks/LICENSE.md, bower_components/angular-mocks/README.md, bower_components/angular-mocks/angular-mocks.js, bower_components/angular-mocks/bower.json, bower_components/angular-mocks/ngAnimateMock.js, bower_components/angular-mocks/ngMock.js, bower_components/angular-mocks/ngMockE2E.js, bower_components/angular-mocks/package.json, e2e/api/policy/policy.po.js, e2e/api/policy/policy.spec.js, e2e/main/main.po.js, e2e/main/main.spec.js, e2e/mocked-backend.js, gulp/build.js, package.json, pom.xml, protractor.conf.js, src/app/index.module.js, src/app/index.run.js
This closes https://github.com/gravitee-io/issues/issues/191
=> Init front end tests with protractor and add some tests on policy add button

src/app/platform/dashboard/_dashboard.scss, src/app/platform/dashboard/dashboard.controller.js, src/app/platform/dashboard/dashboard.html, src/app/platform/dashboard/dashboardAnalyticsCard.html
feat(dashboard): improve admin dashboard with top APIs analytics and keeping active filters mechanism
This closes gravitee-io/issues#192
=> feat(dashboard): improve admin dashboard

src/app/api/apisThumbMode.html
This closes gravitee-io/issues#206
=> feat(apis): display primary owner on each API card

src/app/api/admin/policies/apiPolicies.html, src/app/api/admin/policies/policies.controller.js, src/app/policy/_policy.scss
=> feat(policy): Enable / disable a policy rule

src/app/api/admin/documentation/apiDocumentation.service.js, src/app/api/admin/documentation/page/apiPage.controller.js, src/app/api/admin/documentation/page/apiPage.html, src/app/components/documentation/page.directive.js, src/app/components/documentation/page.html, src/app/components/documentation/pageSwaggerConfiguration.service.js, src/app/components/documentation/pageSwaggerHttpClient.service.js, src/app/index.module.js, src/app/index.run.js
=> feat(documentation): enable tryit mode on swagger

src/app/api/apisThumbMode.html
This closes https://github.com/gravitee-io/issues/issues/229
=> Better display of APIs in views

src/app/api/admin/documentation/page/apiPage.controller.js, src/app/api/admin/resources/resources.controller.js, src/app/components/notification/notification.service.js, src/app/index.interceptor.js
This closes https://github.com/gravitee-io/issues/issues/82
=> Change function's name of error's notification service and avoid use of keyword 'error'

src/app/components/documentation/page.directive.js
=> feat(doc): no try it for anonymous

src/app/components/documentation/pageSwaggerHttpClient.service.js, src/app/index.interceptor.js
=> fix(portal): Do not intercept 401 when invoking an HTTP url from Swagger

src/app/application/details/analytics/analytics.controller.js, src/app/application/details/analytics/analytics.html, src/app/application/details/analytics/analyticsAPIModel.directive.js, src/app/application/details/analytics/analyticsAPIModel.html, src/app/application/details/applications.service.js, src/app/index.module.js, src/app/index.route.js
This closes gravitee-io/issues#238
=> feat(application) : add application analytics

src/app/api/admin/analytics/analytics.controller.js, src/app/api/admin/analytics/analytics.html, src/app/api/admin/analytics/analyticsApplicationModel.directive.js, src/app/api/admin/analytics/analyticsApplicationModel.html, src/app/index.module.js
This closes gravitee-io/issues#193
=> feat(api): use application name instead of application ID for API analytics

src/app/api/admin/analytics/analytics.controller.js
This closes gravitee-io/issues#199
=> feat(api) : do not reload API Analytics Page when selecting a new timeframe

src/app/api/apisList.html, src/app/api/apisThumbMode.html, src/app/components/sidenav/sidenav.directive.js, src/app/index.route.js, src/app/main/main.html, src/constants.js, src/index.html
This closes https://github.com/gravitee-io/issues/issues/181
=> Allows to configure the UI to start in developer mode (without management part)

src/app/api/admin/creation/newApi.controller.js
This closes gravitee-io/issues#215
=> fix(api) : fix API creation process after an invalid context-path value

src/app/api/_api.scss, src/app/api/admin/general/dialog/apiDefinition.dialog.html
This closes gravitee-io/issues#231
=> fix(api) : fix import API on Firefox browser

src/app/api/admin/documentation/apiDocumentation.controller.js, src/app/api/admin/documentation/page/apiPage.controller.js
This fixes gravitee-io/issues#224
=> fix(documentation) : redirect to the current page after saving/updating it

src/app/api/admin/documentation/apiDocumentation.html, src/app/index.scss
This fixes gravitee-io/issues#225
=> fix(documentation) : set (+) button to the bottom of the page

src/app/api/apiHeader.html
=> feat(api): show contextpath on the api header

src/app/api/apisThumbMode.html
This fixes gravitee-io/issues#220
=> fix(view): Do not show views without any API

src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/general/apiGeneral.html, src/app/api/admin/members/members.controller.js, src/app/api/admin/members/members.html, src/app/api/api.service.js, src/app/application/details/applications.service.js, src/app/application/details/general/applicationGeneral.controller.js, src/app/application/details/general/applicationGeneral.html, src/app/application/details/members/applicationMembers.controller.js, src/app/application/details/members/applicationMembers.html, src/app/configuration/admin/groups/dialog/add-group.dialog.controller.js, src/app/configuration/admin/groups/dialog/add-group.dialog.html, src/app/configuration/admin/groups/dialog/addMember.dialog.html, src/app/configuration/admin/groups/dialog/addMemberDialog.controller.js, src/app/configuration/admin/groups/groups.controller.js, src/app/configuration/admin/groups/groups.html, src/app/group/group.service.js, src/app/index.module.js, src/app/index.route.js
=> feat(group): manage group permissions

src/app/api/_api.scss, src/app/api/admin/apiAdmin.controller.js, src/app/api/admin/general/apiGeneral.html, src/app/api/apiHeader.html, src/app/api/portal/apiPortal.controller.js, src/app/components/image/_image.scss, src/app/components/image/image.directive.js, src/app/components/image/image.html
This closes gravitee-io/issues#263
=> feat(api) : set API logo via API header

src/app/api/admin/apiAdmin.controller.js, src/app/api/admin/properties/properties.controller.js, src/app/api/admin/resources/resources.controller.js, src/app/components/image/_image.scss
This closes gravitee-io/issues#267
=> fix(api): fix API icon disappearing

src/app/components/sidenav/sidenav.html
This closes gravitee-io/issues#271
=> fix(api) : resize API sync banner when triggering reduce mode

src/app/configuration/admin/views/views.controller.js
=> fix(portal): Remove totalApis property when updating a view

src/app/api/admin/properties/properties.controller.js, src/app/api/admin/properties/properties.html
This closes gravitee-io/issues#273
=> fix(api): fix API properties empty mode

src/app/api/apis.controller.js, src/app/api/apisList.html
do not get state if the user must not see it
=> fix(api.list): do not get api state if not necessary

src/app/api/admin/analytics/analytics.controller.js, src/app/api/admin/analytics/analytics.html, src/app/application/details/analytics/analytics.controller.js, src/app/application/details/analytics/analytics.html
This closes gravitee-io/issues#311
=> feat(analytics) : prevent multiple analytics executions

src/app/api/admin/documentation/apiDocumentation.html, src/app/api/admin/plans/apiPlans.controller.js, src/app/api/admin/plans/apiPlans.html
=> feat(plan): Plans can be ordered by drag and dropping them

src/app/api/admin/plans/_apiPlans.scss, src/app/api/admin/plans/apiPlans.controller.js, src/app/api/admin/plans/apiPlans.html, src/app/api/admin/plans/closePlan.dialog.html, src/app/api/admin/plans/closePlanDialog.controller.js, src/app/api/admin/plans/publishPlan.dialog.html, src/app/api/admin/plans/publishPlanDialog.controller.js, src/app/api/portal/plan/_plan.scss, src/app/index.module.js, src/app/services/api.service.js
=> feat(plan): Manage API plan status

src/app/api/admin/policies/addPoliciesPath.controller.js, src/app/api/admin/policies/addPoliciesPath.html
=> fix(policies): Remove useless angular provider for apikey

gulp/scripts.js
This closes https://github.com/gravitee-io/issues/issues/324
=> Fail on gulp tasks when js warns

src/app/api/portal/plan/apiPlan.html
=> fix(plan): Subscription button is disabled only for 'edit' mode

src/app/api/admin/general/apiGeneral.controller.js, src/app/index.route.js
=> fix(portal): Inject the correct controller for import / export button

src/app/api/_api.scss, src/app/api/admin/subscriptions/subscription.create.dialog.controller.js, src/app/api/admin/subscriptions/subscription.create.dialog.html, src/app/api/admin/subscriptions/subscriptions.controller.js, src/app/api/admin/subscriptions/subscriptions.html, src/app/index.module.js, src/app/services/api.service.js, src/app/services/applications.service.js
=> feat(subscription): api publisher could add app subscription

src/app/api/admin/documentation/apiDocumentation.html, src/app/api/admin/members/members.html, src/app/api/admin/plans/apiPlans.html, src/app/api/admin/properties/properties.html, src/app/api/admin/resources/resources.html, src/app/api/apisList.html, src/app/application/applicationsList.html, src/app/application/details/members/applicationMembers.html, src/app/components/emptystate/emptystate.html
This closes gravitee-io/issues#279
=> feat(empty-state) : redesign empty states component

src/app/api/admin/analytics/analytics.controller.js, src/app/api/admin/analytics/analyticsApplicationModel.html, src/app/application/details/analytics/analytics.controller.js, src/app/application/details/analytics/analyticsAPIModel.html, src/app/platform/dashboard/dashboardModel.html
This closes gravitee-io/issues#312
=> feat(analytics) : handle deleted api/application analytics

src/app/api/portal/documentation/apiPages.html, src/app/api/portal/plan/apiPlans.html
=> fix(portal): Update message when no plan or no documentation

src/app/api/admin/general/apiGeneral.html, src/app/configuration/admin/tags/tags.html, src/app/index.route.js
This closes https://github.com/gravitee-io/issues/issues/340
=> Coherent tag's wording

src/app/api/admin/plans/_apiPlans.scss, src/app/api/admin/plans/apiPlans.html, src/app/api/admin/plans/closePlan.dialog.html
=> feat(plan): Use a menu for plan settings

src/app/platform/dashboard/dashboardAnalyticsCard.html
=> feat(dashboard): Format numbers (for hits, latency, ...)

src/app/api/admin/documentation/page/apiPage.html
=> fix(documentation): Label pass over the switch button

src/app/instances/details/instanceHeader.html
=> fix(instances): Instance ip is not in the title anymore

src/app/api/admin/analytics/analytics.controller.js, src/app/api/admin/analytics/analytics.html, src/app/api/admin/healthcheck/healthcheck.html, src/app/application/details/analytics/analytics.controller.js, src/app/application/details/analytics/analytics.html, src/app/components/chart/chart.directive.js
This closes https://github.com/gravitee-io/issues/issues/384
=> Allows to synchronize and zoom on analytics charts

src/app/api/admin/analytics/analytics.controller.js, src/app/application/details/analytics/analytics.controller.js
This closes https://github.com/gravitee-io/issues/issues/385
=> Build analytics timestamps with from and interval

src/app/api/admin/general/apiGeneral.html
This closes https://github.com/gravitee-io/issues/issues/389
=> Provide an information on the delete button when disabled

src/app/api/admin/policies/addPoliciesPath.controller.js
=> fix(policy): Create an empty array of policy for the new path

src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/general/apiGeneral.html, src/app/api/apiHeader.html
=> feat: API visibility icons aren't correctly separated

src/app/api/admin/plans/apiPlans.controller.js, src/app/api/admin/plans/closePlanDialog.controller.js, src/app/api/admin/plans/publishPlanDialog.controller.js, src/app/index.route.js
This closes gravitee-io/issues#404
=> feat(plan): better http redirections after API plan operations

bower.json, package.json, src/app/platform/dashboard/dashboardModel.html, src/constants.js
This closes https://github.com/gravitee-io/issues/issues/411
=> Added a link to applications displayed on dashboard

src/app/api/admin/endpoint/endpointConfiguration.html
=> fix: Description of the PEM certificate is misplaced

src/app/index.route.js
This closes https://github.com/gravitee-io/issues/issues/420
=> Allows to login and create an account on dev mode

src/app/instances/details/environment/instanceEnvironment.html
This closes https://github.com/gravitee-io/issues/issues/421
=> Changed label of sharding tags on instance information

src/app/api/admin/documentation/apiDocumentation.html
This closes gravitee-io/issues#417
=> fix(page): do not display 'add page button' in edit mode

src/app/api/portal/plan/subscribePlan.dialog.html
This closes https://github.com/gravitee-io/issues/issues/422
=> Application type on subscription modal

src/app/instances/details/environment/instanceEnvironment.html, src/app/instances/details/instanceHeader.html, src/app/instances/instances.html
=> Port instances display

src/app/api/admin/general/api.html, src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/general/dialog/apiExport.dialog.html, src/app/api/admin/general/dialog/apiExportDialog.controller.js, src/app/api/admin/general/dialog/apiImport.dialog.html, src/app/api/admin/general/dialog/apiImportDialog.controller.js, src/app/api/apis.controller.js, src/app/index.module.js, src/app/services/api.service.js
=> feat(export api): choose what you want to export

src/app/api/admin/apiAdmin.controller.js, src/app/api/admin/documentation/page/apiPage.controller.js, src/app/api/admin/general/apiGeneral.controller.js, src/app/api/admin/history/apiHistory.controller.js, src/app/api/admin/members/members.controller.js, src/app/api/admin/policies/addPoliciesPath.html, src/app/api/admin/policies/policies.controller.js, src/app/api/admin/properties/properties.controller.js, src/app/api/admin/resources/resources.controller.js, src/app/api/admin/subscriptions/subscriptions.controller.js, src/app/application/details/general/applicationGeneral.controller.js, src/app/application/details/members/applicationMembers.controller.js, src/app/application/details/subscriptions/applicationSubscriptions.controller.js, src/app/components/dialog/confirm.dialog.html, src/app/components/dialog/confirmDialog.controller.js, src/app/components/dialog/confirmWarning.dialog.html, src/app/configuration/admin/groups/groups.controller.js, src/app/index.module.js
=> feat(modal): same theme for all Warning and Confirm popup

src/app/api/admin/subscriptions/subscriptions.controller.js
=> fix(plans): Do not list keyless plan for subscriptions

src/app/api/admin/plans/apiPlans.controller.js
=> fix(plan): Set plan form as pristine and untouched

src/app/api/admin/policies/dialog/policy.dialog.html, src/app/api/admin/policies/policies.controller.js, src/app/api/admin/subscriptions/apikey.expiration.dialog.html, src/app/api/admin/subscriptions/subscription.reject.dialog.html, src/app/api/admin/subscriptions/subscriptions.controller.js, src/app/api/apis.controller.js, src/app/application/applications.controller.js, src/app/application/dialog/application.dialog.html
=> fix(portal): Set clickOutsideToClose for modals

src/app/api/admin/general/apiGeneral.controller.js, src/app/application/details/general/applicationGeneral.controller.js
=> fix(sidenav): update api/app name on save

src/app/api/admin/policies/apiPolicies.html
This closes https://github.com/gravitee-io/issues/issues/439
=> Better display of policy path

src/app/api/admin/creation/_apiCreation.scss, src/app/api/admin/creation/newApi.controller.js, src/app/api/admin/creation/newApi.html, src/app/api/admin/creation/steps/_step1.html, src/app/api/admin/creation/steps/_step2.html, src/app/api/admin/creation/steps/_step3.html, src/app/api/admin/creation/steps/_step4.html, src/app/api/admin/creation/steps/_step5.html, src/app/api/admin/creation/steps/steps.html, src/app/api/apis.html, src/app/api/apisList.html, src/app/index.route.js, src/app/services/api.service.js
This closes gravitee-io/issues#418
=> feat(api): enhance create api workflow

src/app/api/admin/analytics/analytics.controller.js, src/app/api/admin/endpoint/endpointConfiguration.controller.js, src/app/api/admin/endpoint/endpointConfiguration.html, src/app/api/admin/general/apiGateway.html, src/app/api/apisList.html, src/app/configuration/admin/tenants/delete.tenant.dialog.controller.js, src/app/configuration/admin/tenants/delete.tenant.dialog.html, src/app/configuration/admin/tenants/tenants.controller.js, src/app/configuration/admin/tenants/tenants.html, src/app/index.module.js, src/app/index.route.js, src/app/instances/details/environment/instanceEnvironment.html, src/app/instances/instances.html, src/app/services/tenant.service.js
=> feat(gateway): Multi-tenant support

src/app/api/admin/general/apiGateway.html, src/app/index.route.js
=> fix(gateway): Use correct controller while switching tabs

src/api/admin/resources/resources.controller.ts
=> fix(resource): Reset configuration when changing resource type

src/api/admin/endpoint/endpointConfiguration.controller.ts, src/api/admin/general/apiGateway.html, src/api/admin/general/apiGeneral.controller.ts, src/index.route.ts
=> fix(gateway): Show the tenant name instead of its ID

src/api/admin/policies/policies.controller.ts
This closes https://github.com/gravitee-io/issues/issues/469
=> Clean empty fields in arrays on save of policy configuration

src/api/admin/policies/apiPolicies.html, src/api/admin/policies/policies.controller.ts
This closes https://github.com/gravitee-io/issues/issues/470
=> Make save button visible on policy screen

src/api/admin/members/members.html, src/api/admin/policies/policies.controller.ts, src/api/apis.controller.ts, src/api/apis.html, src/index.run.ts
=> fix(portal): Several fix after typescript migration

src/api/admin/general/apiGateway.html
=> fix(gateway): Fix issue with ui-router to create a new endpoint

src/management/api/documentation/_apiDocumentation.scss, src/management/api/documentation/apiDocumentation.html, src/management/api/documentation/page/apiPage.controller.ts, src/management/api/documentation/page/apiPage.html, src/services/apiDocumentation.service.ts
=>  feat(pages): set a page as an api homepage

src/application/applications.route.ts, src/application/details/general/application-general.component.ts, src/application/details/general/application-general.controller.ts
=> fix(application): unable to change group

src/management/configuration/configuration.route.ts, src/management/configuration/pages/page/newPage.controller.ts, src/management/configuration/pages/page/page.html, src/management/configuration/pages/portalPages.component.ts, src/management/configuration/pages/portalPages.controller.ts, src/management/configuration/pages/portalPages.directive.ts, src/management/configuration/pages/portalPages.html, src/management/management.module.ts, src/portal/components/navbar/_navbar.scss, src/portal/components/navbar/navbar.html, src/portal/home/_home.scss, src/portal/home/home.controller.ts, src/portal/home/home.html, src/portal/i18n/en.json, src/portal/i18n/fr.json, src/portal/index.html, src/portal/pages/documentation.scss, src/portal/pages/page.component.ts, src/portal/pages/page.html, src/portal/pages/pages.component.ts, src/portal/pages/pages.html, src/portal/portal.module.ts, src/portal/portal.route.ts, src/portal/portal.scss, src/services/portalPages.service.ts
=> feat(pages): add portal pages

src/index.scss, src/management/api/_api.scss, src/management/api/apis.html, src/management/api/creation/newApi.controller.ts, src/management/api/creation/steps/api-creation.controller.ts, src/management/api/documentation/apiDocumentation.controller.ts, src/management/api/general/apiGeneral.controller.ts, src/management/configuration/pages/portalPages.controller.ts, src/portal/api/_api.scss, src/portal/api/apisList.html, src/portal/api/header/api-header.html, src/portal/api/plan/_api-plan.scss, src/portal/pages/documentation.scss, src/portal/pages/page.html, src/portal/pages/pages.component.ts, src/portal/pages/pages.html, src/portal/portal.scss
* remove portal title on the apis management page
* fix apis redirection
* resfresh pages list on delete
* go to plans when click on api name
* some css
=> fix: some fixes

src/management/api/apis.route.ts, src/management/api/resources/resources.controller.ts, src/management/api/resources/resources.html
=> fix(resource): Show resource type name instead of identifier

src/index.route.ts, src/index.scss, src/management/api/healthcheck/_healthcheck.scss, src/management/api/policies/policies.controller.ts, src/management/api/resources/_resources.scss, src/portal/api/plan/api-plans.component.ts, src/portal/api/plan/api-plans.html, src/portal/i18n/fr.json, src/portal/portal.route.ts
* fix(translation): french typo
* fix(portal): hide subscribe button on plan if user not authenticated
=> Portal fix

src/management/api/documentation/apiDocumentation.html
=> fix(doc): owner can add pages no matter his role

src/portal/components/navbar/navbar.html, src/portal/i18n/en.json, src/portal/i18n/fr.json
=> feat(navbar): provide direct access to the apis management view

src/portal/components/navbar/navbar.component.ts, src/services/user.service.ts, src/user/user.controller.ts, src/user/user.html
=> fix(user): user cannot change his picture

src/management/api/policies/policies.controller.ts, src/management/api/resources/resources.controller.ts, src/management/api/resources/resources.html
This closes https://github.com/gravitee-io/issues/issues/564
=> Refresh correctly api when changed on others menus

package.json, src/management/api/properties/_properties.scss, src/management/api/properties/dynamic-provider-http-dialog.controller.ts, src/management/api/properties/dynamic-provider-http.dialog.html
This closes https://github.com/gravitee-io/issues/issues/566
=> fix: Display correctly dynamic property specification example

src/management/api/plans/apiPlans.controller.ts
=> fix(portal): Check API sync status after creation of a plan

src/components/documentation/page-swagger.component.ts
=> fix(portal): Retrieve page content from portal page and not api page

src/components/dashboard/dashboard-filter.controller.ts, src/components/dashboard/dashboard-filter.html, src/components/dashboard/dashboard-timeframe.html, src/components/dashboard/dashboard.component.ts, src/components/dashboard/dashboard.html, src/index.scss, src/management/api/analytics/analytics.controller.ts, src/management/api/analytics/analytics.html, src/management/api/apis.route.ts, src/management/api/logs/_logs.scss, src/management/api/logs/components/logs-timeframe.component.ts, src/management/api/logs/components/logs-timeframe.controller.ts, src/management/api/logs/components/logs-timeframe.html, src/management/api/logs/log.component.ts, src/management/api/logs/log.html, src/management/api/logs/logs.controller.ts, src/management/api/logs/logs.html, src/management/application/applications.route.ts, src/management/application/details/analytics/application-analytics.controller.ts, src/management/application/details/analytics/application-analytics.html, src/management/application/details/logs/application-log.component.ts, src/management/application/details/logs/application-log.html, src/management/application/details/logs/application-logs.component.ts, src/management/application/details/logs/application-logs.controller.ts, src/management/application/details/logs/application-logs.html, src/management/management.module.ts, src/services/api.service.ts, src/services/applications.service.ts
=> feat(log): Request /response analysis

src/portal/api/_api.scss, src/portal/api/header/api-header.component.ts, src/portal/api/header/api-header.html, src/portal/home/_home.scss, src/portal/home/home.html, src/portal/i18n/en.json, src/portal/i18n/fr.json, src/portal/portal.i18n.ts, src/portal/portal.scss
=> fix(portal): Update API header

src/management/api/apis.route.ts, src/management/api/documentation/apiDocumentation.controller.ts, src/management/configuration/pages/portalPages.controller.ts, src/portal/pages/pages.component.ts
=> fix(documentation): Do not use $location to change current view

src/management/api/apis.html
=> fix(api): Do not list API with a user permission

src/management/api/metadata/apiMetadata.controller.ts, src/management/configuration/metadata/metadata.controller.ts
This closes https://github.com/gravitee-io/issues/issues/594
=> Fix dist injection on metadata

src/management/api/endpoint/endpointConfiguration.controller.ts
This closes https://github.com/gravitee-io/issues/issues/582
=> Refresh correctly ui when a gateway endpoint is added

build.json, package.json, src/management/configuration/groups/dialog/addMemberDialog.controller.ts
This closes https://github.com/gravitee-io/issues/issues/301
=> Correctly manage table data on adding of multiple members on a group

src/management/api/policies/_policy.scss, src/management/api/policies/apiPolicies.html, src/management/api/policies/policies.controller.ts
This closes https://github.com/gravitee-io/issues/issues/155
=> Manage unknown policies

src/management/api/policies/apiPolicies.html, src/management/api/policies/policies.controller.ts
This closes https://github.com/gravitee-io/issues/issues/611
=> Check name instead of schema to know if policy is unknown

src/management/configuration/metadata/dialog/save.metadata.dialog.html
This closes https://github.com/gravitee-io/issues/issues/613
=> Metadata key is read only on update

constants.json, constants.tpl.json, package.json, src/authentication/authentication.config.ts, src/index.scss, src/index.ts, src/management/management.interceptor.ts, src/management/management.module.ts, src/portal/components/navbar/navbar.html, src/portal/portal.module.ts, src/services/authentication.service.ts, src/user/login/_login.scss, src/user/login/login.controller.ts, src/user/login/login.html, src/user/registration/registration.html
=> Social authentication

conf/webpack.conf.js, constants.json, src/index.html, src/index.ts
=> feat(portal): Customize the loader

src/index.ts
=> fix(portal): Constants injector

constants.json, src/index.ts, src/portal/components/navbar/navbar.component.ts, src/portal/home/home.controller.ts, src/portal/portal.route.ts
=> refactor(portal): Theme constants

src/management/api/plans/apiPlans.controller.ts
=> fix(plan):API out of sync banner when closing plan

src/portal/home/home.html, themes/default-theme.json, themes/light-theme.json
=> fix(portal): Home page background

src/portal/api/_api.scss, src/portal/api/apis.controller.ts, src/portal/api/apisList.html, src/portal/home/home.html, src/portal/i18n/en.json, src/portal/i18n/fr.json
=> feat(portal): APIs Gallery - New  menu, filter and api views

src/portal/components/navbar/navbar.html, src/portal/i18n/en.json, src/portal/i18n/fr.json
=> feat(portal): Add documentation menu to the navbar

src/management/api/_api.scss, src/management/api/general/apiGateway.html, src/management/api/general/apiGeneral.controller.ts, src/management/api/general/apiGeneral.html, src/services/api.service.ts
=> feat(api): Associate labels to API

src/management/configuration/views/views.controller.ts
=> fix(view): Remove totalApis property when updating a view

src/components/widget/_widget.scss, src/components/widget/widget-data-table.component.ts, src/components/widget/widget-data-table.html, src/index.scss, src/management/platform/dashboard/dashboard.controller.ts
=> feat(dasboard): Add link to API or application's analytics view

src/management/application/details/subscriptions/application-subscriptions.controller.ts, src/management/application/details/subscriptions/application-subscriptions.html
=> feat(subscription): Add a link to the API and the API's version

constants.tpl.json, src/management/management.interceptor.ts, src/services/analytics.service.ts, src/services/api.service.ts, src/services/applications.service.ts
=> fix(analytics): Default timeout for analytics set to 30 seconds

constants.json, constants.tpl.json, src/authentication/authentication.config.ts, src/services/authentication.service.ts, src/user/login/login.html
=> feat(portal): Add custom OAuth2 authentication provider

src/portal/portal.i18n.ts
=> fix(translation): add fallback language to EN

src/management/api/endpoint/endpointConfiguration.controller.ts, src/management/api/endpoint/endpointConfiguration.html
=> feat(endpoint): SSL automatically enabled when enabling trustAll

src/management/api/logs/log.html
=> feat(log): Add a message settled by the gateway in case of error

src/management/api/logs/log.html
=> feat(log): Add gateway identifier

src/portal/components/navbar/_navbar.scss, src/portal/components/navbar/navbar.html, src/portal/home/_home.scss, src/portal/home/home.html, src/portal/index.html, src/portal/portal.scss
=> fix(logo): Ratio

src/portal/home/home.controller.ts, src/portal/home/home.html
=> feat(api-views): display on homepage

src/management/api/_api.scss, src/portal/api/apisList.html, src/portal/home/home.html
=> fix(portal): Alignment of APIs

package.json, src/management/api/_api.scss, src/management/api/general/apiGeneral.controller.ts, src/management/api/general/apiGeneral.html, src/management/api/header/api-header.component.ts, src/management/api/header/api-header.controller.ts, src/management/api/header/api-header.html, src/management/management.module.ts
=> feat(portal): Improve the UX when edit an API

src/components/documentation/page-sidenav.directive.ts, src/components/metadata/metadata.validator.directive.ts
=> fix(bug): TypeScript errors in development

src/management/api/apis.route.ts
=> fix(documentation): Use correct right

src/components/avatar/user-avatar.directive.ts, src/portal/components/navbar/navbar.component.ts
This closes gravitee-io/issues#705
=> fix(portal): use relative path for the default user icon

src/management/api/_api.scss, src/management/api/general/apiGeneral.controller.ts, src/management/api/general/apiGeneral.html, src/management/api/header/api-header.component.ts, src/management/api/header/api-header.controller.ts, src/management/api/header/api-header.html, src/management/management.module.ts
=> feat(portal): Improve the UX when update API infos

src/components/dashboard/dashboard.component.ts, src/components/dashboard/dashboard.html, src/management/api/analytics/analytics.html, src/management/application/details/analytics/application-analytics.html
=> fix(logs): Logs are not accessible from the dashboard view

src/components/documentation/page-swagger.component.ts, src/components/documentation/page-swagger.html, src/components/documentation/page.component.ts, src/components/documentation/page.html, src/management/api/documentation/page/apiPage.html
=> fix(page): Live editing Swagger page

constants.json, src/portal/index.html, src/portal/portal.scss, themes/default-theme.json, themes/light-theme.json
=> feat(portal): Customize footer links

src/management/configuration/groups/groups.html
=> feat: Allows to sort application/api's groups

src/management/api/general/apiGeneral.controller.ts
=> fix(endpoint): Add tenant information per endpoint

src/authentication/authentication.config.ts
=> fix(authentication): Remove additional slash prefix

src/management/api/creation/steps/api-creation-step1.html, src/management/api/general/apiGateway.html
=> fix(api): Context-path accept letters, numbers, dash and underscore

src/management/api/plans/apiPlans.controller.ts, src/management/api/plans/apiPlans.html
=> Avoid plans to disappear on dnd

src/management/api/subscriptions/subscription.accept.dialog.controller.ts, src/management/api/subscriptions/subscription.accept.dialog.html
=> fix(subscription): Use correct property for subscription end date.

build.json, package.json, src/index.scss, src/management/api/apis.route.ts, src/management/api/general/apiGeneral.controller.ts, src/management/api/general/apiGeneral.html, src/management/api/members/members.controller.ts, src/management/api/members/members.html, src/management/application/applications.route.ts, src/management/application/details/general/application-general.controller.ts, src/management/application/details/general/application-general.html, src/management/application/details/members/application-members.component.ts, src/management/application/details/members/application-members.controller.ts, src/management/application/details/members/application-members.html, src/management/configuration/groups/dialog/addMemberDialog.controller.ts, src/management/configuration/groups/groups.controller.ts, src/management/configuration/groups/groups.html, src/services/api.service.ts, src/services/applications.service.ts, src/services/group.service.ts
=> feat(groups): move api/app groups to user groups

src/management/api/members/members.controller.ts, src/management/api/members/members.html
=> fix(members): admin must be allowed to change PO

constants.json, src/management/api/creation/newApi.html, src/management/api/creation/steps/api-creation-step5.component.ts, src/management/api/creation/steps/api-creation-step5.html, src/user/registration/confirm/confirm.html
=> fix(portal): Missing translations

src/management/api/general/apiGateway.html
=> fix(gateway): Admin must be able to change API context-path

src/management/instances/instances.html
=> feat(instances): Add version and tenant info

src/components/documentation/_page.scss, src/components/documentation/page-markdown.html
=> fix(page): Set CSS class for markdown page

src/management/api/general/apiGeneral.controller.ts, src/management/api/general/apiGeneral.html
=> fix(group): Show group name instead of technical ID

src/management/api/general/apiGateway.html
=> Sorting is not working on gateway endpoints

src/management/api/general/apiGateway.html
=> Validation's message is not the same on context-path modification and creation

src/management/api/logs/log.html
=> Add the remote IP on the logs

src/management/api/healthcheck/healthcheck-visualize.html
=> feat(health-check): Add button to refresh data

src/management/instances/instances.html
=> feat(instances): Include gateway sharding tags in instances view

src/management/configuration/tags/tags.controller.ts, src/management/configuration/tags/tags.html, src/management/configuration/tenants/tenants.controller.ts, src/management/configuration/tenants/tenants.html
=> feat(management): display tenant and tag ids

src/management/api/general/apiGateway.html, src/management/api/general/apiGeneral.controller.ts, src/management/api/logs/log.component.ts, src/management/api/logs/log.html, src/management/application/details/logs/application-log.html
=> feat(logging): Show API logs if log has been enabled

src/management/api/documentation/page/apiPage.controller.ts, src/management/api/documentation/page/apiPage.html, src/management/api/plans/apiPlans.controller.ts, src/management/api/plans/apiPlans.html, src/services/api.service.ts, src/services/apiDocumentation.service.ts
=> feat(groups): restrict pages and documentation to a set of groups

src/index.html
=> fix: display a disclaimer on IE browsers older than edge

src/management/api/events/apiEvents.controller.ts, src/management/api/events/apiEvents.html, src/management/api/header/api-header.html, src/management/api/history/apiHistory.controller.ts, src/management/api/history/apiHistory.html, src/management/api/members/members.controller.ts, src/management/api/members/members.html, src/management/application/details/header/application-header.html
=> Display the complete name instead of just the username

src/management/api/_api.scss, src/management/api/general/apiGateway.html, src/management/api/general/apiGeneral.controller.ts
=> feat(cors): Add CORS configuration at proxy level

build.json, constants.json, constants.tpl.json, package.json, src/entities/user.ts, src/index.route.ts, src/management/management.module.ts, src/portal/components/navbar/navbar.component.ts, src/portal/components/navbar/navbar.html, src/portal/i18n/en.json, src/portal/i18n/fr.json, src/portal/portal.scss, src/services/ticket.service.ts, src/support/ticket.controller.ts, src/support/ticket.html
=> Contact screen to send an email to the support team

build.json, conf/webpack-dist.conf.js, package.json, pom.xml
=> Put the localhost target rest API server on the dist's constants.json

src/management/api/apis.route.ts, src/management/api/healthcheck/healthcheck-log.controller.ts, src/management/api/healthcheck/healthcheck-log.html, src/management/api/healthcheck/healthcheck-visualize.html, src/management/api/healthcheck/healthcheck.controller.ts, src/management/management.module.ts, src/services/api.service.ts
=> feat(healthcheck): Store more information in case of HC fail

src/management/api/apis.route.ts, src/management/application/applications.route.ts, src/portal/components/navbar/navbar.html
=> Be sure to load API/APP permissions before to enter on the detail page

src/management/api/endpoint/endpointConfiguration.controller.ts, src/management/api/general/apiGateway.html
=> Sometimes some policies modifications are lost + allows multiple remove of endpoints

src/management/api/endpoint/endpointConfiguration.controller.ts, src/management/api/general/api.html
=> Allows to save correctly an endpoint

src/management/instances/instances.html
=> fix(instances): do not truncate gateway instance version

src/management/configuration/configuration.route.ts, src/management/configuration/pages/page/newPage.controller.ts, src/management/configuration/pages/page/page.html, src/services/portalPages.service.ts
=> feat(pages): add group restrictions on portal pages

src/management/api/logs/log.html, src/management/application/details/logs/application-log.html
=> feat(log): Improve log description

constants.json, constants.tpl.json, package.json, src/index.html, src/portal/portal.module.ts, yarn.lock
=> Add google analytics

src/management/api/subscriptions/subscriptions.controller.ts, src/management/api/subscriptions/subscriptions.html, src/services/api.service.ts
=> Allows to close a subscription

src/index.ts, src/portal/i18n/loader.ts
This closes gravitee-io/issues#879
=> Disable cache on config and theme json files

src/management/api/creation/steps/api-creation-step3.html, src/management/api/creation/steps/api-creation.controller.ts
=> fix(plan): Set correct timeframe for quota and rate-limit

src/management/api/creation/steps/api-creation-step3.html, src/management/api/plans/apiPlans.html
=> fix(plan):  Auto validation swith is not well displayed

src/portal/api/apis.controller.ts, src/portal/api/header/api-header.component.ts, src/portal/api/rating/apiRating.controller.ts, src/portal/components/navbar/navbar.component.ts, src/portal/home/home.controller.ts, src/portal/portal.module.ts
=> fix(): set defaults values to Constants object

src/management/api/apis.route.ts, src/management/configuration/configuration.route.ts, src/management/configuration/views/views.controller.ts, src/management/configuration/views/views.html, src/portal/api/apis.controller.ts, src/portal/api/apisList.html, src/portal/i18n/en.json, src/portal/i18n/fr.json, src/portal/portal.route.ts, src/services/view.service.ts
=> feat(views): make views sortable, hidden and choose the default one

src/management/api/members/members.controller.ts, src/management/application/details/members/application-members.controller.ts, src/management/application/details/members/application-members.html, src/management/application/details/members/transferApplication.dialog.html, src/management/application/details/members/transferApplicationDialog.controller.ts, src/management/management.module.ts, src/services/applications.service.ts
=> feat(members): change the application PO

src/management/api/members/members.controller.ts, src/management/api/members/members.html, src/management/api/members/transferAPI.dialog.html, src/management/api/members/transferAPIDialog.controller.ts, src/management/application/details/members/application-members.controller.ts, src/management/application/details/members/application-members.html, src/management/application/details/members/transferApplication.dialog.html, src/management/application/details/members/transferApplicationDialog.controller.ts, src/services/api.service.ts, src/services/applications.service.ts
=> feat(member): set the new role of the old primaryOwner

src/management/application/applications.route.ts, src/management/management.run.ts
=> fix(portal): Dev mode is not always defined in route

docs/management-api-discovery.md, src/management/api/apis.route.ts, src/management/api/discovery/discovery.controller.ts, src/management/api/discovery/discovery.html, src/management/api/resources/resources.html, src/management/management.module.ts
=> feat(endpoint-discovery): Add endpoint discovery feature

build.json, package.json, src/components/chart/chart.directive.ts, src/components/widget/widget-chart-line.component.ts, src/management/api/healthcheck/healthcheck-visualize.html, src/management/api/healthcheck/healthcheck.controller.ts, src/management/management.module.ts, src/services/api.service.ts, src/services/chart.service.ts
This closes gravitee-io/issues#889
=> feat: Added a chart to display global Health Check average

src/management/api/logs/_logs.scss, src/management/api/logs/components/logs-filters.component.ts, src/management/api/logs/components/logs-filters.controller.ts, src/management/api/logs/components/logs-filters.html, src/management/api/logs/components/logs-timeframe.html, src/management/api/logs/logs.controller.ts, src/management/api/logs/logs.html, src/management/management.module.ts
This closes gravitee-io/issues#703
=> feat(logs): filter API requests logs

src/management/api/general/apiGeneral.controller.ts
This closes gravitee-io/issues#943
=> fix: Do not keep data on API when navigating

src/management/api/apis.controller.ts, src/management/api/apis.html, src/management/api/apis.route.ts
=> fix(apis): always display all apis

src/management/api/apis.route.ts
=> fix(api): always list all views in the api management

build.json, docs/management-tasks.md, package.json, src/entities/pagedResult.ts, src/entities/task.ts, src/entities/user.ts, src/index.scss, src/management/api/subscriptions/subscriptions.controller.ts, src/management/management.module.ts, src/management/management.route.ts, src/management/tasks/tasks.component.ts, src/management/tasks/tasks.html, src/portal/components/navbar/_navbar.scss, src/portal/components/navbar/navbar.component.ts, src/portal/components/navbar/navbar.html, src/portal/home/_home.scss, src/portal/i18n/en.json, src/portal/i18n/fr.json, src/services/task.service.ts, src/services/user.service.ts, themes/default-theme.json, themes/light-theme.json
=> feat(taks): add a task list for each user

constants.tpl.json, src/index.ts, themes/assets/gravitee.css
=> [portal] add personal css with theme

src/management/api/apis.controller.ts, src/management/api/apis.html
This closes gravitee-io/issues#1010
=> fix: Allows to filter correctly manageable apis list

src/portal/api/header/api-header.html
This closes gravitee-io/issues#1003
=> feat: Show the full name instead of username

src/components/documentation/_page.scss, src/components/documentation/page.html, src/portal/api/documentation/api-pages.component.ts
This closes gravitee-io/issues#1007
=> feat: Allows to display a warning message on portal drafts documentation

src/components/contextual/_contextual-doc.component.scss
=> fix(documentation): be able to scroll contextual documentation

src/components/sidenav/sidenav.component.ts, src/components/sidenav/sidenav.html
=> fix(sidenav): store the state of the sidenav

src/management/api/general/apiGeneral.controller.ts
=> feat(view): Do not allow to add/remove the  view on an API.

constants.json, constants.tpl.json, src/index.scss, src/portal/api/_api.scss, src/portal/api/apis.controller.ts, src/portal/api/apisList.html
This closes gravitee-io/issues#1004
=> feat: Allows to display portal apis on list mode

src/management/api/apiAdmin.controller.ts, src/management/api/discovery/discovery.controller.ts, src/management/api/endpoint/endpointConfiguration.controller.ts, src/management/api/general/apiGeneral.controller.ts, src/management/api/healthcheck/healthcheck-configure.controller.ts, src/management/api/properties/properties.controller.ts, src/portal/portal.route.ts, src/services/api.service.ts, src/services/notification.service.ts
This closes gravitee-io/issues#999
=> feat: Allows to handle concurrent modifications on API

src/portal/api/plan/_api-plan.scss, src/portal/api/plan/api-plans.component.ts, src/portal/api/plan/api-plans.html
=> fix(plan): Plan description is truncated

src/management/api/healthcheck/healthcheck-configure.controller.ts
=> feat(healthcheck): do not enable HC by default

src/management/api/members/addMember.dialog.html, src/management/api/members/addMemberDialog.controller.ts, src/management/application/details/members/addMember.dialog.html, src/management/application/details/members/addMemberDialog.controller.ts, src/management/configuration/roles/user/add/add.user.dialog.controller.ts, src/management/configuration/roles/user/add/add.user.dialog.html
Closes gravitee-io/issues#1036
=> fix(user): Resolve user picture url when using ng-src

constants.tpl.json, src/components/dashboard/dashboard-filter.controller.ts, src/components/widget/widget-data-table.component.ts, src/components/widget/widget-data-table.html, src/management/api/analytics/analytics.controller.ts, src/management/application/details/analytics/application-analytics.controller.ts
=> feat(geoip): add geolocation country and city in the dashboard

src/management/api/general/apiGateway.html
=> fix(failover): set the default timeout > 0

src/services/notification.service.ts, yarn.lock
This closes gravitee-io/issues#160
=> feat: allows to configure specific CORS headers

src/management/api/creation/steps/api-creation.controller.ts
=> fix(ui): fix API creation wizard with deploy and start option

constants.tpl.json, src/index.route.ts, src/portal/components/navbar/navbar.component.ts, src/portal/components/navbar/navbar.html, src/user/login/login.controller.ts, src/user/login/login.html
1. single sign out
1. better ui in case of only oauth provider used
fix issue: https://github.com/gravitee-io/issues/issues/1060
=> better oauth2 ui integration

src/components/widget/widget-chart-pie.component.ts
=> fix(analytics): add informations about failed requests

src/components/audit/audit.component.ts, src/components/audit/audit.html, src/entities/user.ts, src/management/configuration/groups/groups.html
=> fix(audit): use the display name

build.json, docs/management-configuration-top_apis.md, package.json, src/management/configuration/configuration.route.ts, src/management/configuration/top-apis/dialog/add.top-api.dialog.controller.ts, src/management/configuration/top-apis/dialog/add.top-api.dialog.html, src/management/configuration/top-apis/dialog/delete.top-api.dialog.controller.ts, src/management/configuration/top-apis/dialog/delete.top-api.dialog.html, src/management/configuration/top-apis/top-apis.component.ts, src/management/configuration/top-apis/top-apis.controller.ts, src/management/configuration/top-apis/top-apis.html, src/management/configuration/views/views.html, src/management/management.module.ts, src/portal/home/home.html, src/portal/portal.route.ts, src/services/api.service.ts, src/services/role.service.ts, src/services/top-api.service.ts
This closes gravitee-io/issues#932
=> feat: allows to configure top APIs displayed on portal

src/management/api/endpoint/endpointConfiguration.html, src/management/api/general/apiGateway.html, src/management/api/general/apiGeneral.controller.ts
Closes gravitee-io/issues#1056
=> feat(tenant): An endpoint can be associated to multiple tenants

src/components/documentation/page-swagger.component.ts
=> feat(swagger): collapse tags and hide url

src/portal/i18n/zh.json
closes gravitee-io/issues#1160
=> feat(i18n):add the i18n for chinese

constants.json, constants.tpl.json, src/portal/home/home.html, src/portal/i18n/fr.json, src/portal/index.html, src/portal/portal.route.ts
This closes gravitee-io/issues#1148
=> fix: Allows to configure the brand of the portal title

src/management/api/apiAdmin.controller.ts
This closes gravitee-io/issues#1138
=> fix: Refresh correctly API when the API picture is changed

src/management/api/logs/components/logs-filters.controller.ts, src/management/api/logs/components/logs-filters.html, src/management/api/logs/log.html
=> fix(metrics): index uri instead of path

src/components/notificationsettings/notificationsettings.html, src/components/sidenav/sidenav.component.ts, src/index.scss, src/management/_submenu.scss, src/management/configuration/configuration.route.ts, src/management/configuration/metadata/metadata.html, src/management/configuration/pages/page/newPage.controller.ts, src/management/configuration/pages/portalPages.controller.ts, src/management/configuration/pages/portalPages.html, src/management/configuration/roles/role/save/role.save.controller.ts, src/management/configuration/roles/role/save/role.save.html, src/management/configuration/roles/roles.controller.ts, src/management/configuration/settings.component.ts, src/management/configuration/settings.html, src/management/configuration/top-apis/top-apis.html, src/management/management.module.ts
=> feat(menu): config menu refactoring

src/components/documentation/_page.scss
Closes gravitee-io/issues#1178
=> fix(documentation): minor styling issues with swagger 3.0

src/management/api/portal/subscriptions/subscription.html, src/management/application/details/subscriptions/application-subscription.html
=> fix(subscription): display the subscribedBy name

src/services/user.service.ts, src/user/user.html
=> fix(user): update user avatar

src/management/api/portal/subscriptions/subscription.accept.dialog.controller.ts, src/management/api/portal/subscriptions/subscription.accept.dialog.html, src/management/api/portal/subscriptions/subscription.html, src/management/application/details/subscriptions/application-subscription.html, src/portal/api/subscribe/api-subscribe.component.ts, src/portal/api/subscribe/api-subscribe.html, src/services/applications.service.ts
=> feat(subscription): add a reason on accept and on request

src/portal/i18n/zh.json
Closes gravitee-io/issues#1201
=> fix: the Chinese translation is not very accurate

src/management/api/analytics/logs/components/logs-filters.controller.ts
Closes gravitee-io/issues#1193
=> fix(http): Handle properly unknown HTTP method

docs/management-api-plans-wizard.md, src/management/api/portal/apis.portal.route.ts
This closes gravitee-io/issues#1222
=> fix: Add contextual doc on plan creation wizard

src/management/portalnotifications/portalnotifications.component.ts
Closes gravitee-io/issues#1225
=> feat(management): adding the notification html5

docs/management-configuration-group.md, src/management/configuration/configuration.route.ts, src/management/configuration/group/group.html, src/management/configuration/groups/groups.component.ts, src/management/configuration/groups/groups.html, src/management/configuration/settings.component.ts, src/management/configuration/settings.html, src/management/configuration/user/user.html
=> feat(group): Delegate the management of a group

src/management/api/portal/plans/closePlanDialog.controller.ts
Closes gravitee-io/issues#1116
=> fix(plan): Keyless plans are now closed instead of deleted

src/management/api/proxy/backend/healthcheck/healthcheck-log.html
=> feat(hc): add back button

src/management/api/proxy/backend/endpoint/endpointConfiguration.html
=> fix(endpoint): Disable autofill for endpoint form

src/index.ts, src/management/configuration/portal/portal.component.ts, src/management/configuration/portal/portal.html
provide a way to override values comming from the rest-api with values comming from contants.json
=> feat(config): override database settings

src/index.html, src/index.route.ts, src/user/login/login.controller.ts, src/user/login/login.html
This closes gravitee-io/issues#1231
=> feat: avoid the blink effect when accessing or leaving the login screen

src/management/api/proxy/apis.proxy.route.ts
Closes gravitee-io/issues#1251
=> fix(endpoint): Resolve list of tenants before displaying UI view

src/_constants.scss
=> fix(sidenav): center sidenav items

src/management/configuration/group/addMember.dialog.html
=> fix(groups): do not allow PO as default user role

src/management/api/creation/newApi.controller.ts
be able to create an api with an openapi definition
fix gravitee-io/issues#1246
=> feat(api): import openapi

src/management/configuration/settings.html
=> fix(views): Views settings are no longer available

src/management/management.run.ts, src/portal/components/navbar/navbar.component.ts
=> fix(tasks): Do not fetch tasks if window is blurred

src/services/user.service.ts
This closes gravitee-io/issues#1260
=> fix: Force refresh of user avatar on user change

src/components/image/image.directive.ts
This closes gravitee-io/issues#1263
=> feat: allows to reduce size of uploaded pictures before to save it

build.json, package.json, src/management/management.interceptor.ts, src/user/login/login.controller.ts
This closes gravitee-io/issues#1259
=> fix: Allows to define cookie on a specific domain, path

src/management/api/portal/general/apiPortal.controller.ts
This closes gravitee-io/issues#1171
=> fix: do not reset visibility state after save

src/services/user.service.ts
This closes gravitee-io/issues#1290
=> fix: Avoid js error when user is logging out

src/portal/api/rating/api-ratings.html
This closes gravitee-io/issues#1288
=> feat: Increase size of rating comment field

src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts
This closes gravitee-io/issues#1083
=> fix: take care of dates on HC zoom

src/management/api/proxy/backend/healthcheck/healthcheck-visualize.html, src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts
This closes gravitee-io/issues#1240
=> feat: allows to display HC status transitions

src/portal/i18n/en.json
This closes gravitee-io/issues#1294
=> fix: Missing translations on english version

src/portal/api/header/api-header.html
This closes gravitee-io/issues#1296
=> fix: Image is not well displayed on portal api header

src/management/configuration/portal/portal.html
=> fix(settings): typo on theme inputs

src/components/progressbar/progress-bar.html, src/management/api/proxy/backend/healthcheck/_healthcheck.scss
=> fix(progressbar): display % in black if the value is too low

src/management/management.interceptor.ts, src/portal/api/_api.scss, src/portal/api/header/api-header.component.ts, src/portal/api/header/api-header.html, src/portal/api/support/api-support.component.ts, src/portal/portal.module.ts, src/portal/portal.route.ts, src/support/ticket.controller.ts, src/support/ticket.html
This closes gravitee-io/issues#1241
=> feat: add a link to support on api portal view

src/management/management.interceptor.ts, src/portal/portal.route.ts
This closes gravitee-io/issues#1309
=> fix: A user not authenticated cannot access to a public API

docs/management-api-proxy-group.md, src/management/api/proxy/apiProxy.controller.ts, src/management/api/proxy/apis.proxy.route.html, src/management/api/proxy/apis.proxy.route.ts, src/management/api/proxy/backend/endpoint/apiEndpoints.html, src/management/api/proxy/backend/endpoint/endpointConfiguration.controller.ts, src/management/api/proxy/backend/endpoint/group.controller.ts, src/management/api/proxy/backend/endpoint/group.html, src/management/api/proxy/backend/failover/apiProxyFailover.html, src/management/api/proxy/general/apiProxyCORS.html, src/management/api/proxy/general/apiProxyDeployments.html, src/management/api/proxy/general/apiProxyGeneral.html, src/management/management.module.ts
=> feat(gateway): Manage group of endpoints

src/management/platform/dashboard/dashboard.controller.ts
=> fix(analytics): some platform analytics take into account all apis

src/management/api/apis.html
closes gravitee-io/issues#1156
=> feat(ui): sort api list by context-path and state

src/index.scss, src/management/configuration/configuration.route.ts, src/management/configuration/portal/portal.html, src/management/configuration/views/view/_view.scss, src/management/configuration/views/view/delete-api-view.dialog.controller.ts, src/management/configuration/views/view/delete-api-view.dialog.html, src/management/configuration/views/view/view.component.ts, src/management/configuration/views/view/view.controller.ts, src/management/configuration/views/view/view.html, src/management/configuration/views/views.controller.ts, src/management/configuration/views/views.html, src/management/management.module.ts, src/portal/api/api-list.controller.ts, src/portal/api/api-list.html, src/portal/components/navbar/navbar.html, src/portal/home/home.controller.ts, src/portal/home/home.html, src/portal/i18n/en.json, src/portal/i18n/fr.json, src/portal/i18n/zh.json, src/portal/portal.module.ts, src/portal/portal.route.ts, src/portal/portal.scss, src/portal/views/_views.scss, src/portal/views/view/_view.scss, src/portal/views/view/view.controller.ts, src/portal/views/view/view.html, src/portal/views/views.controller.ts, src/portal/views/views.html, src/services/view.service.ts
Closes gravitee-io/issues#1011
=> feat(view): allow APIs to be grouped on a single view tile

src/support/ticket.controller.ts, src/support/ticket.html
This closes gravitee-io/issues#1359
=> fix: Support form should be pristine after submit

src/components/documentation/page-swagger.component.ts, src/management/api/portal/documentation/pages/page/apiPage.html, src/management/configuration/pages/page/page.html
=> feat(page): add more options on swagger ui

src/management/api/creation/steps/api-creation.controller.ts
=> fix(api): error on the api wizard

src/portal/views/view/view.controller.ts
=> fix(views): permit access to public views

src/management/configuration/groups/groups.component.ts
=> fix(group): typo on the group addition notification

src/management/api/apiAdmin.controller.ts, src/management/api/portal/apis.portal.route.html, src/management/api/proxy/apis.proxy.route.html
=> fix(menu): reflect user permissions

src/management/api/analytics/apis.analytics.route.ts, src/management/api/analytics/logs/logs.html, src/management/application/applications.route.ts, src/management/application/details/logs/application-logs.html, src/services/api.service.ts, src/services/applications.service.ts
closes gravitee-io/issues#1412
=> feat(log): add log timestamp to select elasticsearch indices

src/management/api/proxy/backend/endpoint/endpointConfiguration.html
Closes gravitee-io/issues#1401
=> feat(endpoint): Variable rsolution for endpoint's configuration

src/entities/qualityMetrics.ts, src/management/api/_api.scss, src/management/api/apis.controller.ts, src/management/api/apis.html, src/management/api/portal/general/apiPortal.controller.ts, src/management/api/portal/general/apiPortal.html, src/management/configuration/portal/portal.html, src/services/api.service.ts
=> feat(quality): add api quality metrics

src/components/dashboard/dashboard-filter.controller.ts
Closes gravitee-io/issues#1411
=> fix(analytics): A selectable field can not be selected again

src/portal/api/api-list.controller.ts, src/portal/api/api-list.html
Closes gravitee-io/issues#1447
=> feat(api): Associate a CSS class per API's view for customization.

src/management/application/create-application.html, src/management/application/details/general/application-general.html
Hi, we would like to use client ids longer than 50 characters. Would it be OK to increase the max length to 100? Otherwise we'll use a fork of this repository.
=> increase clientId maxlength from 50 to 100

pom.xml, src/management/management.interceptor.ts
This closes gravitee-io/issues#1405
=> fix: Redirections does not work well for registration/login

src/portal/portal.module.ts
This closes gravitee-io/issues#1450
=> fix: Google analytics is not working

src/entities/user.ts, src/index.route.ts, src/management/management.interceptor.ts, src/management/management.module.ts, src/portal/components/navbar/navbar.component.ts, src/portal/portal.module.ts, src/services/router.service.ts, src/services/user.service.ts, src/user/login/login.controller.ts
Closes gravitee-io/issues#1466
=> fix(portal): Do not redirect user to home page when accessing direct URL

src/components/notificationsettings/notificationsettings.component.ts
=> fix(notification) add confirm dialog on delete

src/management/configuration/configuration.route.ts, src/services/role.service.ts
=> fix(perms) remove unused perms

src/management/application/details/members/application-members.html
=> fix(members) Do not allow a RO member to search for members in an app

src/management/api/analytics/logs/logs.html, src/management/application/details/logs/application-logs.html
=> fix(logs): remove ids form the logs table

src/management/api/apis.controller.ts, src/management/configuration/group/group.component.ts, src/management/configuration/group/group.html, src/management/configuration/groups/groups.html, src/management/configuration/roles/roles.html, src/management/configuration/user/user.html, src/management/configuration/user/userdetail.component.ts, src/management/configuration/users/users.html, src/services/group.service.ts, src/services/user.service.ts
=> feat(management): show apis and apps for a user or a group

package.json, src/management/api/_api.scss, src/management/api/analytics/logs/components/logs-timeframe.html, src/management/api/portal/plans/list-plans.html
This closes gravitee-io/issues#1388
=> fix: revert deploy banner size + timeframe buttons

src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts
This closes gravitee-io/issues#1467
=> fix: Error when enabling health check

docs/management-messages.md, src/components/messages/messages.component.ts, src/components/messages/messages.html, src/management/api/messages/apis.messages.route.ts, src/management/management.module.ts, src/management/management.route.ts, src/services/message.service.ts, src/services/role.service.ts
=> feat(messages): add the message feature

src/management/configuration/portal/portal.html
=> fix(settings): allow user to set the css theme file

src/management/api/apiAdmin.controller.ts, src/management/api/apis.controller.ts, src/management/api/portal/documentation/pages/apiDocumentation.controller.ts, src/management/configuration/pages/portalPages.controller.ts, src/portal/api/api-list.controller.ts, src/portal/pages/pages.component.ts, src/portal/pages/pages.html
This closes gravitee-io/issues#1472
=> fix: Button add page disappear when using back history of browser

docs/management-configuration-dictionaries.md, docs/management-configuration-dictionary.md, src/management/api/apiAdmin.controller.ts, src/management/configuration/configuration.route.ts, src/management/configuration/dictionaries/add-property.dialog.controller.ts, src/management/configuration/dictionaries/add-property.dialog.html, src/management/configuration/dictionaries/dictionaries.component.ts, src/management/configuration/dictionaries/dictionaries.controller.ts, src/management/configuration/dictionaries/dictionaries.html, src/management/configuration/dictionaries/dictionary.component.ts, src/management/configuration/dictionaries/dictionary.controller.ts, src/management/configuration/dictionaries/dictionary.html, src/management/configuration/settings.component.ts, src/management/configuration/settings.html, src/management/management.module.ts, src/services/dictionary.service.ts, src/services/role.service.ts
Closes gravitee-io/issues#1400
=> feat(dictionary): Add global dictionary

src/services/message.service.ts
=> fix(message): typo in message url

src/index.scss, src/management/_datatable.scss, src/management/api/_api.scss, src/management/api/apis.html, src/management/application/applications.html
=> feat(apis): improve the api list display

package.json, src/components/dashboard/dashboard-timeframe.controller.ts, src/components/dashboard/dashboard-timeframe.html, src/components/dashboard/dashboard.html, src/components/widget/widget-data-table.html, src/index.scss, src/management/_analytics.scss, src/management/_datatable.scss, src/management/api/analytics/apis.analytics.route.ts, src/management/api/analytics/logs/components/logs-filters.controller.ts, src/management/api/analytics/logs/components/logs-filters.html, src/management/api/analytics/logs/components/logs-timeframe.controller.ts, src/management/api/analytics/logs/components/logs-timeframe.html, src/management/api/analytics/logs/log.component.ts, src/management/api/analytics/logs/log.html, src/management/api/analytics/logs/logs.controller.ts, src/management/api/analytics/logs/logs.html, src/management/api/analytics/overview/analytics.controller.ts, src/management/application/applications.route.ts, src/management/application/details/logs/application-log.component.ts, src/management/application/details/logs/application-log.html, src/management/application/details/logs/application-logs.html, src/management/management.module.ts, yarn.lock
=> feat(logs): improve api logs

src/management/api/portal/general/apiPortal.controller.ts, src/management/api/portal/general/apiPortal.html, src/management/api/portal/general/dialog/apiExport.dialog.html, src/management/api/portal/general/dialog/apiExportDialog.controller.ts, src/portal/index.html, src/services/api.service.ts
Closes gravitee-io/issues#1503
=> feat(api): export API definition for a specific Gravitee.io APIM version

src/management/api/proxy/backend/endpoint/group.controller.ts
=> fix(api): allow apis with no endpoints groups

docs/management-api-logging-configuration.md, src/management/api/analytics/apis.analytics.route.ts, src/management/api/analytics/logs/configure-logging-editor.dialog.controller.ts, src/management/api/analytics/logs/configure-logging-editor.dialog.html, src/management/api/analytics/logs/logging-configuration.controller.ts, src/management/api/analytics/logs/logging-configuration.html, src/management/api/analytics/logs/logs.html, src/management/api/proxy/apiProxy.controller.ts, src/management/api/proxy/general/apiProxyGeneral.html, src/management/management.module.ts
Closes gravitee-io/issues#1482
=> feat(logging): Define a condition to log a request

src/components/documentation/page-sidenav.directive.ts, src/components/documentation/page-sidenav.html
Closes gravitee-io/issues#1531
=> bug(portal): Click on the right menu doesn't scroll

src/management/api/proxy/apiProxy.controller.ts, src/management/api/proxy/general/apiProxyCORS.html
Closes gravitee-io/issues#1524
=> fix(cors): Do not allow to save CORs configuration if cors is disabled

src/management/instances/details/environment/instance-environment.controller.ts, src/management/instances/details/environment/instance-environment.html
=> feat(monitoring): filter envvar

src/components/documentation/_page.scss
Closes gravitee-io/issues#1537
=> feat(doc): Add doc style for http verbs

src/management/api/proxy/apis.proxy.route.ts, src/management/api/proxy/backend/endpoint/endpointConfiguration.controller.ts, src/management/api/proxy/backend/endpoint/endpointConfiguration.html, src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts, src/management/api/proxy/backend/healthcheck/healthcheck-configure.html
Closes gravitee-io/issues#1543
=> fix(health-check): Get endpoint from an endpoint group

src/management/api/analytics/logs/log.html, src/management/api/analytics/overview/analytics.controller.ts, src/management/configuration/portal/portal.component.ts, src/management/configuration/portal/portal.html
Closes gravitee-io/issues#1536
=> feat(analytics): Add Host HTTP header into analytics

src/management/_forms.scss, src/management/api/_api.scss, src/management/api/apis.html, src/management/api/creation/steps/api-creation-step1.html, src/management/api/creation/steps/api-creation-step2.html, src/management/api/creation/steps/api-creation-step3.html, src/management/api/creation/steps/api-creation-step4.html, src/management/api/creation/steps/api-creation.html, src/management/api/portal/documentation/pages/page/apiPage.html, src/management/api/portal/general/apiPortal.controller.ts, src/management/api/portal/general/apiPortal.html, src/management/api/portal/plans/plan/plan-wizard-general.html, src/management/api/portal/plans/plan/plan-wizard-policies.html, src/management/api/portal/plans/plan/plan-wizard-security.html, src/management/api/proxy/backend/endpoint/apiEndpoints.html, src/management/api/proxy/backend/endpoint/group.html, src/management/application/applications.html, src/management/application/create-application.html, src/management/configuration/metadata/metadata.html, src/management/configuration/pages/page/page.html, src/management/configuration/top-apis/top-apis.html, src/management/configuration/views/views.html
=> feat(ui): redesign forms (2nd cleaning)

conf/webpack-dist.conf.js, src/components/documentation/page-swagger.component.ts, src/swagger-oauth2-redirect.html
Closes gravitee-io/issues#1529
=> fix(swagger): Add the oauth2 redirect page for oauth2 authentication

src/components/documentation/_page.scss
=> fix(swagger): css for example is wrong

src/index.scss, src/management/api/apis.html, src/management/application/applications.html, src/portal/api/api-list.html
=> feat(search): add a search button

src/management/api/portal/general/apiPortal.controller.ts
This closes gravitee-io/issues#1603
=> fix: API not refreshed correctly when stopping it

src/management/application/create-application.html, src/management/application/details/general/application-general.html
=> fix(application): min length to 1 and no max length

src/management/_forms.scss, src/management/api/analytics/logs/log.html, src/management/api/analytics/logs/logging-configuration.html, src/management/api/analytics/logs/logs.html, src/management/api/portal/subscriptions/subscription.html, src/management/api/proxy/backend/endpoint/apiEndpoints.html, src/management/api/proxy/backend/endpoint/endpointConfiguration.html, src/management/api/proxy/backend/endpoint/group.html, src/management/api/proxy/backend/failover/apiProxyFailover.html, src/management/api/proxy/backend/healthcheck/healthcheck-configure.html, src/management/api/proxy/backend/healthcheck/healthcheck-visualize.html, src/management/api/proxy/general/apiProxyCORS.html, src/management/api/proxy/general/apiProxyDeployments.html, src/management/application/details/subscriptions/application-subscription.html, src/management/configuration/dictionaries/dictionary.html, src/management/configuration/group/group.html, src/management/configuration/roles/role/role.html, src/management/configuration/roles/role/role.members.html, src/management/configuration/user/user.html, src/management/configuration/views/view/view.html
=> fix(ui): do not hide forms title on resize

src/management/api/design/properties/properties.html, src/management/api/design/resources/resources.html
This closes gravitee-io/issues#1617
=> fix: Delete button of the properties screen is not well displayed

src/management/application/applications.route.ts, src/management/application/details/subscriptions/application-subscriptions.component.ts, src/management/application/details/subscriptions/application-subscriptions.controller.ts, src/management/application/details/subscriptions/application-subscriptions.html
Closes gravitee-io/issues#1607
=> fix(application): Remove parent form

src/management/api/apis.route.ts, src/management/application/applications.route.ts
=> fix(api, app): keep old permissions when switch to a new app/api

src/management/configuration/api-portal-header/api-portal-header.html, src/management/configuration/roles/roles.html, src/management/configuration/top-apis/top-apis.html, src/management/configuration/users/users.html, src/management/configuration/views/views.html
=> fix(ui): fix how action icons are displayed with Chrome

package-lock.json, package.json
Closes gravitee-io/issues#1651
=> fix(swagger): Upgrade the swagger-ui dependency to fix the models issue.

src/components/contextual/_contextual-doc.component.scss, src/components/contextual/contextual-doc.component.html, src/components/documentation/_page.scss, src/components/notificationsettings/notificationsettings.html, src/index.route.ts, src/index.scss, src/management/_submenu.scss, src/management/api/analytics/pathMappings/pathMappings.html, src/management/api/apis.html, src/management/api/design/policies/apiPolicies.html, src/management/api/design/properties/properties.html, src/management/api/design/resources/resources.html, src/management/api/portal/documentation/pages/apiDocumentation.html, src/management/api/portal/plans/list-plans.html, src/management/api/portal/subscriptions/subscriptions.html, src/management/api/portal/userGroupAccess/members/members.html, src/management/application/applications.html, src/management/application/details/members/application-members.html, src/management/configuration/api-portal-header/api-portal-header.html, src/management/configuration/dictionaries/dictionaries.html, src/management/configuration/dictionaries/dictionary.html, src/management/configuration/group/group.html, src/management/configuration/groups/groups.html, src/management/configuration/metadata/metadata.html, src/management/configuration/pages/portalPages.html, src/management/configuration/roles/role/role.members.html, src/management/configuration/top-apis/top-apis.html, src/management/configuration/user/user.html, src/management/configuration/views/views.html
Closes gravitee-io/issues#1648
=> feat: Animation the contextual documentation

src/components/documentation/_page.scss, src/components/documentation/page-sidenav.directive.ts, src/components/documentation/page-sidenav.html, src/components/documentation/page.component.ts, src/components/documentation/page.html, src/portal/api/_api.scss, src/portal/api/documentation/api-page.html, src/portal/api/header/api-header.component.ts, src/portal/api/header/api-header.html
Closes gravitee-io/issues#1619
=> feat: Add animation for the portal api headers

src/components/sidenav/_sidenav.scss, src/components/sidenav/sidenav.html, src/components/sidenav/submenu.html
Closes gravitee-io/issues#1620
=> feat: Add animation for the conf menu

src/management/api/portal/plans/list-plans.controller.ts, src/management/api/portal/plans/list-plans.html
=> fix(plan): access plan management with only read permission

src/components/documentation/page-editormarkdown-viewer.component.ts, src/components/documentation/page-editormarkdown.component.ts
Closes gravitee-io/issues#1671
=> fix(markdown): Allow inline HTML tags

src/management/api/analytics/logs/configure-logging-editor.dialog.controller.ts, src/management/api/analytics/logs/configure-logging-editor.dialog.html, src/management/api/analytics/logs/logging-configuration.html
=> feat(log) remove condition in the configurator

src/management/api/analytics/logs/configure-logging-editor.dialog.controller.ts
This closes gravitee-io/issues#1680
=> fix: Log condition end date is not well managed

src/portal/components/navbar/navbar.component.ts, src/portal/components/navbar/navbar.html
=> feat(navbar): hide login button on login form

src/portal/portal.i18n.ts
=> feat(i18n): add a better language negotiation

src/components/messages/messages.component.ts, src/components/messages/messages.html, src/components/notificationsettings/notificationsettings.component.ts, src/components/notificationsettings/notificationsettings.html, src/entities/notificationConfig.ts, src/services/message.service.ts
=> feat(proxy): add global proxy

src/management/api/portal/general/apiPortal.html
This closes gravitee-io/issues#1666
=> fix: Danger zone is displayed to USER RO

build.json, package.json, src/index.scss, src/management/api/apis.controller.ts, src/management/api/apis.html, src/portal/api/api-list.controller.ts, src/portal/api/api-list.html
This closes gravitee-io/issues#1544
=> feat: Add a loading spinner while searching for APIs

src/components/documentation/page-editormarkdown.component.ts, src/management/configuration/portal/portal.html
=> feat(portal): Allows to persist images to use it on documentation pages

src/management/api/proxy/apiProxy.controller.ts, src/management/api/proxy/backend/endpoint/apiEndpoints.html
=> fix(healthcheck): do no run heathcheck if endpoint HC is disabled

src/management/configuration/roles/role/role.members.component.ts, src/management/configuration/roles/role/role.members.html
=> fix(role): do not freeze when adding or removing a member of a role

src/management/configuration/identity/identity-provider-graviteeio-am.html
Closes gravitee-io/issues#1711
=> fix(identity): Picture was not associated to the correct property

conf/webpack-dist.conf.js
This closes gravitee-io/issues#1720
=> fix: JS error on dist

src/management/api/portal/plans/plan/plan-wizard-security.component.ts
Closes gravitee-io/issues#1724
=> fix(plan): Reinit security definition only for a new plan

src/index.html
This closes gravitee-io/issues#1731
=> fix: Banner of unsupported browser version is not displayed

src/management/api/proxy/apis.proxy.route.ts, src/management/api/proxy/backend/endpoint/apiEndpoints.html, src/management/api/proxy/backend/endpoint/group.controller.ts, src/management/api/proxy/backend/endpoint/group.html, src/management/management.module.ts, src/services/serviceDiscovery.service.ts
and manage service discovery as a plugin
Closes gravitee-io/issues#1701
=> feat(discovery): Add service discovery at the endpoint group level

src/management/api/analytics/pathMappings/pathMappings.html
Closes gravitee-io/issues#1756
=> fix(ui): Use fluid form for path mappings

src/management/configuration/groups/groups.html
=> fix(groups): the add button is floating if the screen is empty

src/management/api/audit/events/apiEvents.html, src/management/api/audit/history/apiHistory.html
Closes gravitee-io/issues#1764
=> fix(user): Use the user's displayname from API's history and events

src/management/configuration/identity/identity-provider.html
Closes gravitee-io/issues#1736
=> fix(identity): Bind to the model from controller

src/management/application/details/subscriptions/application-subscription.component.ts, src/management/application/details/subscriptions/application-subscription.html, src/services/application.service.ts
Closes gravitee-io/issues#1746
=> feat(subscription): An application can close its own subscription

src/management/api/proxy/apiProxy.controller.ts, src/management/api/proxy/backend/endpoint/apiEndpoints.html, src/management/api/proxy/backend/endpoint/endpointConfiguration.html
=> fix(endpoints): be able to change the endpoint weight

src/components/dashboard/dashboard-filter.controller.ts, src/components/logs/logs-filters.controller.ts
This closes gravitee-io/issues#1766
=> feat: Better handling of character escaping on analytics

src/components/dashboard/dashboard.html, src/management/api/analytics/overview/analytics.html, src/management/application/details/analytics/application-analytics.html, src/management/application/details/logs/application-logs.html, src/management/application/details/members/application-members.html, src/management/application/details/subscriptions/application-subscription.html, src/management/application/details/subscriptions/application-subscriptions.html, src/management/platform/dashboard/dashboard.html
This closes gravitee-io/issues#1767
=> feat: Display correctly application title when no type defined

src/management/api/portal/plans/list-plans.controller.ts, src/management/api/portal/plans/list-plans.html, src/services/api.service.ts
Closes gravitee-io/issues#1762
=> feat(plan): A plan can be depreciate to close subscriptions

src/management/api/creation/newApi.controller.ts, src/management/api/creation/newApi.html, src/management/api/creation/steps/api-creation.controller.ts, src/services/api.service.ts
=> feat(swagger): add options on api creation

src/services/notification.service.ts
This closes gravitee-io/issues#1784
=> feat: Display errors notifications correctly

package.json, src/components/documentation/page-editormarkdown-viewer.component.ts, yarn.lock
=> Fix: Better management of select item in the right menu of the doc

src/portal/components/navbar/_navbar.scss
=> fix(modal): navbar is stil reachable even if a dialog is shown

src/portal/api/_api.scss, src/portal/api/api-list.html, src/portal/home/home.html
=> Feat: Preserve the height for the api card in the api list

src/components/sidenav/_sidenav.scss
=> fix: menu display issue

src/management/api/proxy/backend/endpoint/endpointConfiguration.controller.ts
This closes gravitee-io/issues#1776
=> fix: New endpoints are systematically created with ssl configuration

src/components/contextual/_contextual-doc.component.scss
=> fix(contextual-doc): remove z-index to avoid potential overlay issue

src/management/api/design/properties/properties.controller.ts, src/management/api/design/properties/properties.html, src/management/configuration/dictionaries/dictionary.controller.ts, src/management/configuration/dictionaries/dictionary.html
This closes gravitee-io/issues#1670
=> feat: add a 'remove all' button in properties and dictionaries

src/management/api/portal/subscriptions/subscription.component.ts, src/management/api/portal/subscriptions/subscription.html, src/management/api/portal/subscriptions/subscriptions.component.ts, src/management/application/details/subscriptions/application-subscription.component.ts, src/management/application/details/subscriptions/application-subscription.html, src/management/application/details/subscriptions/application-subscriptions.controller.ts, src/services/api.service.ts
Closes gravitee-io/issues#1753
=> feat(souscription): A subscription can be paused and resumed

docs/management-configuration-entry_point.md, src/management/api/creation/steps/api-creation-step2.html, src/management/components/circularPercentage/circularPercentage.component.ts, src/management/components/circularPercentage/circularPercentage.controller.ts, src/management/configuration/configuration.route.ts, src/management/configuration/entrypoint/delete.entrypoint.dialog.controller.ts, src/management/configuration/entrypoint/delete.entrypoint.dialog.html, src/management/configuration/entrypoint/entrypoint.component.ts, src/management/configuration/entrypoint/entrypoint.controller.ts, src/management/configuration/entrypoint/entrypoint.html, src/management/configuration/portal/portal.component.ts, src/management/configuration/portal/portal.html, src/management/configuration/tags/delete.tag.dialog.html, src/management/configuration/tags/tags.controller.ts, src/management/configuration/tags/tags.html, src/management/management.module.ts, src/portal/api/header/api-header.component.ts, src/portal/api/header/api-header.html, src/portal/api/subscribe/api-subscribe.component.ts, src/portal/api/subscribe/api-subscribe.html, src/portal/portal.route.ts, src/services/api.service.ts, src/services/entryPoint.service.ts
This closes gravitee-io/issues#1706
=> feat: display entrypoints by API sharding tags

src/management/configuration/portal/portal.html
This closes gravitee-io/issues#1822
=> feat: Add explanation on configuration of tiles mode display

src/management/api/portal/documentation/metadata/dialog/update.api.metadata.dialog.controller.ts, src/management/configuration/metadata/dialog/save.metadata.dialog.html
=> fix(metadata): unable to create a metadata

src/management/components/messages/messages.component.ts, src/management/components/messages/messages.html, src/management/management.module.ts
=> feat(messages): add multiple recipients

src/management/api/proxy/backend/endpoint/group.controller.ts
This closes gravitee-io/issues#1865
=> fix: Service discovery is not working anymore

src/management/api/portal/plans/list-plans.controller.ts
=> fix(plan) typo when trying to deprecated a plan

build.json, package.json, src/components/documentation/page/page.component.ts, src/components/documentation/page/page.html, src/management/components/documentation/edit-page.html
This closes gravitee-io/issues#1825
=> fix: Add a link to the git repository defined on a documentation page

src/management/api/apis.route.ts, src/management/api/creation/steps/api-creation-step2.component.ts, src/management/api/creation/steps/api-creation-step2.html, src/management/api/creation/steps/api-creation.component.ts, src/management/api/creation/steps/api-creation.controller.ts
It's now possible to configure a tenant and a tags on the endpoint.
fix gravitee-io/issues#1819
=> feat(api.wizard): add advanced mode

src/management/configuration/portal/portal.html, src/management/configuration/views/view/view.controller.ts, src/management/configuration/views/view/view.html, src/management/configuration/views/views.controller.ts, src/management/configuration/views/views.html, src/portal/views/view/_view.scss, src/portal/views/view/view.html, src/portal/views/views.html
closes gravitee-io/issues#1821
=> feat(view): add picture to a portal view

src/components/documentation/page/page.html, src/management/application/details/logs/application-log.component.ts, src/management/application/details/logs/application-log.html
Closes gravitee-io/issues#1710
=> fix(logs): Add request / response body into application's logs

src/management/api/design/policies/apiPolicies.html, src/management/api/design/policies/policies.controller.ts
This closes gravitee-io/issues#1914
=> fix: Avoid to list all policy's schemas

src/management/api/analytics/logs/logging-configuration.controller.ts
Closes gravitee-io/issues#1901
=> fix(logging): Refresh the API after a deploy

src/components/dashboard/dashboard-timeframe.controller.ts, src/components/dashboard/dashboard-timeframe.html, src/components/logs/logs-timeframe.controller.ts, src/components/logs/logs-timeframe.html
=> fix(analytics): change the end date of the timeframe

src/management/configuration/group/group.component.ts, src/management/configuration/groups/groups.component.ts, src/management/configuration/groups/groups.html, src/services/group.service.ts
=> fix(group): apply a default role on a group change the group attributes

src/management/api/analytics/logs/logging-configuration.controller.ts, src/management/api/analytics/logs/logging-configuration.html, src/management/configuration/portal/portal.html
=> fix(logging): add a max duration at the platform level

src/management/api/creation/newApi.controller.ts, src/management/api/creation/newApi.html, src/management/api/creation/steps/api-creation-step2.html, src/management/api/design/policies/apiPolicies.html, src/management/api/design/policies/policies.controller.ts
This closes gravitee-io/issues#1567
=> feat: Create mocks in API imported from swagger/OAI

src/components/contextual/contextual-doc.controller.ts, src/index.scss, src/management/components/notifications/notificationsettings/notificationsettings.component.ts, src/management/configuration/configuration.route.ts, src/management/configuration/group/addMember.dialog.html, src/management/configuration/group/addMemberDialog.controller.ts, src/management/configuration/group/group.component.ts, src/management/configuration/group/group.html, src/management/configuration/group/inviteMember.dialog.html, src/management/configuration/groups/add-group.dialog.html, src/management/configuration/groups/groups.html, src/services/group.service.ts, src/user/registration/confirm/confirm.controller.ts, src/user/registration/confirm/confirm.html, src/user/registration/registration.html, src/user/resetPassword/resetPassword.controller.ts
This closes gravitee-io/issues#1818
=> feat: Invite a user in a group

src/management/api/proxy/backend/endpoint/group.html
This closes gravitee-io/issues#1954
=> fix: Impossible to add a new endpoint group

src/management/api/design/policies/apiPolicies.html, src/management/api/design/policies/policies.controller.ts
=> fix(policies): enable the  button when methods change

src/index.scss, src/management/configuration/group/group.html
This closes gravitee-io/issues#1957
=> Change the disposition of admin section in group configuration

src/management/api/portal/general/dialog/apiExportDialog.controller.ts
=> fix(export): be able to exclude groups from the api export

src/portal/api/header/api-header.html
=> fix(api): headers name are duplicate

build.json, package.json, src/management/instances/instances.controller.ts, src/management/instances/instances.html, src/services/instances.service.ts
This closes gravitee-io/issues#1908
=> feat: Instances management screen not accessible sometimes

src/components/notificationsettings/notificationsettings.html, src/management/api/analytics/apis.analytics.route.html, src/management/api/audit/apis.audit.route.html, src/management/api/design/apis.design.route.html, src/management/api/portal/apis.portal.route.html, src/management/api/proxy/apis.proxy.route.html
=> feat(menu): add a tooltip on the api name

src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts
=> fix(healthcheck): api outdated when configuring the healthcheck

src/management/api/portal/documentation/pages/page/apiPage.controller.ts, src/management/configuration/pages/page/newPage.controller.ts
=> fix(page): import documentation from file

docs/management-api-log.md, src/management/api/analytics/apis.analytics.route.ts, src/management/api/analytics/logs/_logs.scss, src/management/api/analytics/logs/log.html, src/management/api/design/policies/_policy.scss
This closes gravitee-io/issues#1950
=> feat: Improve log detail screen

build.json, package.json, src/components/dashboard/dashboard-timeframe.html, src/management/api/analytics/overview/analytics.controller.ts, src/management/application/details/analytics/application-analytics.controller.ts, src/management/configuration/portal/portal.component.ts
This closes gravitee-io/issues#1951
=> feat: Add an option to get hits by user agent in analytics dashboard

src/management/api/proxy/backend/endpoint/endpointConfiguration.controller.ts, src/management/api/proxy/backend/endpoint/endpointConfiguration.html, src/management/api/proxy/backend/endpoint/group.controller.ts, src/management/api/proxy/backend/endpoint/group.html, src/services/api.service.ts
=> fix(api): Avoid duplicate name for groups and endpoints

src/management/api/proxy/backend/endpoint/endpointConfiguration.html, src/management/api/proxy/backend/endpoint/group.controller.ts, src/management/api/proxy/backend/endpoint/group.html
=> fix(endpoints): resolve endpoints with special characters in their name 

build.json, package.json, src/user/login/login.html
=> fix(login): oauth button color is always grey

src/management/configuration/users/users.html
=> fix(user): add a magnifying glass in the user search

build.json, docs/management-api-documentation.md, docs/management-configuration-create-user.md, docs/management-configuration-portal-pages.md, package.json, src/management/configuration/configuration.route.ts, src/management/configuration/portal/portal.html, src/management/configuration/user/new/new-user.component.ts, src/management/configuration/user/new/new-user.html, src/management/configuration/users/users.component.ts, src/management/configuration/users/users.html, src/management/management.module.ts, src/services/user.service.ts, src/user/registration/confirm/confirm.controller.ts, src/user/resetPassword/resetPassword.controller.ts, src/user/user.controller.ts
This closes gravitee-io/issues#1505
=> feat: User creation from management gui / management API

src/management/api/creation/newApi.controller.ts
This closes gravitee-io/issues#2022
=> fix: Error while importing an API

src/management/api/apis.controller.ts, src/portal/api/api-list.controller.ts
This closes gravitee-io/issues#1937
=> feat: improve the search engine

src/management/api/portal/apis.portal.route.ts, src/management/components/documentation/edit-page.component.ts, src/management/components/documentation/edit-page.html, src/management/configuration/configuration.route.ts
=> feat(documentation): keep the current tab on save

docs/management-configuration-apilogging.md, src/management/_analytics.scss, src/management/api/analytics/logs/_logs.scss, src/management/api/analytics/logs/log.component.ts, src/management/api/analytics/logs/log.html, src/management/api/analytics/logs/logs.controller.ts, src/management/api/analytics/logs/logs.html, src/management/application/details/logs/application-log.component.ts, src/management/application/details/logs/application-log.html, src/management/application/details/logs/application-logs.controller.ts, src/management/application/details/logs/application-logs.html, src/management/configuration/api_logging/api_logging.html
This closes gravitee-io/issues#1948
=> feat: Audit on API user from JWT

src/components/widget/widget.component.ts, src/management/platform/dashboard/dashboard.controller.ts
This closes gravitee-io/issues#1938
=> fix: top failed==top apis when a tenant is selected

docs/management-configuration-analytics.md, src/management/configuration/analytics/analytics.component.ts, src/management/configuration/analytics/analytics.html, src/management/configuration/configuration.route.ts, src/management/configuration/portal/portal.html, src/management/configuration/settings.component.ts, src/management/configuration/settings.html, src/management/management.module.ts, src/services/analytics.service.ts, src/services/api.service.ts, src/services/application.service.ts
move the configuration to the database and group analytics settings in a
single page
fix gravitee-io/issues#1920
=> fix: configurable request timeout for analytics

src/portal/api/_api.scss, src/portal/api/header/api-header.html
=> fix: API description is too large from API header

src/management/management.module.ts, src/services/base64.service.ts, src/services/user.service.ts
=> fix(login): accept UTF8 passwords

build.json, package.json, src/management/api/analytics/logs/logs.controller.ts, src/management/api/analytics/logs/logs.html
This closes gravitee-io/issues#2002
=> feat: Allows to define the number of logs to display per page

src/management/components/documentation/documentation-management.component.ts, src/management/components/documentation/documentation-management.html, src/management/components/documentation/edit-page.component.ts, src/management/components/documentation/edit-page.html, src/services/documentation.service.ts
This closes gravitee-io/issues#2001
=> feat: Add a button to fetch API/portal docs

build.json, package.json, src/components/logs/logs-timeframe.html, src/management/api/analytics/logs/_logs.scss, src/management/api/analytics/logs/logs.controller.ts, src/management/api/analytics/logs/logs.html, src/management/application/details/logs/application-logs.controller.ts, src/management/application/details/logs/application-logs.html, src/services/api.service.ts, src/services/application.service.ts
This closes gravitee-io/issues#2004
=> feat: Allows to export logs in a CSV file

build.json, package.json, src/management/platform/dashboard/dashboard.controller.ts
This closes gravitee-io/issues#2044
=> feat: hits by host in the global dashboard analytics

src/management/management.run.ts, src/portal/components/navbar/navbar.component.ts, src/user/login/login.controller.ts
=> fix(registration): unable to complete registration if ForceLogin

src/components/dashboard/dashboard-timeframe.html, src/management/api/analytics/logs/logs.controller.ts, src/management/api/analytics/logs/logs.html, src/management/application/details/logs/application-logs.controller.ts, src/management/application/details/logs/application-logs.html, src/services/api.service.ts, src/services/application.service.ts
This closes gravitee-io/issues#2003
=> feat: Allows to sort the logs by date, path, status

src/portal/api/_api.scss, src/portal/api/api.html
fix gravitee-io/issues#2077
and improves gravitee.io/issues#2034
=> fix: API metadata must in the same line as the title

docs/management-configuration-client-registration-provider.md, docs/management-configuration-client-registration-providers.md, src/entities/application.ts, src/entities/clientRegistrationProvider.ts, src/entities/oauth.ts, src/index.scss, src/management/application/_applications.scss, src/management/application/applications.html, src/management/application/applications.route.ts, src/management/application/create-application.component.ts, src/management/application/create-application.html, src/management/application/details/general/application-general.controller.ts, src/management/application/details/general/application-general.html, src/management/application/details/header/application-header.html, src/management/configuration/application/registration/client-registration-provider.component.ts, src/management/configuration/application/registration/client-registration-provider.controller.ts, src/management/configuration/application/registration/client-registration-provider.html, src/management/configuration/application/registration/client-registration-providers.component.ts, src/management/configuration/application/registration/client-registration-providers.html, src/management/configuration/configuration.route.ts, src/management/configuration/settings.component.ts, src/management/configuration/settings.html, src/management/management.module.ts, src/portal/api/subscribe/api-subscribe.component.ts, src/services/application.service.ts, src/services/clientRegistrationProvider.service.ts, src/services/user.service.ts
Closes gravitee-io/issues#1580
=> feat(dcr): Add Dynamic Client Registration support

docs/management-api-proxy-response-template.md, docs/management-api-proxy-response-templates.md, src/management/api/audit/history/apiHistory.controller.ts, src/management/api/proxy/apis.proxy.route.html, src/management/api/proxy/apis.proxy.route.ts, src/management/api/proxy/general/response-templates/response-template-type.component.ts, src/management/api/proxy/general/response-templates/response-template-type.html, src/management/api/proxy/general/response-templates/response-template.component.ts, src/management/api/proxy/general/response-templates/response-template.controller.ts, src/management/api/proxy/general/response-templates/response-template.html, src/management/api/proxy/general/response-templates/response-templates.controller.ts, src/management/api/proxy/general/response-templates/response-templates.html, src/management/management.module.ts, src/services/api.service.ts
=> feat(api): Define response templates to override policy response

src/management/configuration/api_logging/api_logging.html, src/services/api.service.ts
closes gravitee-io/issues#2103
=> feat(audit): add API Logging configuration audit logs

src/management/api/analytics/logs/logs.controller.ts
Closes gravitee-io/issues#2150
=> fix(log): Inject constant to get the displayed user attribute

src/management/api/proxy/apis.proxy.route.html
Closes gravitee-io/issues#2162
=> fix(health-check): Response template menu item must not be selected

src/management/api/analytics/logs/_logs.scss, src/management/api/analytics/logs/log.component.ts, src/management/api/analytics/logs/log.html, src/management/application/details/logs/application-log.component.ts, src/management/application/details/logs/application-log.html
Closes gravitee-io/issues#2052
=> feat(log): Add a button to copy the payload of request / response

build.json, package.json, src/components/logs/logs-filters.controller.ts, src/components/logs/logs-filters.html, src/management/api/analytics/logs/log.component.ts, src/management/api/analytics/logs/logs.html, src/management/application/details/logs/application-log.component.ts, src/management/application/details/logs/application-logs.html
This closes gravitee-io/issues#2053
=> feat: Allows to search in logs payloads

src/management/api/portal/apis.portal.route.ts, src/management/configuration/configuration.route.ts, src/portal/portal.route.ts, src/services/documentation.service.ts
This closes gravitee-io/issues#2171
=> fix: Attributes not interpreted anymore on api pages

.gitignore, src/components/healthcheckmetric/healthcheck-metric.component.ts, src/components/healthcheckmetric/healthcheck-metric.html, src/management/api/proxy/backend/healthcheck/healthcheck-visualize.html, src/management/management.module.ts
Creation of :
- a new component to manage healthcheck metric
- a new directive to floor the metric value to the nearest integer
Code refactoring
Fix gravitee-io/issues#2168.
=> fix(): improve healthcheck percentage display

src/components/widget/widget-data-table.html
closes gravitee-io/issues#2204
=> fix(analytics): Redirect to the API / application 's analytics view

src/management/api/apis.controller.ts, src/management/api/apis.html, src/management/api/apis.route.ts, src/management/management.interceptor.ts, src/portal/api/api-list.controller.ts, src/portal/api/api-list.html, src/portal/portal.route.ts, src/services/api.service.ts, src/services/portal.service.ts
=> fix(search): automatic search dealy is too short

src/entities/clientRegistrationProvider.ts, src/management/application/create-application.html, src/management/configuration/application/registration/client-registration-provider.controller.ts, src/management/configuration/application/registration/client-registration-provider.html, src/services/clientRegistrationProvider.service.ts
Closes gravitee-io/issues#2207
=> feat(dcr): Support multiple initial access token providers

src/management/api/proxy/general/response-templates/response-template.controller.ts
=> feat(rbac): Add new response template keys
