gravitee-io/gravitee-management-webui

.gitignore
src/management/api/proxy/backend/endpoint/apiEndpoints.html

fix(): add tooltips to health-check icons

---

.gitignore
src/management/api/analytics/logs/logs.controller.ts
src/management/api/analytics/logs/logs.html

fix(): Export CSV works now for Firefox

---

src/entities/identityProvider.ts
src/management/configuration/identity/identity-provider.controller.ts
src/management/configuration/identity/identity-provider.html
src/services/identityProvider.service.ts

refactoring from 1.20.16 due to new idp management
fix gravitee-io/issues#2124

feat(idp): oauth idp could authorize users without email

---

src/management/application/applications.route.ts

feat(application): allow to change application groups

---

src/management/api/apiAdmin.controller.ts
src/management/api/apiAdmin.html
src/management/api/apis.controller.ts
src/management/api/apis.html
src/management/api/creation/steps/api-creation-step5.html
src/management/api/creation/steps/api-creation.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/apiPortal.html
src/management/api/portal/general/dialog/requestForChanges.controller.ts
src/management/api/portal/general/dialog/requestForChanges.dialog.html
src/management/api/review/review.dialog.html
src/management/api/review/reviewDialog.controller.ts
src/management/configuration/portal/portal.html
src/management/configuration/settings.component.ts
src/management/configuration/settings.html
src/management/management.module.ts
src/management/tasks/tasks.component.ts
src/management/tasks/tasks.html
src/portal/api/api-list.controller.ts
src/portal/portal.route.ts
src/services/api.service.ts

This closes gravitee-io/issues#1996

feat: lifecycle API and review workflow

---

src/management/components/circularPercentage/circularPercentage.controller.ts

fix(metrics): rounded the score

---

src/management/configuration/portal/portal.component.ts
src/management/configuration/portal/portal.html

fix(settings): reset settings changes when leaving without saving

---

src/management/configuration/groups/groups.component.ts
src/services/group.service.ts

fix(groups): checkboxes are not taken into account

---

src/components/documentation/page/page-swagger.component.ts
src/management/components/documentation/edit-page.html

This closes gravitee-io/issues#2278

feat: add an option to enable the swagger try out in anonymous mode

---

build.json
package.json
src/components/chart/chart.directive.ts
src/components/dashboard/dashboard-timeframe.controller.ts
src/components/widget/widget-chart-map.component.ts
src/components/widget/widget-chart-map.html
src/components/widget/widget.html
src/management/api/analytics/apis.analytics.route.ts
src/management/api/analytics/overview/analytics.controller.ts
src/management/configuration/analytics/analytics.component.ts
src/management/configuration/analytics/analytics.html
src/management/configuration/portal/portal.html
src/management/management.module.ts
src/management/management.route.ts
src/management/platform/dashboard/dashboard.controller.ts
src/management/platform/dashboard/dashboard.html
yarn.lock

This closes gravitee-io/issues#1997

feat: Multi analytics dashboards

---

src/management/components/documentation/documentation-management.html

fix(pages): remove access to update a page if not authorized

---

src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts

fix(): the request in the healthcheck summary takes now 'From root path' into account

---

src/management/api/portal/general/dialog/apiExport.dialog.html

fix(export): make api export compatible with 1.20

---

src/index.scss
src/management/_forms.scss
src/management/components/documentation/documentation-management.component.ts
src/management/components/documentation/documentation-management.html
src/management/components/notifications/notificationsettings/notificationsettings.component.ts
src/management/components/notifications/notificationsettings/notificationsettings.html
src/management/configuration/api-portal-header/api-portal-header.component.ts
src/management/configuration/api-portal-header/api-portal-header.html
src/management/configuration/application/registration/client-registration-providers.html
src/management/configuration/dictionaries/dictionaries.controller.ts
src/management/configuration/dictionaries/dictionaries.html
src/management/configuration/group/group.html
src/management/configuration/groups/groups.component.ts
src/management/configuration/groups/groups.html
src/management/configuration/identity/identity-providers.component.ts
src/management/configuration/identity/identity-providers.html
src/management/configuration/metadata/metadata.controller.ts
src/management/configuration/metadata/metadata.html
src/management/configuration/roles/role/role.members.component.ts
src/management/configuration/roles/role/role.members.html
src/management/configuration/tags/tags.controller.ts
src/management/configuration/tags/tags.html
src/management/configuration/top-apis/top-apis.controller.ts
src/management/configuration/top-apis/top-apis.html
src/management/configuration/user/user.html
src/management/configuration/user/userdetail.component.ts
src/management/configuration/users/users.component.ts
src/management/configuration/users/users.html
src/management/configuration/views/views.controller.ts
src/management/configuration/views/views.html

fix(management): the + button overlaps multiple forms

---

src/management/api/portal/plans/list-plans.html

fix(plan): plan card must adapt themselves on screen sizes

---

src/components/widget/widget-data-table.component.ts
src/components/widget/widget-data-table.html
src/management/api/analytics/logs/logs.html
src/management/api/apis.html
src/management/api/portal/subscriptions/subscriptions.html
src/management/application/applications.html
src/management/application/details/logs/application-logs.html
src/management/application/details/subscriptions/application-subscriptions.html
src/management/components/documentation/documentation-management.component.ts
src/management/components/documentation/documentation-management.html
src/management/configuration/dictionaries/dictionaries.controller.ts
src/management/configuration/dictionaries/dictionaries.html
src/management/configuration/groups/groups.component.ts
src/management/configuration/groups/groups.html
src/management/configuration/identity/identity-providers.component.ts
src/management/configuration/identity/identity-providers.html
src/management/configuration/roles/roles.component.ts
src/management/configuration/roles/roles.html
src/management/configuration/tags/tags.html
src/management/configuration/users/users.component.ts
src/management/configuration/users/users.html
src/management/configuration/views/views.controller.ts
src/management/configuration/views/views.html

fix(table): open table row in a new tab

---

src/management/api/apiAdmin.html
src/management/api/portal/apis.portal.route.ts
src/management/api/portal/plans/list-plans.html
src/management/api/portal/plans/plan/edit-plan.component.ts
src/management/api/portal/plans/plan/edit-plan.controller.ts
src/management/api/portal/plans/plan/plan-wizard-general.html
src/portal/api/header/api-header.html
src/portal/api/subscribe/api-subscribe.component.ts
src/services/api.service.ts

Closes gravitee-io/issues#2219

feat(plan): Manage plan deployment using sharding tags

---

src/management/components/documentation/edit-page.html

fix(page): use the fetcher logo on the 'edit on xxx' link

---

src/components/documentation/page/page-editormarkdown.html
src/components/documentation/page/page.html
src/index.scss
src/management/api/analytics/logs/logging-configuration.html
src/management/components/documentation/edit-page.html
src/management/components/documentation/import-pages.html
src/support/ticket.html

fix(): same red on all warning messages

---

conf/browsersync.conf.js
constants.json
constants.tpl.json

Closes gravitee-io/issues#2287

feat(env): call API with DEFAULT env

---

src/management/api/analytics/apis.analytics.route.ts
src/management/api/analytics/logs/log.component.ts
src/management/api/analytics/logs/logs.controller.ts
src/management/api/analytics/logs/logs.html
src/management/application/applications.route.ts
src/management/application/details/logs/application-log.component.ts
src/management/application/details/logs/application-logs.controller.ts
src/management/application/details/logs/application-logs.html

fix: keep the pagination configuration

---

src/portal/i18n/nl-BE.json
src/portal/i18n/nl.json

Closes gravitee-io/issues#2334

fix minor translation errors

---

conf/webpack-dist.conf.js
src/components/chart/chart.directive.ts
src/components/widget/widget-chart-map.component.ts
src/management/management.module.ts

fix: Highchart module is not well loaded on dist

---

src/components/dashboard/dashboard-timeframe.controller.ts
src/components/dashboard/dashboard.component.ts
src/components/widget/widget.component.ts
src/management/api/analytics/apis.analytics.route.ts
src/management/api/analytics/overview/analytics.controller.ts
src/management/api/apiAdmin.html
src/management/management.route.ts
src/management/platform/dashboard/dashboard.controller.ts
src/management/platform/dashboard/dashboard.html

fix: Filters does not work properly on all dashboards

---

src/entities/identityProvider.ts
src/management/configuration/identity/identity-provider.controller.ts

Closes gravitee-io/issues#2170

feat(identity): Provide default (common) values for user-mapping

---

src/entities/clientRegistrationProvider.ts
src/management/application/details/general/application-general.controller.ts
src/management/application/details/general/application-general.html
src/management/configuration/application/registration/client-registration-provider.controller.ts
src/management/configuration/application/registration/client-registration-provider.html
src/management/configuration/settings.html
src/services/application.service.ts
src/services/clientRegistrationProvider.service.ts

Closes gravitee-io/issues#2350

feat(application): Add renew client_secret support

---

src/portal/views/_views.scss
src/portal/views/views.html

fix(): display view card like api card

---

src/portal/api/rating/apiRating.controller.ts

fix(): reload controller state to update rating title

---

src/portal/components/starRating/_star.rating.scss

fix(): add a min-width for No-Rating link

---

src/management/api/analytics/pathMappings/pathMappings.controller.ts

fix(): call the right resource to get api swagger pages

---

src/management/api/apis.controller.ts

fix: API search is not working as expected

---

src/management/application/details/subscriptions/application-subscriptions.html

fix: Button of subscription should not be displayed is there is subs

---

src/management/api/portal/general/apiPortal.controller.ts
src/management/components/circularPercentage/circularPercentage.controller.ts
src/management/components/circularPercentage/circularPercentage.html

fix(quality): refresh metrics on save

---

src/management/api/analytics/overview/analytics.controller.ts
src/management/api/analytics/overview/analytics.html
src/management/platform/dashboard/dashboard.controller.ts
src/management/platform/dashboard/dashboard.html

Minor rework on geo dashboard

---

src/management/api/portal/plans/plan/plan-wizard-security.html

fix: Description of additional selection rule is not well readable

---

src/management/api/proxy/apis.proxy.route.ts
src/management/api/proxy/backend/healthcheck/healthcheck-visualize.html
src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts

closes gravitee-io/issues#2378

feat(healthcheck): adding a time filter in the healthcheck screen

---

src/management/configuration/top-apis/top-apis.controller.ts

fix(top-api): management screen is broken

---

src/components/documentation/page/page-editormarkdown-viewer.component.ts

fix(pages): Bold titles are not rendered

---

src/management/api/proxy/apiProxy.controller.ts

Closes gravitee-io/issues#2435

fix(cors): Add missing OPTIONS HTTP method

---

src/management/api/proxy/backend/healthcheck/_healthcheck.scss
src/management/api/proxy/backend/healthcheck/healthcheck-configure.html

fix(healthcheck): improve summary rendering

---

src/index.route.ts
src/management/api/apis.controller.ts
src/management/management.interceptor.ts
src/management/management.run.ts
src/services/router.service.ts
src/services/user.service.ts
src/user/login/login.controller.ts

fix: redirect user to wished url after login

---

src/management/api/portal/apis.portal.route.ts
src/management/api/portal/subscriptions/subscription.component.ts
src/management/api/portal/subscriptions/subscription.create.dialog.controller.ts
src/management/api/portal/subscriptions/subscription.html
src/management/api/portal/subscriptions/subscriptions.component.ts
src/management/api/portal/subscriptions/subscriptions.html
src/management/application/applications.route.ts
src/management/application/details/subscriptions/application-subscription.component.ts
src/management/application/details/subscriptions/application-subscription.html
src/management/application/details/subscriptions/application-subscriptions.controller.ts
src/management/application/details/subscriptions/application-subscriptions.html

fix(subscriptions): keep filter & pagination during navigation

---

src/management/application/details/subscriptions/application-subscription.html

feat(subscriptions): allow apps to close all subscriptions

---

src/management/components/documentation/documentation-management.component.ts
src/management/components/documentation/documentation-management.html
src/management/components/documentation/import-pages.component.ts
src/management/components/documentation/import-pages.html
src/portal/portal.route.ts

feat(pages) Disable fetchAll when its in progress

---

build.json
package.json
src/components/dashboard/dashboard-timeframe.controller.ts
src/components/logs/logs-filters.controller.ts

fix: Filter on hits should be based on "endpoint" field

---

src/management/api/analytics/logs/logs.controller.ts
src/management/api/analytics/logs/logs.html
src/management/api/portal/subscriptions/subscriptions.component.ts
src/management/api/portal/subscriptions/subscriptions.html
src/services/api.service.ts

feat: Allows to export subscriptions to CSV

---

conf/browsersync.conf.js
constants.json
constants.tpl.json

Change management API URL
Closes gravitee-io/issues#2288

feat(env): splits management and portal APIs.

---

src/components/chart/chart.directive.ts
src/management/api/portal/subscriptions/subscriptions.component.ts
src/management/api/portal/subscriptions/subscriptions.html

feat: Add a sparkline graph on subscriptions list

---

src/components/widget/widget-data-table.component.ts
src/components/widget/widget-data-table.html
src/components/widget/widget.component.ts
src/management/application/details/analytics/application-analytics.controller.ts
src/management/platform/dashboard/dashboard.controller.ts

feat: Display top failed calls as percentage

---

src/management/api/portal/apis.portal.route.ts
src/management/api/portal/subscriptions/subscription.component.ts
src/management/api/portal/subscriptions/subscriptions.component.ts
src/management/api/portal/subscriptions/subscriptions.html
src/management/application/applications.route.ts
src/management/application/details/subscriptions/application-subscription.component.ts
src/management/application/details/subscriptions/application-subscriptions.controller.ts
src/management/application/details/subscriptions/application-subscriptions.html

feat: Allows to search subscriptions by api key

---

src/management/api/analytics/logs/log.html

feat: Display client id and not token on logs for JWT/OAuth2 plans

---

src/management/configuration/views/view/view.controller.ts
src/management/configuration/views/view/view.html

fix: Impossible to detach an API while creating a view

---

src/management/components/notifications/notificationsettings/addnotificationsettings.dialog.html
src/management/components/notifications/notificationsettings/notificationsettings.component.ts

fix: When deleting a notification, list is not refreshed

---

src/management/api/analytics/logs/logging-configuration.controller.ts

fix: Logging configuration filter display closed plans

---

src/management/configuration/tenants/tenants.html

fix: The copy to clipboard button of tenant is not correctly centered

---

src/management/api/portal/subscriptions/subscription.component.ts
src/management/api/portal/subscriptions/subscription.html

fix: An expired API key should not appear as valid

---

src/management/api/portal/subscriptions/subscriptions.html

fix: Pagination size is not working anymore on subscriptions list

---

src/management/api/portal/subscriptions/subscription.component.ts

fix: Renew subscription also renew expired (not revoked) api keys

---

src/components/logs/logs-filters.controller.ts
src/components/logs/logs-filters.html

feat: Allows to filter logs by endpoint

---

src/management/api/portal/subscriptions/subscription.component.ts
src/management/api/portal/subscriptions/subscription.html

fix: Avoid some actions on expired api keys

---

src/management/api/portal/userGroupAccess/members/_members.scss
src/management/api/portal/userGroupAccess/members/addMember.dialog.html
src/management/api/portal/userGroupAccess/transferOwnership/transferOwnership.html
src/management/application/details/members/addMember.dialog.html
src/management/application/details/members/application-members.html
src/management/configuration/group/addMember.dialog.html

feat(user): add an option to retreive users email in search dialog boxes

---

src/management/configuration/dictionaries/dictionary.html

fix(dictionary): readonly users must not see the provider informations

---

conf/browsersync.conf.js
constants.json
constants.tpl.json
pom.xml

Closes gravitee-io/issues#2288

feat(env): modification of the base url of the management API

---

pom.xml

Closes gravitee-io/issues#2585

feat(v3): add trailing slash

---

src/management/configuration/user/userdetail.component.ts

fix(user): hide archived apps

---

build.json
package.json
src/components/widget/widget-data-stats.component.ts
src/components/widget/widget-data-stats.html

fix: Requests per second is not displayed anymore

---

src/management/api/analytics/pathMappings/pathMappings.controller.ts

fix: verify regex before saving the api

---

src/management/api/proxy/general/apiProxyDeployments.html

fix(deployment): Forms buttons have the wrong color

---

src/management/api/proxy/backend/failover/apiProxyFailover.html

fix(failover): improve the configuration message

---

src/management/configuration/group/group.component.ts
src/management/configuration/group/group.html

fix(groups): a group admin should be able to add members

---

src/management/configuration/dictionaries/dictionary.controller.ts

feat(dictionary): add a confirm dialog on deletion

---

src/services/documentation.service.ts

fix(documentation): increase the fetch timeout

---

src/management/management.interceptor.ts

fix(errors): use the SilentCall parameter in http errors

---

src/management/api/apis.controller.ts

Closes gravitee-io/issues#2763

fix: Sometimes the api list is not refreshing well

---

src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/apiPortal.html
src/management/api/portal/general/dialog/apiDuplicate.dialog.html
src/management/api/portal/general/dialog/apiDuplicateDialog.controller.ts
src/management/management.module.ts
src/services/api.service.ts

feat: Duplicate an api to create a new version of the API

---

build.json
package.json
src/management/api/portal/documentation/metadata/apiMetadata.controller.ts

Closes gravitee-io/issues#2703

fix: Delete button is not displayed on metadata sometimes

---

src/management/api/creation/steps/api-creation-step1.html
src/management/application/create-application.html
src/management/application/details/general/application-general.html

feat(api/app): allow names with 512 char

---

src/management/configuration/analytics/dashboard/dashboard.components.ts
src/management/configuration/analytics/dashboard/dashboard.html
src/management/configuration/analytics/dashboard/query-filter-information.dialog.controller.ts
src/management/management.module.ts

fix: Minor changes in multi analytics dashboard

---

src/management/configuration/users/users.html

fix(users): the trash icon disappears when horizontal scrollbar appears

---

src/management/management.interceptor.ts
src/services/user.service.ts

fix(login): redirect to home when the jwt token expire

---

src/management/api/apiAdmin.controller.ts
src/management/api/apiAdmin.html
src/management/api/apis.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/apiPortal.html
src/management/api/portal/plans/list-plans.component.ts
src/management/api/portal/plans/list-plans.controller.ts
src/management/api/portal/plans/list-plans.html

feat: Lifecycle - allows to deprecate an API

---

src/management/platform/dashboard/dashboard.controller.ts
src/management/platform/dashboard/dashboard.html

fix: Only call events API on first dashboard

---

src/management/api/portal/apis.portal.route.ts

fix: Not able to manage groups for an API

---

src/management/application/applications.route.ts
src/portal/components/navbar/navbar.component.ts
src/portal/components/navbar/navbar.html

If user does not have a read permission for management-application or portal-application
Closes gravitee-io/issues#2565

fix(application): Do not show the menu applications menu item

---

src/portal/i18n/cs.json
src/portal/portal.i18n.ts

Closes gravitee-io/issues#1853

Added Czech I18N

---

src/management/application/details/general/application-general.html
src/management/application/details/header/application-header.component.ts

fix(application): Archived applications must be in readonly mode

---

src/management/api/apiAdmin.controller.ts
src/management/api/apiAdmin.html
src/management/api/review/reviewDialog.controller.ts

fix: Cannot accept/reject review cause the popup is not displayed

---

src/management/components/documentation/edit-page.html

fix(page): edit a page by importing a file

---

src/management/api/analytics/logs/log.component.ts
src/management/api/analytics/logs/log.html

fix(logs): display multiple headers with the same name

---

src/management/configuration/dictionaries/dictionary.controller.ts
src/management/configuration/dictionaries/dictionary.html

Closes gravitee-io/issues#2846

fix(dictionary): Setup pagination for dictionary's properties

---

src/management/api/portal/userGroupAccess/members/addMember.dialog.html
src/management/api/portal/userGroupAccess/members/members.html
src/management/application/details/members/addMember.dialog.html
src/management/application/details/members/application-members.html
src/management/configuration/group/addMember.dialog.html
src/management/configuration/roles/role/add.user.dialog.html
src/management/configuration/user/user.html
src/management/configuration/users/users.html
src/portal/components/navbar/navbar.html

Closes gravitee-io/issues#2898

feat: use default avatar when image not load

---

src/management/api/proxy/backend/endpoint/apiEndpoints.html

fix(api): add controls on api creation and update

---

src/management/configuration/api-portal-header/api-portal-header.component.ts
src/management/configuration/application/registration/client-registration-providers.component.ts
src/management/configuration/identity/identity-providers.component.ts

fix(settings): saved settings modifications in the current Constants obj

---

src/management/management.interceptor.ts

Closes gravitee-io/issues#2957

fix: Unable to reset user password from link

---

src/management/components/documentation/edit-page.component.ts
src/management/components/documentation/edit-page.html

Closes gravitee-io/issues#3039

feat(portal): add the possibility to choose openapi documentation viewer

---

src/management/api/analytics/logs/configure-logging-editor.dialog.controller.ts

fix(logging.editor): generate a more tolerant condition for tables

---

src/management/components/documentation/edit-page.html

fix: Configure openAPI viewer for Swagger pages only

---

src/portal/api/_api.scss
src/portal/api/header/api-header.html

fix(api-header): tags and views overflows under the sticky navbar

---

src/components/metadata/metadata.validator.directive.ts
src/management/api/portal/documentation/metadata/dialog/save.api.metadata.dialog.html

closes gravitee-io/issues#3049

feat(metadata): add EL support for the "email-support" API metadata

---

src/management/api/proxy/apiProxy.controller.ts
src/management/api/proxy/general/apiProxyCORS.html
src/services/api.service.ts

fix(cors): add a warning when allow all origin

---

src/components/dashboard/dashboard-filter.html
src/management/api/creation/steps/api-creation-step3.html
src/management/api/portal/general/apiPortal.html
src/management/api/portal/plans/plan/plan-wizard-general.html
src/management/api/proxy/general/apiProxyCORS.html
src/management/application/create-application.html
src/management/application/details/general/application-general.html
src/management/configuration/application/registration/client-registration-provider.html
src/management/configuration/identity/identity-provider-graviteeio-am.html
src/management/configuration/identity/identity-provider-oidc.html

feat(chips): create chip when the user leave the input

---

src/components/widget/pie/widget-chart-pie-configuration.component.ts

Closes gravitee-io/issues#3089

fix: Cannot remove an item on the widget status (pie)

---

src/components/logs/logs-filters.controller.ts

fix(logs): escape reserved words during research

---

src/management/api/analytics/overview/analytics.controller.ts
src/management/application/details/analytics/application-analytics.controller.ts
src/management/platform/dashboard/dashboard.controller.ts

fix(analytics): be more specific between analytics and latency

---

src/management/api/proxy/apiProxy.controller.ts
src/management/api/proxy/general/apiProxyCORS.html
src/management/components/documentation/edit-page.html

fix(cors): add more help on the CORS configuration

---

src/management/management.interceptor.ts

feat(maintenance): add a maintenance mode for the ui and api

---

src/management/api/portal/subscriptions/subscription.change.end.date.dialog.controller.ts
src/management/api/portal/subscriptions/subscription.change.end.date.dialog.html
src/management/api/portal/subscriptions/subscription.component.ts
src/management/api/portal/subscriptions/subscription.html
src/management/management.module.ts
src/services/api.service.ts

fix(subscription): update subscription ending date

---

src/management/api/portal/subscriptions/apikey.expiration.dialog.controller.ts
src/management/api/portal/subscriptions/apikey.expiration.dialog.html

fix(apikey): expire date cannot ended after subscription

---

src/management/components/alerts/alert/notifications/alert-notification.html
src/management/components/alerts/alert/notifications/alert-notifications.ts

Closes gravitee-io/issues#3162

fix(alert): Form can be updated as soon as a notification is removed

---

src/services/dashboard.service.ts

Closes gravitee-io/issues#3121

feat(analytics): Add the remote-address field as part of the widgets

---

src/management/management.run.ts
src/user/login/login.controller.ts

Closes gravitee-io/issues#2957

fix: Unable to reset user password from link with force login setting

---

conf/browsersync.conf.js
constants.json
constants.tpl.json
pom.xml

Closes gravitee-io/issues#3182

feat(multi-env): add organization feature

---

src/management/configuration/users/users.html

Closes gravitee-io/issues#2425

feat(user): Add a PO badge to user

---

src/portal/api/_api.scss
src/portal/api/header/api-header.component.ts
src/portal/api/header/api-header.html
src/portal/i18n/en.json
src/portal/i18n/fr.json

closes gravitee-io/issues#3239

feat(ui): associate sharding tags - entry points in API Portal Header

---

docs/management-configuration-portal-theme.md
pom.xml
src/components/image/_image.scss
src/components/image/image.directive.ts
src/components/image/image.html
src/entities/theme.ts
src/index.scss
src/management/configuration/configuration.route.ts
src/management/configuration/portal/portal.html
src/management/configuration/settings.component.ts
src/management/configuration/settings.html
src/management/configuration/theme/_theme.scss
src/management/configuration/theme/theme.component.ts
src/management/configuration/theme/theme.controller.ts
src/management/configuration/theme/theme.html
src/management/management.module.ts
src/services/theme.service.ts

feat: add customization of portal

---

src/portal/api/header/api-header.component.ts
src/portal/api/header/api-header.html

fix(api): add missing entry points API header

---

src/components/widget/_widget.scss
src/components/widget/stats/widget-data-stats.html
src/components/widget/table/widget-data-table.html
src/components/widget/widget.html

Closes gravitee-io/issues#3263

fix: Paging functionality of widgets in the dashboards not working

---

src/components/logs/logs-filters.html
src/management/management.module.ts
src/management/management.route.ts
src/management/platform/dashboard/dashboard.controller.ts
src/management/platform/dashboard/dashboard.html
src/management/platform/logs/platform-log.component.ts
src/management/platform/logs/platform-log.html
src/management/platform/logs/platform-logs.component.ts
src/management/platform/logs/platform-logs.controller.ts
src/management/platform/logs/platform-logs.html
src/services/analytics.service.ts

Closes gravitee-io/issues#3233

feat(logs): Provide a way to consult API logs from platform dashboard

---

src/management/api/portal/documentation/metadata/apiMetadata.html
src/management/configuration/metadata/metadata.html

Closes gravitee-io/issues#3266

fix: Metadata cannot be deleted when value is too long

---

src/management/configuration/views/view/view.controller.ts

fix(view): be able to only update view visibility

---

docs/management-configuration-portal-theme.md
src/management/configuration/portal/portal.html
src/management/configuration/theme/_theme.scss
src/management/configuration/theme/theme.controller.ts
src/management/configuration/theme/theme.html
src/management/management.module.ts

fix(theme): resolve communication mechanism with iframe

---

src/management/api/portal/plans/plan/edit-plan.controller.ts

Closes gravitee-io/issues#3280

fix: Allows to define all policies at the plan's level

---

src/management/components/documentation/edit-page.html

Closes gravitee-io/issues#3277

feat(swagger): Swagger server can be based on API entrypoints

---

src/portal/api/_api.scss
src/portal/api/header/api-header.html

fix(api): API Entry Points portal headers should not be truncated

---

src/management/api/portal/plans/plan/edit-plan.controller.ts
src/management/api/portal/plans/plan/plan-wizard-general.html
src/management/components/documentation/edit-page.component.ts
src/management/components/documentation/edit-page.html
src/services/api.service.ts

Closes gravitee-io/issues#3281

fix: Make clearer the group's selection on a plan or a page

---

src/management/api/portal/general/dialog/apiExportDialog.controller.ts

fix(api): export API metadata

---

src/management/configuration/dictionaries/dictionary.controller.ts
src/management/configuration/dictionaries/dictionary.html

Closes gravitee-io/issues#3296

feat(dictionary): Provide support HTTP headers

---

src/management/components/alerts/alert/alert.html
src/management/components/alerts/alert/history/alert-history.component.ts
src/management/components/alerts/alert/history/alert-history.html
src/management/components/alerts/alert/notifications/alert-notifications.html
src/management/components/alerts/alerts.html
src/management/management.module.ts
src/services/alert.service.ts

Closes gravitee-io/issues#3185

feat(alert): Add alert history

---

src/components/dashboard/dashboard-filter.controller.ts
src/components/logs/logs-filters.controller.ts

fix(analytics): be able to filter on unknown app

---

src/components/logs/logs-filters.controller.ts

Closes gravitee-io/issues#3358

fix(log): Add more options to filter on response-time

---

src/management/configuration/portal/portal.html

Closes gravitee-io/issues#3109

feat(portal) : add management link in portal usermenu

---

src/components/logs/logs-filters.controller.ts

Closes gravitee-io/issues#3349

fix(logs): Manage unknown API and allow to filter by unknown API|App

---

src/management/api/proxy/apis.proxy.route.ts
src/management/api/proxy/general/response-templates/response-template-type.html
src/management/api/proxy/general/response-templates/response-templates.html

Closes gravitee-io/issues#3331

fix(response_template): Template can be viewable with read permission

---

src/components/dashboard/dashboard-filter.controller.ts

Closes gravitee-io/issues#3369

fix(analytics): USe the right syntax for ES query string

---

src/management/components/documentation/documentation-management.component.ts
src/management/components/documentation/documentation-management.html

fix(documentation): be able to navigate inside a subfolder

---

src/entities/alert.ts
src/entities/alerts/api.metrics.ts
src/entities/alerts/healthcheck.metrics.ts
src/entities/alerts/node.metrics.ts
src/entities/alerts/rule.metrics.ts
src/management/components/alerts/alert/alert.component.ts
src/management/components/alerts/alert/alert.html
src/management/components/alerts/alert/triggers/projections/trigger-projection.component.ts
src/management/components/alerts/alert/triggers/projections/trigger-projection.html
src/management/components/alerts/alert/triggers/projections/trigger-projections.component.ts
src/management/components/alerts/alert/triggers/projections/trigger-projections.html
src/management/components/alerts/alert/triggers/trigger-metrics-aggregation.html
src/management/components/alerts/alert/triggers/trigger-metrics-rate.html
src/management/management.module.ts
src/services/alert.service.ts

Closes gravitee-io/issues#3335

feat(alert): Alert for all APIs can be setup at the platform level

---

build.json
package-lock.json
package.json
src/user/login/login.controller.ts
src/user/login/login.html

fix(portal): enable LogIn button on first load

---

src/management/api/portal/documentation/metadata/apiMetadata.controller.ts
src/management/api/portal/documentation/metadata/apiMetadata.html
src/management/api/portal/subscriptions/subscriptions.component.ts
src/management/api/portal/subscriptions/subscriptions.html

Closes gravitee-io/issues#3081

fix: plus button override clickable elements

---

src/portal/api/header/api-header.component.ts
src/portal/api/header/api-header.html

Closes gravitee-io/issues#3404

fix: Entrypoints are incorrect in case of virtual hosting configuration

---

src/components/dashboard/dashboard-filter.controller.ts

fix: Unable to filter analytics on paths

---

src/management/configuration/views/view/view.html

Closes gravitee-io/issues#3178

feat(portal): display Views picture

---

src/components/image/image.html
src/management/configuration/theme/theme.controller.ts
src/management/configuration/theme/theme.html

feat: add homepage options in theme

---

src/components/navbar/navbar.component.ts
src/components/navbar/navbar.html
src/entities/user.ts
src/index.route.ts
src/management/api/header/api-header.html
src/management/api/proxy/apiProxy.controller.ts
src/management/configuration/application/registration/client-registration-providers.component.ts
src/management/configuration/tags/tags.controller.ts
src/management/management.interceptor.ts
src/management/management.module.ts
src/management/management.run.ts
src/services/user.service.ts
src/user/confirmProfile/confirmProfile.controller.ts
src/user/confirmProfile/confirmProfile.html

feat: Allow users to subscribe to newsletters

---

src/index.route.ts
src/management/api/apis.controller.ts
src/management/api/apis.html
src/management/api/apis.route.ts
src/management/application/applications.route.ts
src/management/configuration/portal/portal.html
src/management/management.run.ts

Closes gravitee-io/issues#3439

feat(portal): remove dev mode

---

src/management/api/proxy/general/response-templates/response-template.controller.ts

closes gravitee-io/issues#3513

feat(policyChain): add PLAN_UNRESOLVABLE policy chain error key

---

src/entities/alerts/rule.metrics.ts
src/management/components/alerts/alert/alert.html

fix(alert): update metrics when changing a rule

---

src/management/api/proxy/backend/endpoint/httpConfiguration.html

Closes gravitee-io/issues#2634

feat(gateway): remove encodeURI

---

src/components/navbar/navbar.html

fix: Add a link on the logo to go to home

---

package.json

chore: upgrade node-sass to 4.13.1

---

src/services/user.service.ts
src/user/confirmProfile/confirmProfile.controller.ts
src/user/confirmProfile/confirmProfile.html

fix: Allows to define an email on a first login with a inmemory user

---

src/management/configuration/user/_user.scss
src/management/configuration/user/user.html
src/management/configuration/user/userdetail.component.ts

fix(management): hack to prevent md-select to active ng-change on init

---

package.json

Closes gravitee-io/issues#3625

chore: Upgrade swagger-ui dependency

---

src/management/api/proxy/general/apiProxyEntrypoints.html

fix: Allows to override virtual host with entrypoints

---

build.json
package-lock.json
package.json
src/components/dashboard/dashboard-filter.controller.ts
src/components/dashboard/dashboard-filter.html
src/components/widget/line/widget-chart-line.component.ts
src/components/widget/table/widget-data-table.component.ts
src/components/widget/widget.component.ts
src/services/analytics.service.ts

fix: Filters are not correctly synched

---

src/management/configuration/theme/theme.controller.ts
src/management/configuration/theme/theme.html

feat: allow to import/export theme

---

src/index.ts

Closes gravitee-io/issues#3658

fix(theme): Fallback to default theme if the custom one does not exist

---

src/management/management.module.ts
src/portal/i18n/en.json
src/user/resetPassword/resetPassword.html

fix(resetPassword): add a translation to help users

---

src/index.route.ts
src/management/management.module.ts
src/services/reCaptcha.service.ts
src/services/user.service.ts
src/user/registration/confirm/confirm.controller.ts
src/user/registration/confirm/confirm.html
src/user/registration/registration.controller.ts
src/user/registration/registration.html
src/user/resetPassword/resetPassword.controller.ts

Closes gravitee-io/issues#3655

feat(captcha): add captcha protection if feature is enabled

---

src/management/management.interceptor.ts

Closes gravitee-io/issues#3662

feat(csrf): handle csrf cross-domain

---

src/management/management.interceptor.ts

Closes gravitee-io/issues#3662

fix(csrf): handle csrf cross-domain

---

src/services/user.service.ts
src/user/login/login.controller.ts
src/user/registration/confirm/confirm.controller.ts
src/user/resetPassword/resetPassword.controller.ts

fix(captcha): fix renew captcha when needed

---

package.json

Closes gravitee-io/issues#3678

feat(dependencies): bum jquery version to 3.5.0

---

src/entities/application.ts

Closes gravitee-io/issues#3269

Implicit Grant removed from WEB application type with REFRESH default

---

src/management/api/proxy/general/response-templates/response-template.controller.ts

Closes gravitee-io/issues#3689

Merge 1.25.25

---

src/services/theme.service.ts

fix: The theme is not merged when it is never modified by the user

---

src/management/application/applications.html
src/management/application/details/general/application-general.html

fix(ui): Generate the application picture using owner name

---

themes/default-theme.json

fix(management): change notifications color to be a11y compatible

---

src/components/documentation/edit-page.html
src/components/documentation/new-page.html

fix(portal): update links to view, to use key instead of id

---

src/components/documentation/edit-page.component.ts
src/components/documentation/new-page.component.ts
src/management/api/apis.route.ts
src/management/api/portal/apis.portal.route.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/proxy/apiProxy.controller.ts
src/management/configuration/configuration.route.ts
src/management/configuration/views/views.controller.ts
src/management/configuration/views/views.html
src/services/view.service.ts

Closes gravitee-io/issues#3767

feat(management): remove Default view ALL and 'default' field

---

package-lock.json
package.json
src/components/documentation/page/page-editormarkdown-viewer.component.ts
src/components/documentation/page/page-editormarkdown.component.ts
src/index.scss

fix(management): Add Syntax highlighting with a11y-light.js

---

src/user/confirmProfile/confirmProfile.html

fix: Newsletter changes

---

src/services/analytics.service.ts

fix: Errors when selecting a filter on an empty user agent

---

src/management/api/apis.controller.ts
src/management/api/apis.html

fix: some resource accesses should be restricted

---

src/components/documentation/documentation-management.component.ts
src/components/documentation/edit-page.component.ts
src/components/documentation/new-page.component.ts
src/services/documentation.service.ts

fix(management): allow creation of folders in TopFooter system folder

---

docs/management-configuration-apiportalheader.md
src/management/configuration/api-portal-header/api-portal-header.html
src/management/configuration/settings.html

refactor(portal): rename API Portal Headers to API Portal Informations

---

src/management/api/proxy/apiProxy.controller.ts
src/management/api/proxy/general/apiProxyCORS.html

fix(cors): add regex support

---

src/components/widget/table/widget-data-table.component.ts
src/services/analytics.service.ts

fix: Filters are not working on the same widget

---

build.json
package.json
src/components/widget/table/widget-data-table.component.ts
src/management/api/proxy/apiProxy.controller.ts
src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts
src/management/api/proxy/general/apiProxyCORS.html

chore: Merge 1.30.11

---

src/management/configuration/views/view/view.controller.ts
src/management/configuration/views/view/view.html

fix(management): ID remove from view creation request.

---

src/components/logs/logs-filters.controller.ts
src/components/logs/logs-filters.html

Closes gravitee-io/issues#3879

feat(log): Add a field to serach on remote-address

---

build.json
package-lock.json
package.json
src/components/documentation/page/_page.scss

fix: Markdown editor broken

---

.editorconfig
src/services/authentication.service.ts
src/user/login/login.controller.ts

Closes gravitee-io/issues#3857

feat(management): fix redirection with extern url (starting with 'http')

---

src/management/api/analytics/overview/analytics.controller.ts
src/management/platform/dashboard/dashboard.controller.ts

fix(management): move variable declaration into constructor

---

src/management/configuration/groups/group/group.component.ts
src/management/configuration/groups/group/group.html

fix(groups): unable to set a default app or api role in a group

---

src/entities/alert.ts
src/management/api/notifications/apis.notifications.settings.route.ts
src/management/components/alerts/alert/alert.component.ts
src/management/components/alerts/alert/alert.html
src/management/components/alerts/alert/triggers/conditions/trigger-condition-compare.html
src/management/components/alerts/alerts.component.ts
src/management/components/alerts/alerts.html
src/management/configuration/notifications/global.notifications.settings.route.ts
src/management/configuration/settings.component.ts
src/management/configuration/settings.html
src/services/alert.service.ts

Closes gravitee-io/issues#3970

feat(alert): Support for alert templates

---

src/entities/alerts/healthcheck.metrics.ts
src/entities/alerts/node.metrics.ts
src/management/components/alerts/alert/triggers/conditions/trigger-condition-string.component.ts
src/management/components/alerts/alert/triggers/conditions/trigger-condition-string.html
src/management/components/alerts/alert/triggers/trigger-condition.component.ts

fix: Allows to filter alerts on health check status

---

src/management/components/alerts/alert/alert.html
src/management/components/alerts/alert/history/alert-history.html
src/management/components/alerts/alert/triggers/trigger-filters.component.ts

fix: Allows to refresh the alerts history with a button

---

docs/management-application-metadata.md

fix: Documentation is missing for the application metadata

---

src/management/configuration/configuration.route.ts
src/management/configuration/user/new/new-user.component.ts
src/management/configuration/user/new/new-user.html

feat: Allows to search / register user on OIDC provider

---

src/management/api/analytics/logs/configure-logging-editor.dialog.controller.ts

fix(management): don't initiate an array with a type

---

src/components/widget/map/widget-chart-map.component.ts

fix(dashboard): fix world map import

---

src/management/api/proxy/backend/endpoint/httpConfiguration.component.ts

fix: Cannot save API in some case with http headers

---

package-lock.json
package.json
src/components/widget/_widget.scss
src/management/api/portal/general/dialog/apiExport.dialog.html

fix(management): change material version to fix a md-select bug

---

src/management/api/proxy/backend/endpoint/apiEndpoints.html
src/management/api/proxy/backend/endpoint/endpointConfiguration.controller.ts
src/management/api/proxy/backend/endpoint/endpointConfiguration.html
src/management/api/proxy/backend/endpoint/group.html
src/management/api/proxy/backend/endpoint/httpConfiguration.component.ts
src/management/api/proxy/backend/endpoint/httpConfiguration.html

Closes gravitee-io/issues#3105

feat(grpc): Add GRPC support

---

src/services/analytics.service.ts

Closes gravitee-io/issues#4044

feat(plan): Handle unknown plan

---

src/entities/alerts/healthcheck.metrics.ts

fix: Typo in healthcheck metrics

---

src/services/dashboard.service.ts

feat: Support zone in order to group analytics

---

src/management/api/proxy/backend/endpoint/endpointConfiguration.html

Closes gravitee-io/issues#3877

feat(endpoint): Manage secondary endpoints

---

src/components/audit/audit.component.ts
src/components/audit/audit.html
src/management/_datatable.scss

feat(management/audit): display all properties for an event

---

src/management/api/portal/subscriptions/subscription.html

Closes gravitee-io/issues#3965

feat(management): add more information about the application on subscription screen

---

package-lock.json
src/components/newsletter-subcription/_newsletter-subscription.scss
src/components/newsletter-subcription/newsletter-subscription.component.ts
src/components/newsletter-subcription/newsletter-subscription.html
src/index.html
src/index.scss
src/management/management.module.ts
src/services/user.service.ts
src/user/login/login.controller.ts

feat: Allows user to subscribe to the newsletter after login

---

src/management/api/portal/userGroupAccess/members/members.controller.ts
src/management/api/portal/userGroupAccess/members/members.html
src/management/application/details/members/application-members.controller.ts
src/management/application/details/members/application-members.html
src/management/configuration/groups/group/group.component.ts
src/management/configuration/groups/group/group.html
src/services/api.service.ts
src/services/application.service.ts
src/services/group.service.ts

Closes gravitee-io/issues#4134

feat(management): add an option to allow members notification when added in a group, an API or an application

---

src/management/configuration/portal/portal.html
src/management/configuration/user/user.html
src/management/configuration/user/userdetail.component.ts
src/management/configuration/users/users.html
src/management/tasks/tasks.component.ts
src/services/user.service.ts

+ remove portalURL config from gravitee.yml (#4144)
Closes gravitee-io/issues#4069

feat(registration): add an option to enable auto validation registration

---

src/components/metadata/dialog/save.metadata.dialog.html

fix(portal): allow to manage Application's metadata from portal

---

src/entities/alerts/rule.metrics.ts
src/management/components/alerts/alert/alert.component.ts

Closes gravitee-io/issues#4210

feat(alert): Add ability to define health-check rule templates

---

src/management/api/proxy/apiProxy.controller.ts

fix(management): apply pattern validation on cors allow-origin field

---

src/components/import/import-api.component.ts
src/components/import/import-api.html
src/management/api/creation/newApi.html

Allow to import WSDL (from file or URL) in addition of swagger/openapi
fix gravitee-io/issues#322

feat(maganement): Create api from a WSDL

---

src/management/configuration/roles/role/role.components.ts

fix: redirect to the role edit page after creation

---

src/management/api/apis.controller.ts
src/management/api/apis.html

fix: resolve infinite scroll APIs on high resolution

---

build.json
package-lock.json
package.json
src/management/api/portal/userGroupAccess/members/_members.scss
src/management/api/portal/userGroupAccess/members/addMember.dialog.html
src/management/application/details/members/addMember.dialog.html
src/management/application/details/members/application-members.html

fix: resolve display of member's list component

---

src/components/healthcheckmetric/healthcheck-metric.html

fix: Do not display a gauge when no health check value

---

src/management/api/portal/apis.portal.route.html

feat: show API status icons next to title

---

src/management/api/analytics/logs/logging-configuration.controller.ts
src/management/api/analytics/logs/logging-configuration.html

feat: enable logging without condition

---

src/management/components/documentation/edit-page.html
src/management/components/documentation/new-page.html

fix(management): fix popup display

---

src/components/documentation/edit-page.component.ts
src/components/documentation/edit-page.html
src/components/documentation/new-page.component.ts
src/management/configuration/portal/portal.component.ts
src/management/configuration/portal/portal.html

feat: Add settings for OpenAPI doc format

---

src/assets/logo_file.svg
src/components/documentation/dialog/selectpage.controller.ts
src/components/documentation/dialog/selectpage.dialog.html
src/components/documentation/edit-page.component.ts
src/components/documentation/edit-page.html
src/components/documentation/new-page.component.ts
src/components/documentation/new-page.html
src/components/documentation/page/page-editormarkdown.component.ts
src/management/api/portal/apis.portal.route.ts
src/management/configuration/configuration.route.ts
src/management/management.module.ts

Closes gravitee-io/issues#4072

feat(management): add link to internal page in documentation

---

src/entities/user.ts
src/services/user.service.ts
src/user/user.controller.ts
src/user/user.html

Closes gravitee-io/issues#4250

feat(account): allow user to delete his own account

---

src/components/documentation/edit-page.component.ts
src/components/documentation/edit-page.html
src/components/documentation/new-page.component.ts
src/components/documentation/new-page.html
src/management/configuration/categories/category/category.component.ts
src/management/configuration/categories/category/category.controller.ts
src/management/configuration/categories/category/category.html
src/management/configuration/configuration.route.ts

Closes gravitee-io/issues#4067

feat(management): associate a page to a category

---

docs/management-api-documentation.md
pom.xml

feat(management): auto fetch pages based on user configuration

---

src/components/import/import-api.component.ts
src/services/api.service.ts

fix gravitee-io/issues#4149
fix gravitee-io/issues#3156

fix(management): resolve API import/export

---

src/management/api/proxy/backend/endpoint/httpConfiguration.component.ts
src/management/api/proxy/backend/endpoint/httpConfiguration.html
src/services/api.service.ts

Closes gravitee-io/issues#4256

feat(proxy): allow use of system proxy in endpoint configuration

---

src/management/api/portal/subscriptions/subscription.component.ts
src/management/api/portal/subscriptions/subscription.html
src/services/api.service.ts

Closes gravitee-io/issues#4227

feat(apikey): allow apikey reactivation

---

src/components/documentation/dialog/selectpage.dialog.html

Closes gravitee-io/issues#4265

feat(management): use the good field to display the path

---

src/management/api/portal/apis.portal.route.ts
src/management/configuration/configuration.route.ts

Closes gravitee-io/issues#4270

feat(management): use the "published" query filter

---

src/management/configuration/roles/role/role.components.ts

Closes gravitee-io/issues#4258

fix(role): fix error when updating role using jdbc

---

src/management/configuration/user/new/new-user.html

fix: all user invitations are made for the idp 'gravitee'

---

src/management/configuration/users/users.html

Closes gravitee-io/issues#4269

feat(management): replace DISABLED by REJECTED

---

src/components/dialog/fileChooser.dialog.html
src/components/dialog/fileChooserDialog.controller.ts
src/components/documentation/edit-page.component.ts
src/components/documentation/edit-page.html
src/components/fileloader/fileloader.directive.ts
src/management/api/portal/apis.portal.route.ts
src/management/configuration/configuration.route.ts
src/management/management.module.ts
src/services/documentation.service.ts

Closes gravitee-io/issues#4066

feat(management): associate assets to a page

---

src/management/configuration/user/new/new-user.component.ts
src/management/configuration/user/new/new-user.html

fix(management-ui): show IdP Identifier only if there are some IdPs

---

docs/management-configuration-roles.md

fix[management]: update role configuration documentation

---

src/management/_datatable.scss

fix(console): fix audit properties display

---

src/components/image/_image.scss
src/components/image/image.directive.ts
src/components/image/image.html
src/entities/user.ts
src/management/api/apiAdmin.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/apiPortal.html
src/management/configuration/views/view/view.controller.ts
src/management/configuration/views/view/view.html
src/services/api.service.ts
src/services/user.service.ts
src/user/user.controller.ts
src/user/user.html

Closes gravitee-io/issues#4268

feat(management): allow to delete a picture from API, View & user

---

package-lock.json
src/components/error/_error.scss
src/components/error/error.component.ts
src/components/error/error.controller.ts
src/components/error/error.html
src/index.scss
src/management/components/documentation/edit-page.component.ts
src/management/components/documentation/edit-page.html
src/management/components/documentation/new-page.component.ts
src/management/components/documentation/new-page.html
src/management/components/import/_import-api.scss
src/management/components/import/import-api.component.ts
src/management/components/import/import-api.html
src/management/management.module.ts
src/services/api.service.ts
src/services/documentation.service.ts

feat(swagger): display parse errors messages when import definition

---

src/components/identityPicture/identityPicture.directive.ts
src/components/image/_image.scss
src/components/image/image.directive.ts
src/components/image/image.html
src/entities/user.ts
src/management/api/apiAdmin.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/apiPortal.html
src/management/application/details/general/application-general.html
src/management/configuration/categories/category/category.controller.ts
src/management/configuration/categories/category/category.html
src/services/api.service.ts
src/services/application.service.ts
src/user/user.controller.ts
src/user/user.html

From API, applications, categories and users
Closes gravitee-io/issues#4316

feat(pictures): allow to delete pictures

---

src/management/api/proxy/apiProxy.controller.ts
src/management/api/proxy/general/apiProxyCORS.html

fix(api): angularjs error on cors settings screen

---

src/management/management.interceptor.ts

Closes gravitee-io/issues#3721

feat(login): don't redirect to login when accessing public page as anonymous user

---

src/services/authentication.service.ts

Closes gravitee-io/issues#4290

fix(oidc): webconsole error when logging with oidc provider

---

src/management/configuration/portal/portal.html

Closes gravitee-io/issues#4370

refactor(settings): remove useless portal title setting

---

src/management/configuration/settings.component.ts

Closes gravitee-io/issues#4392

fix(settings): fix blank settings page when selecting multiple times

---

src/components/documentation/edit-page.component.ts
src/components/documentation/edit-page.html

Closes gravitee-io/issues#4389

fix(swagger): use right url in swagger and redoc page

---

src/components/import/_import-api.scss
src/components/import/import-api.html
src/management/api/portal/general/dialog/apiImport.dialog.html

Closes gravitee-io/issues#4295

feat(management): fix import API dialog display

---

src/management/management.interceptor.ts

fix(mng/portal): fix test on error Url to avoid redirect on login

---

src/components/dashboard/dashboard-timeframe.controller.ts
src/components/logs/logs-timeframe.controller.ts

fix(console): set default analytics & logs time range to 5m

---

src/components/image/_image.scss
src/components/image/image.directive.ts
src/components/image/image.html
src/management/configuration/theme/theme.html

feat: change background color for theme logo

---

src/services/user.service.ts
src/user/resetPassword/resetPassword.controller.ts

fix(mng): call the dedicated resource to change user password

---

src/index.scss

fix(mngt): addition of missing import in index.scss

---

src/components/dashboard/dashboard-filter.controller.ts
src/components/logs/logs-filters.controller.ts

fix(analytics): escape API host field

---

src/user/login/login.html
themes/default-theme.json
themes/light-theme.json

Fixes https://github.com/gravitee-io/issues/issues/4458

feat: allow to define background color of login page

---

src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/apiPortal.html
src/management/configuration/portal/portal.component.ts
src/management/configuration/portal/portal.html

feat: label's dictionary

---

src/management/api/portal/plans/list-plans.controller.ts
src/management/api/portal/plans/list-plans.html
src/services/api.service.ts

Closes gravitee-io/issues#4414

feat(plan): '_deprecate' api plan action instead of '_depreciate'

---

src/services/api.service.ts

Closes gravitee-io/issues#4411

feat(api): import swagger to update api using put method

---

src/management/api/proxy/backend/endpoint/httpConfiguration.html

fix(http): allow only 1 connection to backend

---

src/management/api/_api.scss
src/management/api/proxy/apiProxy.controller.ts
src/management/api/proxy/apis.proxy.route.ts
src/management/api/proxy/general/apiProxyEntrypoints.html
src/services/environment.service.ts

If domain restrictions exists on current environment, virtual hosts must respect them and host become mandatory,
Closes gravitee-io/issues#4308

feat(virtual-host): implement domain restriction

---

docs/management-alerts.md

Closes gravitee-io/issues#4443

docs(alert): add links to documentation to help configuring alerts

---

src/entities/alerts/rule.metrics.ts
src/management/components/alerts/alert/alert.html
src/management/components/alerts/alert/triggers/trigger-missing-data.component.ts
src/management/components/alerts/alert/triggers/trigger-missing-data.html
src/management/components/alerts/alert/triggers/trigger-window.component.ts
src/management/components/alerts/alert/triggers/trigger-window.html
src/management/management.module.ts
src/services/api.service.ts

Closes gravitee-io/issues#4445

feat(alert): allow to alert on missing data

---

src/components/widget/line/widget-chart-line.component.ts

Closes gravitee-io/issues#4554

fix(management): Cannot filter on a status code in analytics

---

src/management/api/_api.scss
src/management/api/portal/general/apiPortal.html

closes gravitee-io/issues#3201

add some icons & reorganize content

---

src/components/audit/audit.html
src/management/configuration/settings.html

* remove the audit filter on type (ORGANIZATION and ENVIRONMENT)
* move the 'console authentication' near the former 'Authentication' menu
Fixes gravitee-io/issues#4590

fix(management): rewording

---

src/components/navbar/navbar.html
src/management/management.module.ts
src/management/management.route.ts
src/management/support/ticket-detail.component.ts
src/management/support/ticket-detail.html
src/management/support/ticket.controller.ts
src/management/support/ticket.html
src/management/support/tickets-list.controller.ts
src/management/support/tickets-list.html
src/services/ticket.service.ts

feat: support tickets history

---

package-lock.json
src/management/configuration/notification-templates/components/notificationTemplateByType.html

fix: Build of management UI is in error

---

src/entities/qualityRule.ts
src/management/configuration/api-quality-rules/api-quality-rule/api-quality-rule.controller.ts

fix(quality-rules): remove forbidden fields when creating a rule

---

docs/management-configuration-portal.md
src/components/identityProviders/identity-providers.component.ts
src/management/configuration/analytics/analytics.component.ts
src/management/configuration/analytics/analytics.html
src/management/configuration/api-portal-header/api-portal-header.component.ts
src/management/configuration/api-portal-header/api-portal-header.html
src/management/configuration/api-quality-rules/api-quality-rules.component.ts
src/management/configuration/api-quality-rules/api-quality-rules.html
src/management/configuration/api_logging/api_logging.controller.ts
src/management/configuration/api_logging/api_logging.html
src/management/configuration/application/registration/client-registration-providers.component.ts
src/management/configuration/application/registration/client-registration-providers.html
src/management/configuration/categories/categories.controller.ts
src/management/configuration/categories/categories.html
src/management/configuration/portal/portal.component.ts
src/management/configuration/portal/portal.html
src/management/configuration/tags/tags.controller.ts
src/management/configuration/tags/tags.html
src/services/portalConfig.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4452

feat: override settings via envvars

---

src/management/configuration/portal/portal.html

fix: Portal and Schedulers sections appear two times in settings

---

src/management/api/design/properties/properties.html
src/management/configuration/dictionaries/dictionary.controller.ts
src/management/configuration/dictionaries/dictionary.html

fix(management-ui): sort dictionaries by name column

---

src/components/error/error.controller.ts
src/components/error/error.html
src/management/components/documentation/edit-page.component.ts
src/management/components/documentation/import-pages.component.ts
src/management/components/documentation/new-page.component.ts

fix(api): swagger descriptors with missing info are still displayed and imported but an error message is displayed on import

---

src/components/identityProviders/identity-providers.component.ts
src/components/identityProviders/identity-providers.html
src/management/api/proxy/apiProxy.controller.ts
src/management/configuration/analytics/analytics.component.ts
src/management/configuration/analytics/analytics.html
src/management/configuration/api-portal-header/api-portal-header.component.ts
src/management/configuration/api-portal-header/api-portal-header.html
src/management/configuration/api-quality-rules/api-quality-rules.component.ts
src/management/configuration/api-quality-rules/api-quality-rules.html
src/management/configuration/api_logging/api_logging.controller.ts
src/management/configuration/api_logging/api_logging.html
src/management/configuration/application/registration/client-registration-providers.component.ts
src/management/configuration/application/registration/client-registration-providers.html
src/management/configuration/categories/categories.controller.ts
src/management/configuration/categories/categories.html
src/management/configuration/portal/portal.component.ts
src/management/configuration/portal/portal.html
src/management/configuration/tags/tags.controller.ts
src/management/configuration/tags/tags.html
src/management/management.module.ts
src/services/cors.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4432
Fixes https://github.com/gravitee-io/issues/issues/4433

feat: move smtp and cors from static to dynamic configuration

---

src/management/api/creation/steps/api-creation.controller.ts

* fix a javascript error when creating an API from scratch
* order callbacks to get the right state
Fixes gravitee-io/issues#4571

fix(management): add a null test

---

src/management/configuration/theme/theme.controller.ts
src/management/configuration/theme/theme.html

fix(theme): replace function calls by variables

---

src/management/configuration/identity/identity-provider.controller.ts
src/services/authentication.service.ts

* useful to determine on which environment for default application has to be created.
Fixes gravitee-io/issues#4634

fix(user-creation): use envURL for OAuth

---

docs/management-api-policy-studio.md
package-lock.json
src/management/api/design/policy-studio/policy-studio.controller.ts

feat(policy-studio): improve interaction with forms

---

package-lock.json

fix(policy-studio): resolve policy edition of flow plan

---

src/management/configuration/portal/portal.html

fix: Backport 4578

---

src/services/analytics.service.ts
src/services/api.service.ts
src/services/application.service.ts

… page
Closes gravitee-io/issues#4666

chore(): Prepare next version

---

src/management/configuration/identity/identity-provider.controller.ts
src/services/authentication.service.ts

fix: Backport 4634

---

package.json

Closes gravitee-io/issues#4665

fix(studio): Upgrade ui-components

---

src/services/api.service.ts

Closes gravitee-io/issues#4721

Merge 1.30.28

---

src/management/api/creation/_newApi.scss

fix(management): resolve ui of api importing block

---

src/management/api/proxy/general/response-templates/response-template.controller.ts

Closes gravitee-io/issues#4464

feat(response-template): Define a default response template

---

package-lock.json
package.json
src/management/api/design/policy-studio/policy-studio.controller.ts

fix(management): resolve complex form validation

---

src/management/management.interceptor.ts

Closes gravitee-io/issues#4532

fix(login): inconsistent login state between portal and console

---

build.json
package-lock.json
package.json
src/management/configuration/api_logging/api_logging.component.ts
src/management/configuration/api_logging/api_logging.controller.ts
src/management/configuration/api_logging/api_logging.html
src/management/configuration/configuration.route.ts
src/management/configuration/portal/portal.component.ts
src/management/configuration/tags/tags.component.ts
src/management/configuration/tags/tags.controller.ts
src/management/configuration/tags/tags.html
src/services/portalConfig.service.ts

Closes gravitee-io/issues#4787

fix(management): Better handling of settings

---

build.json
package-lock.json
package.json
src/components/import/import-api.component.ts
src/management/api/design/apis.design.route.ts
src/management/api/design/policies/_policy.scss
src/management/api/design/policies/apiPolicies.html
src/management/api/design/policies/policies.controller.ts
src/management/api/design/policy-studio/policy-studio.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/plans/list-plans.controller.ts
src/management/application/details/general/application-general.controller.ts
src/management/configuration/dictionaries/dictionary.controller.ts
src/services/api.service.ts
src/user/user.controller.ts

Fixes https://github.com/gravitee-io/issues/issues/4589

feat: allow to migrate from policy studio v1 to v2

---

src/entities/user.ts
src/services/user.service.ts
src/user/user.controller.ts
src/user/user.html

feat(management): edit my account information

---

src/management/api/design/policy-studio/policy-studio.controller.ts

refactor(policy-studio): add attributes for AM integration

---

src/services/user.service.ts

fix(management): load user permissions only if current env is known

---

src/services/analytics.service.ts
src/services/api.service.ts
src/services/application.service.ts

Closes gravitee-io/issues#4811

fix(settings): get analytics timeout from environment settings

---

src/services/api.service.ts

fix(management): no need to send flows to update a plan

---

src/index.route.ts
src/management/management.run.ts

fix(console): load environments in transitions hooks

---

src/components/documentation/page/page-editormarkdown.component.ts

Fixes https://github.com/gravitee-io/issues/issues/4810

fix: markdown generation issue with too big images

---

src/components/identityProviders/identity-providers.component.ts
src/components/identityProviders/identity-providers.html
src/management/configuration/configuration.route.ts
src/organization/configuration/organization-settings.component.ts
src/organization/organization.route.ts

- manage empty state
- manage ui-router in organization-settings
Fixes gravitee-io/issues#4828

fix(management): improve identity providers screens

---

src/components/widget/table/widget-data-table.component.ts
src/user/user.html

Fixes https://github.com/gravitee-io/issues/issues/4668
+ Fixes a typo from a previous merge

fix: hits by country not well sorted

---

src/management/api/design/policy-studio/policy-studio.controller.ts
src/management/management.module.ts
src/services/spel.service.ts

feat: add expression-language component in studio-policy form

---

src/management/components/import/import-api.component.ts
src/management/components/import/import-api.html

fix(management): avoid multiple import due to double click

---

src/management/api/portal/subscriptions/subscription.html

Change the condition to display the button.
Fixes gravitee-io/issues#4850

fix(console): allow apikey reactivation

---

src/management/management.interceptor.ts

fix(management): resolve error when console start in prod mode

---

src/components/dashboard/dashboard-filter.controller.ts
src/components/dashboard/dashboard-timeframe.controller.ts
src/components/logs/logs-timeframe.controller.ts

fix(management): resolve apis confusion when peforming timeframe zoom

---

docs/management-configuration-identityproviders.md

Closes gravitee-io/issues#4890

fix : Add missing documentation for environement identity providers

---

src/management/api/notifications/apis.notifications.settings.route.ts

Closes gravitee-io/issues#4908

fix(alert): fix alert menu entry on api

---

docs/management-home.md
src/components/dashboard/dashboard.component.ts
src/components/dashboard/dashboard.html
src/components/navbar/navbar.html
src/components/widget/_widget.scss
src/components/widget/count/widget-chart-count.component.ts
src/components/widget/count/widget-chart-count.html
src/components/widget/line/widget-chart-line.component.ts
src/components/widget/line/widget-chart-line.html
src/components/widget/map/widget-chart-map.component.ts
src/components/widget/map/widget-chart-map.html
src/components/widget/pie/widget-chart-pie.component.ts
src/components/widget/pie/widget-chart-pie.html
src/components/widget/stats/widget-data-stats.component.ts
src/components/widget/table/widget-data-table.component.ts
src/components/widget/table/widget-data-table.html
src/components/widget/widget.component.ts
src/components/widget/widget.html
src/index.scss
src/management/management.module.ts
src/management/management.route.ts
src/management/management.run.ts
src/management/platform/home/_home.scss
src/management/platform/home/home.controller.ts
src/management/platform/home/home.html
src/services/environment.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4747

feat: console dashboard page

---

src/management/api/portal/subscriptions/subscription.html

Closes gravitee-io/issues#4889

fix(subscription): Do not allow to reactivate an apikey for a closed plan

---

src/management/api/apiAdmin.controller.ts
src/management/api/audit/history/apiHistory.controller.ts
src/management/api/audit/history/apiHistory.html
src/management/api/deploy/confirmDeployment.dialog.html
src/management/api/deploy/confirmDeploymentDialog.controller.ts
src/management/management.module.ts
src/management/platform/dashboard/dashboard.html
src/management/platform/home/home.html
src/services/api.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4742

feat: associate a label to an api deployment

---

build.json
package.json
src/components/diff/diff.directive.ts
src/services/api.service.ts

chore: fix build

---

src/management/api/apis.route.ts
src/management/api/creation/steps/api-creation-step1.html
src/management/api/creation/steps/api-creation-step5.html
src/management/api/creation/steps/api-creation.component.ts
src/management/api/creation/steps/api-creation.controller.ts

feat(management): allow to select groups while creating API

---

src/components/widget/map/widget-chart-map.component.ts
src/components/widget/pie/widget-chart-pie.component.ts
src/index.ts

Fixes https://github.com/gravitee-io/issues/issues/4952

Activate AngularJS Strict DI in dev mode too and add missing 'ngInject'

---

src/management/platform/home/home.controller.ts

Closes https://github.com/gravitee-io/issues/issues/4953

fix(management): bind fct to fix mdtable pagination in home dashboard

---

src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/general/dialog/apiImport.dialog.html
src/management/api/portal/general/dialog/apiImportDialog.controller.ts

fix(management): Allow to update policies when importing a swagger

---

src/components/widget/line/widget-chart-line-configuration.component.ts
src/components/widget/line/widget-chart-line-configuration.html
src/components/widget/pie/widget-chart-pie-configuration.component.ts
src/components/widget/pie/widget-chart-pie-configuration.html
src/components/widget/pie/widget-chart-pie.component.ts
src/components/widget/table/widget-data-table-configuration.component.ts
src/components/widget/table/widget-data-table-configuration.html

Custom metrics are indexed under the `custom` object.
So we need to prefix a custom field like this `custom.MyMetric` so the aggregation request works.
Closes gravitee-io/issues#4769

feat(assign-metrics): use custom metrics in dashboard

---

docs/organization-configuration-cockpit.md
src/index.scss
src/index.ts
src/management/management.module.ts
src/organization/configuration/cockpit/_cockpit.scss
src/organization/configuration/cockpit/cockpit.component.ts
src/organization/configuration/cockpit/cockpit.html
src/organization/configuration/organization-settings.component.ts
src/organization/configuration/organization-settings.html
src/organization/organization.route.ts
src/services/installation.service.ts

Closes gravitee-io/issues#4766

feat(cockpit): manage cockpit installation registration

---

package-lock.json
package.json

Fixes https://github.com/gravitee-io/issues/issues/4955
This fixes some issues with the read-only mode in the history preview.

History: Bump @gravitee/ui-components to fix to issues with readonly mode

---

src/management/api/audit/history/apiHistory.controller.ts

Closes https://github.com/gravitee-io/issues/issues/4954

fix(management): set default value to services used in gv-policy-studio

---

package.json
src/management/api/design/properties/_properties.scss
src/management/api/design/properties/properties.controller.ts
src/management/api/design/properties/properties.html
src/management/api/proxy/backend/healthcheck/_healthcheck.scss
src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts
src/management/api/proxy/backend/healthcheck/healthcheck-configure.html

feat(management): be able to enable/disable health-check during some periods

---

src/management/api/proxy/apiProxy.controller.ts

Issue: https://github.com/gravitee-io/issues/issues/4796

fix(management): use CORS allow origin regex from RFC6454

---

src/components/sidenav/sidenav.component.ts
src/entities/user.ts
src/index.route.ts
src/management/management.run.ts
src/management/platform/home/home.controller.ts
src/services/environment.service.ts
src/services/user.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4777

feat: handle environment switching

---

src/components/sidenav/sidenav.component.ts
src/components/widget/line/widget-chart-line.component.ts
src/components/widget/pie/widget-chart-pie.component.ts
src/entities/IEnvironmentPermissions.ts
src/index.ts
src/management/management.run.ts
src/services/api.service.ts
src/services/application.service.ts
src/services/environment.service.ts
src/services/user.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4778

feat: display current env id in console url

---

package-lock.json
src/entities/identityProvider.ts
src/organization/configuration/identity/identity-provider.component.ts
src/organization/configuration/identity/identity-provider.html
src/organization/organization.route.ts

Closes gravitee-io/issues#4803

feat(management): allow to configure roleMapping on several environments

---

src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts
src/services/api.service.ts

**Issue**
Fixes https://github.com/gravitee-io/issues/issues/5020
This service doesn't exist anymore so I just removed it (L36), and improve some typings by the way.

fix: remove `ChartService` from Healthcheck controller 

---

src/management/api/healthcheck/apisHealthcheck.controller.ts
src/management/api/healthcheck/apisHealthcheck.html

Fixes https://github.com/gravitee-io/issues/issues/5012

fix: api healthcheck version smaller

---

src/services/installation.service.ts

Closes https://github.com/gravitee-io/issues/issues/5037

fix: move installation resource under organization

---

src/components/user-autocomplete/_user-autocomplete.scss

fix(console): limit css scope for user-autocomplete md-label

---

package-lock.json
package.json
src/libraries/gv-model.directive.ts
src/management/api/analytics/apis.analytics.route.ts
src/management/api/analytics/logs/_logs.scss
src/management/api/analytics/logs/logging-configuration.controller.ts
src/management/api/analytics/logs/logging-configuration.html
src/management/management.module.ts

feat(management): improve API logging configuration

---

src/management/management.run.ts
src/services/environment.service.ts

Fixes https://github.com/gravitee-io/issues/issues/5036
Use ui-router HookMatchCriteria to simplify the transition handling

fix: dashboard is empty after login

---

src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts

**Issue**
Closes https://github.com/gravitee-io/issues/issues/5039
This PR only update the default value of the health check, all the other improvements listed in the issue are handled on `ui-components` side in https://github.com/gravitee-io/gravitee-ui-components/pull/272

HealthCheck: set default value to "Every 1s"

---

src/components/dashboard/dashboard-timeframe.html
src/components/logs/logs-timeframe.html
src/management/api/analytics/logs/configure-logging-editor.dialog.html
src/management/api/portal/subscriptions/dialog/apikey.expiration.dialog.html
src/management/api/portal/subscriptions/dialog/subscription.change.end.date.dialog.html

fix(management): set good configuration to angular-moment-picker

---

src/management/api/design/policy-studio/policy-studio.controller.ts
src/management/api/design/properties/properties.controller.ts
src/management/api/design/properties/properties.html
src/management/configuration/dictionaries/dictionary.controller.ts
src/management/configuration/dictionaries/dictionary.html

Fixes https://github.com/gravitee-io/issues/issues/4746

feat: define HTTP verb for dynamic properties and dictionaries

---

package-lock.json
package.json

fix(management): resolve scroll on code field

---

src/management/configuration/dictionaries/dictionary.controller.ts

Closes gravitee-io/issues#5072

fix(dictionary): Do not compute properties for new dictionary

---

src/management/api/apis.route.ts
src/management/application/applications.route.ts
src/management/management.interceptor.ts

fix: apis and applications should not be accessible from another environment

---

src/components/user-autocomplete/_user-autocomplete.scss

Closes gravitee-io/issues#5089

fix: Tasks are displayed in 2 columns

---

package-lock.json
package.json

fix: use last version of gv-code

---

package-lock.json
package.json

fix: upgrade ui-components to use latest version of gv-code

---

conf/webpack-dist.conf.js
conf/webpack.conf.js
package-lock.json
package.json
src/management/api/portal/apis.portal.route.ts
src/management/api/portal/plans/plan/edit-plan.component.ts
src/management/api/portal/plans/plan/edit-plan.controller.ts
src/management/api/portal/plans/plan/plan-wizard-security.component.ts
src/management/api/portal/plans/plan/plan-wizard-security.html

refactor: use gv-schema-form & resources autocomplete in plan edition

---

src/management/configuration/groups/group/addMember.dialog.html
src/management/configuration/groups/group/addMemberDialog.controller.ts
src/management/configuration/groups/group/group.component.ts
src/management/configuration/groups/group/group.html

* authorize at most 1 API PRIMARY OWNER member in a group
* use the new 'hasAPIPrimaryOwner' boolean of the GroupEntity object. It is computed only if needed.
Closes gravitee-io/issues#5133

feat(management): Manage API PO in a group

---

src/management/api/apis.controller.ts
src/management/api/apis.html
src/management/api/apis.route.ts
src/management/application/applications.route.ts
src/management/application/creation/steps/application-creation.component.ts
src/management/application/creation/steps/application-creation.controller.ts
src/management/audit/audit.controller.ts
src/management/management.route.ts
src/services/api.service.ts

fix(performance): add pagination on list and search apis

---

src/components/documentation/documentation-management.component.ts
src/management/configuration/categories/category/category.controller.ts
src/management/configuration/categories/category/category.html

Fixes https://github.com/gravitee-io/issues/issues/5114

fix: Permissions issue when accessing category documentation

---

src/management/configuration/dictionaries/dictionary.html

fix(management): cannot delete dynamic properties

---

build.json
package-lock.json
package.json
src/components/import/import-api.component.ts
src/components/import/import-api.html
src/management/api/creation/steps/api-creation-step1.component.ts
src/management/api/creation/steps/api-creation-step1.html
src/management/api/creation/steps/api-creation.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/management/api/portal/userGroupAccess/groups/groups.html
src/management/api/portal/userGroupAccess/members/members.html
src/management/api/portal/userGroupAccess/transferOwnership/transferOwnership.controller.ts
src/management/api/portal/userGroupAccess/transferOwnership/transferOwnership.html
src/management/configuration/groups/groups.html
src/management/configuration/portal/portal.html
src/management/management.module.ts
src/services/apiPrimaryOwnerMode.service.ts

* get the config from the management API
* add a service to manage this mode
Closes gravitee-io/issues#5137

feat(management): add a "group only" mode

---

build.json
package-lock.json
package.json

fix(portal): use the latest version of gv-code

---

src/management/api/portal/general/apiPortal.controller.ts

Fixes gravitee-io/issues#5228
Fixes gravitee-io/issues#5229

fix(management): test variable existence

---

package-lock.json
package.json

chore: upgrade ui-components to 2.0.0

---

src/management/api/apis.controller.ts

fix(apis): fetch api quality metric and sync from the apis page

---

src/components/documentation/page/page-editormarkdown.component.ts

fix(management): set the envId from the current Env

---

package-lock.json
package.json

chore: upgrade ui-components to 2.1.1

---

docs/management-api-alerts.md
docs/management-dashboard-alerts.md
package-lock.json
package.json
src/components/alerts/alert/alert.component.ts
src/components/alerts/dashboard/_alerts-dashboard.scss
src/components/alerts/dashboard/alerts-dashboard.component.ts
src/components/alerts/dashboard/alerts-dashboard.html
src/components/emptystate/emptystate.directive.ts
src/index.scss
src/management/api/analytics/alerts/api-alerts-dashboard.controller.ts
src/management/api/analytics/alerts/api-alerts-dashboard.html
src/management/api/analytics/apis.analytics.route.html
src/management/api/analytics/apis.analytics.route.ts
src/management/configuration/notifications/global.notifications.settings.route.ts
src/management/dashboard/alerts-dashboard/platform-alerts-dashboard.controller.ts
src/management/dashboard/alerts-dashboard/platform-alerts-dashboard.html
src/management/dashboard/dashboard.html
src/management/management.module.ts
src/management/management.route.ts
src/services/alert.service.ts

feat: dashboard of all alerts

---

src/organization/configuration/identity/identity-provider-github.html
src/organization/configuration/identity/identity-provider-google.html
src/organization/configuration/identity/identity-provider-graviteeio-am.html
src/organization/configuration/identity/identity-provider-oidc.html
src/organization/configuration/identity/identity-provider.controller.ts
src/organization/configuration/identity/identity-provider.html

Closes gravitee-io/issues#5297

fix: Some fix on idp creation

---

src/index.route.ts
src/services/user.service.ts
src/user/newsletter/newsletter-subscription.controller.ts

Closes gravitee-io/issues#5269

feat: Dynamic newsletter taglines

---

build.json
package-lock.json
package.json
src/management/api/analytics/logs/_logs.scss
src/management/api/analytics/logs/log.component.ts
src/management/api/analytics/logs/log.html
src/management/api/analytics/logs/logs.controller.ts
src/services/analytics.service.ts

Closes gravitee-io/issues#4871

feat: Allow to navigate to previous / next log

---

src/components/documentation/documentation-management.component.ts
src/components/documentation/documentation-management.html
src/components/documentation/edit-page.html
src/components/documentation/new-page.component.ts
src/components/documentation/new-page.html
src/services/documentation.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4893

feat: setting to make portal pages non-visible for anonymous user

---

src/entities/user.ts

fix(permissions): check environment authentication settings permissions

---

src/management/dashboard/dashboard.controller.ts
src/management/dashboard/dashboard.html

fix(permissions): check 'dashboard' permission to display analytics

---

src/organization/configuration/cockpit/cockpit.component.ts

Closes gravitee-io/issues#5170

feat(cockpit): Manage installation deletion

---

package-lock.json
package.json
src/components/image/image.directive.ts
src/components/image/image.html
src/entities/theme.ts
src/management/configuration/theme/theme.controller.ts
src/management/configuration/theme/theme.html
src/services/theme.service.ts

feat(portal): allows to change favicon

---

package-lock.json
src/entities/user.ts
src/management/configuration/groups/group/group.component.ts
src/services/user.service.ts
src/user/_user.scss
src/user/user.controller.ts
src/user/user.html

Closes gravitee-io/issues#4870

feat: Display groups in user account information

---

package-lock.json
package.json

Fixes https://github.com/gravitee-io/issues/issues/5383

chore: update ui-components to 2.3.1

---

package-lock.json
package.json

chore: upgrade ui-components to 2.3.1

---

src/management/dashboard/dashboard.controller.ts
src/management/dashboard/dashboard.html

fix(management): fix perm issue for alerts tab

---

src/management/api/_api.scss
src/management/api/analytics/logs/_logs.scss
src/management/api/proxy/backend/healthcheck/healthcheck-log.html

Fixes https://github.com/gravitee-io/issues/issues/5309

fix: consistent colors between healthcheck details and logs

---

src/management/messages/messages.component.ts

style: contact subscribers as an api publisher

---

src/components/documentation/edit-page-acls.components.ts
src/components/documentation/edit-page-acls.html
src/components/documentation/edit-page.component.ts
src/components/documentation/edit-page.html
src/components/documentation/new-page.html
src/management/management.module.ts
src/services/documentation.service.ts

feat: add ACL on custom link

---

src/management/api/analytics/logs/_logs.scss

Closes gravitee-io/issues#5406

fix: logging options are always displayed

---

src/management/api/portal/subscriptions/subscription.html
src/management/application/applications.controller.ts
src/management/application/applications.html
src/management/application/details/subscriptions/application-subscription.html
src/services/application.service.ts

Fixes https://github.com/gravitee-io/issues/issues/4453

feat: allow to restore an archived application

---

src/management/api/proxy/apis.proxy.route.ts
src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts
src/management/api/proxy/backend/healthcheck/healthcheck-log.controller.ts
src/management/api/proxy/backend/healthcheck/healthcheck-log.html
src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts

fix(console): preserve HealthCheck params on 'back to HealthCheck' link

---

src/services/user.service.ts

Closes gravitee-io/issues#5423

fix: Cannot login with new users with newsletter

---

src/management/application/applications.controller.ts

Closes gravitee-io/issues#5419

fix: change reqest for the copy when application is restored

---

src/management/api/creation/steps/api-creation.controller.ts
src/services/user.service.ts
src/user/user.controller.ts

use path /groups for current user
fix gravitee-io/issues#5416

fix(management): resolve api creation & permissions

---

src/management/api/analytics/logs/logs.html
src/management/application/details/logs/application-logs.html
src/management/platform/logs/platform-logs.html

closes gravitee-io/issues#3391

feat(logs): sort logs by response time

---

src/user/_user.scss
src/user/user.html

fix(account): rollback to the 1.30.x style for the user account page

---

package-lock.json
package.json

chore: bump @gravitee/ui-components to 2.3.3

---

package-lock.json
package.json

fix gravitee-io/issues#5351
fix gravitee-io/issues#5336

chore: bump @gravitee/ui-components to 2.3.4

---

src/management/api/creation/steps/api-creation-step3.html
src/management/api/portal/plans/plan/plan-wizard-restrictions.component.ts

refactor(management): rename path authorization to resource filtering

---

src/management/api/proxy/backend/healthcheck/healthcheck.controller.ts

fix(management): remove unused import

---

package-lock.json
src/management/instances/details/environment/instance-environment.html

Fixes https://github.com/gravitee-io/issues/issues/5357

feat: allow to associate a gateway to environments

---

src/components/alerts/alert/alert.component.ts
src/components/alerts/alert/alert.html
src/components/alerts/alert/triggers/conditions/trigger-condition-compare.component.ts
src/components/alerts/alert/triggers/conditions/trigger-condition-string.component.ts
src/components/alerts/alert/triggers/trigger-api-hc-endpoint-status-changed.component.ts
src/components/alerts/alert/triggers/trigger-application-quota.component.ts
src/components/alerts/alert/triggers/trigger-condition.html
src/components/alerts/alert/triggers/trigger-dampening.html
src/components/alerts/alert/triggers/trigger-metrics-aggregation.component.ts
src/components/alerts/alert/triggers/trigger-metrics-rate.component.ts
src/components/alerts/alert/triggers/trigger-metrics-simple-condition.component.ts
src/components/alerts/alert/triggers/trigger-missing-data.component.ts
src/components/alerts/alert/triggers/trigger-node-healthcheck.component.ts
src/components/alerts/alert/triggers/trigger-node-lifecycle-changed.component.ts
src/components/alerts/alerts.component.ts
src/components/alerts/dashboard/alerts-dashboard.component.ts
src/entities/alert.ts

fix(management): use uppercase enum in alerts

---

src/index.route.ts
src/services/user.service.ts

fix(): refresh current user profile when 'MyAccount' is displayed

---

src/management/api/proxy/backend/endpoint/endpointConfiguration.controller.ts

fix(management): test ssl config before deletion

---

src/index.scss
src/organization/_organization.scss
src/organization/configuration/roles/role/_role.scss
src/organization/configuration/roles/role/role.html
src/services/user.service.ts

**Issue**
Fixes https://github.com/gravitee-io/issues/issues/5544
- Always display the info label and not only as a tooltip
- Lighten the disable mode of `md-checkbox` to distinguish it more easily from the "active" state
**Screenshot**
Before:
After:

Role: ui improvements for the tooltip on ENTRYPOINT

---

build.json
package-lock.json
package.json
src/organization/configuration/identity/identity-provider.html

Closes gravitee-io/issues#5561

fix: not default role when user created with external IDP

---

src/organization/configuration/notification-templates/components/notificationTemplateByType.component.ts
src/organization/configuration/notification-templates/components/notificationTemplateByType.controller.ts
src/organization/configuration/notification-templates/components/notificationTemplateByType.html
src/organization/configuration/notification-templates/notificationTemplate.component.ts
src/organization/configuration/notification-templates/notificationTemplate.controller.ts
src/organization/configuration/notification-templates/notificationTemplate.html
src/organization/configuration/notification-templates/notificationTemplates.controller.ts
src/organization/organization.route.ts

* Do not display alert templates if alert service is not enabled
* Prevent alert templates to be modified if no alert plugin is installed
Closes gravitee-io/issues#5481

feat(management): allow to customize consumer alerts

---

src/components/audit/audit.html

Closes gravitee-io/issues#5256

fix(ui): update label to 'select start date'

---

package-lock.json
package.json
src/organization/configuration/organization-settings.html

Fixes https://github.com/gravitee-io/issues/issues/4460

fix(management): platform policies update ui-component and add a missing menu entry

---

src/management/api/design/apis.design.route.html
src/management/api/design/apis.design.route.ts
src/management/api/design/design/design.controller.ts
src/management/api/design/design/design.html

Fixes https://github.com/gravitee-io/issues/issues/4460

fix(management): platform policies fix routing and property providers

---

build.json
package-lock.json
package.json
src/components/image/image.directive.ts
src/management/api/apiAdmin.controller.ts
src/management/api/portal/general/apiPortal.controller.ts
src/services/api.service.ts

Closes gravitee-io/issues#5303

fix: Unable to use default image on API

---

src/services/cors.service.ts

fix(cors): allow all valid regex

---

package-lock.json
package.json

Fixes https://github.com/gravitee-io/issues/issues/4460

fix: fix policy error on find

---

docs/management-configuration-policies.md

docs: add documentation page for platform policies

---

src/management/api/_api.scss
src/management/api/apiAdmin.controller.ts
src/management/api/deploy/_deploy.scss
src/management/api/deploy/confirmDeployment.dialog.html
src/management/api/deploy/confirmDeploymentDialog.controller.ts
src/services/flow.service.ts

feat: use a resource to know if the platform has policies or not

---

src/organization/configuration/identity/identity-provider.html

fix(management): improve oidc group mapping

---

src/management/configuration/portal/portal.html
src/organization/configuration/console/console.html

fix(management): clean CORS env vars & migration guide

---

src/management/api/proxy/apis.proxy.route.ts
src/management/api/proxy/backend/healthcheck/_healthcheck.scss
src/management/api/proxy/backend/healthcheck/healthcheck-configure.controller.ts
src/management/api/proxy/backend/healthcheck/healthcheck-configure.html
src/management/configuration/dictionaries/dictionary.html

https://github.com/gravitee-io/issues/issues/4943

feat: allow to use EL in health check configuration

---

build.json
package-lock.json
package.json
src/services/user.service.ts

Closes gravitee-io/issues#5720

fix: Newsletter subscribe link not working anymore

---

package-lock.json
package.json

feat: improve design resources management

---

src/components/navbar/navbar.html

fix(management): redirect to dashboard when click on logo

---

src/index.ts

fix: add missing pathname in url rewriting

---

src/components/alerts/alert/alert.html
src/components/alerts/alert/triggers/trigger-node-healthcheck.component.ts

* fix a duplicate name for a component
* add component in alert.html
Fixes gravitee-io/issues#5808

fix: display a condition for node healthcheck

---

package-lock.json
package.json
src/management/api/analytics/logs/log.component.ts
src/management/api/analytics/logs/log.html
src/management/api/design/policy-studio/policy-studio.controller.ts

Replace codemirror with gv code

---

pom.xml

CICD operation : restore state right after 3.5.17 release

restoring state right after release 3.5.17

---

jest.setup.js
src/entities/task/task.ts
src/management/tasks/_tasks.scss
src/management/tasks/promotion/_promotion-task.scss
src/management/tasks/promotion/promotion-task.component.ts
src/management/tasks/promotion/promotion-task.html
src/management/tasks/tasks.component.ts
src/management/tasks/tasks.html
src/services/promotion.service.spec.ts
src/services/promotion.service.ts
src/services/qualityRule.service.spec.ts

**Issue**
https://github.com/gravitee-io/issues/issues/5528
https://github.com/gravitee-io/issues/issues/5527
Add buttons to accept or reject an API promotion in Tasks screen.

Accept or reject an API promotion

---

src/entities/alerts/api.metrics.ts
src/management/api/proxy/general/response-templates/response-template.controller.ts

Closes gravitee-io/issues#5501

feat(response-template): Add support for HTTP client connection issues

---

src/management/api/portal/plans/plan/plan-wizard-restrictions.component.ts

See https://github.com/gravitee-io/issues/issues/5833

fix(management): plan creation with restriction causes an exception

---

src/services/api.service.ts

fixes gravitee-io/issues#5694
fixes gravitee-io/issues#5820

fix: update flows linked to a Plan on update plan action

---

src/components/widget/table/widget-data-table-configuration.component.ts

fix: do not erase chart.percent

---

src/components/documentation/documentation-management.html
src/components/documentation/edit-tabs/edit-page-translations.html

fix: use regular font size for link translation

---

src/components/policy-studio-wrapper/_policy-studio-wrapper.scss
src/components/policy-studio-wrapper/policy-studio-wrapper.html

fix(management): set white background to policy-studio-wrapper component

---

src/management/api/creation/steps/api-creation.controller.ts
src/services/api.service.ts

**Issue**
https://github.com/gravitee-io/issues/issues/5941
Use APIM confirm modal template to display warning dialog properly. Also start to improve typings of Api Creation Controller.
**Screenshot**
Before
After

Fix Page deletion warning in api creation flow

---

package-lock.json
package.json
src/components/import/import-api.component.ts

Fix policy validation

---

docs/management-configuration-portal-pages.md

**Issue**
https://github.com/gravitee-io/issues/issues/5575
Edited portal pages internal UI documentation as per Ami's request in ticket #1644 / 5575.

Editing UI Documentation 

---

src/management/instances/details/environment/instance-environment.html

feat: select gateway to execute debug request

---

package-lock.json
package.json

fix: request form headers not reset when changing pages

---

.github/pull_request_template.md
.gitignore
.storybook/main.ts
.storybook/preview.ts
package-lock.json
package.json
src/organization/configuration/console/console-settings.stories.ts
tsconfig.json

**Issue**
https://github.com/gravitee-io/issues/issues/6023
- Setup Storybook, we need a custom webpack config because we are not using Angular CLI (yet 😛 )
- Add Design addon (https://github.com/pocka/storybook-addon-designs) to be able to preview Figma 
Also: 
- Add a PR template
**How to test?**
- `npm install`
- `npm run storybook`
- Enjoy

Setup Storybook and Design addon

---

.circleci/config.yml

**Issue**
NA
Try to comment PR but stop job when no PR is available

CI: Try to comment PR but stop job when no PR is available

---

.circleci/config.yml
.gitignore
package-lock.json
package.json

**Issue**
https://github.com/gravitee-io/issues/issues/6055
Setup chromatic 
With this new check
we can see storybook deployment https://612657caa8e859003a8a6430-umufjuufrk.chromatic.com/

Setup chromatic

---

src/organization/configuration/organization-settings.module.ts
src/organization/configuration/users/org-settings-users.component.html
src/organization/configuration/users/org-settings-users.component.scss
src/organization/configuration/users/org-settings-users.component.spec.ts
src/organization/configuration/users/org-settings-users.component.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6061
Add users table with empty data and simple search input

6061 migrate org users list step 2

---

src/components/identityProviders/identity-providers.html
src/organization/configuration/console/console.html
src/organization/configuration/console/org-settings-general.component.scss
src/organization/configuration/identity/identity-provider.html
src/organization/configuration/notification-templates/notificationTemplate.html
src/organization/configuration/notification-templates/notificationTemplates.html
src/organization/configuration/organization-settings.html
src/organization/configuration/roles/role/role.html
src/organization/configuration/roles/roles.html
src/organization/configuration/tags/tags.html
src/organization/configuration/tenants/tenants.html
src/organization/configuration/user/new/new-user.html
src/organization/configuration/user/user.html
src/organization/configuration/users/users.html
src/scss/gio-layout.scss

**Issue**
NA
- Move CSS class used to define size in a container inside compo
- Use a container with responsive margins for Org Conf General screen
**Screenshot**

Add multiple responsive layouts and fix spacing in Org Settings screens

---

.circleci/config.yml
docker/Dockerfile-dev

**Issue**
https://github.com/gravitee-io/issues/issues/6048
Update the Element Zero stack after each merge in the `master` branch.
Details:
- A docker image is built
- The docker image is pushed to Azure private docker registry
- The cluster is updated using Helm command

CI : Auto deploy APIM UI 

---

src/components/identityProviders/identity-providers.html

**Issue**
NA
Fix layout of identity providers setting screen
**Before**
**After**

Fix layout of identity providers setting screen

---

license-check-config.json
src/organization/configuration/organization-settings.module.ts
src/organization/configuration/users/org-settings-users.component.html
src/organization/configuration/users/org-settings-users.component.scss
src/organization/configuration/users/org-settings-users.component.spec.ts
src/organization/configuration/users/org-settings-users.component.ts
src/services-ngx/users.service.ts
src/shared/components/gio-avatar/__snapshots__/gio-avatar.component.spec.ts.snap
src/shared/components/gio-avatar/gio-avatar.component.html
src/shared/components/gio-avatar/gio-avatar.component.scss
src/shared/components/gio-avatar/gio-avatar.component.spec.ts
src/shared/components/gio-avatar/gio-avatar.component.ts
src/shared/components/gio-avatar/gio-avatar.module.ts
src/shared/components/gio-avatar/gio-avatar.stories.ts

**Issue**
gravitee-io/issues#6061
- Add new component to create user avatar like IdentityPictureController
- Use this component in users list
- Set page layout

6061 migrate org users list step 4

---

src/index.scss
src/management/management.run.ts
src/organization/configuration/organization-settings.module.ts
src/organization/configuration/users/org-settings-users.component.html
src/organization/configuration/users/org-settings-users.component.scss
src/organization/configuration/users/org-settings-users.component.spec.ts
src/organization/configuration/users/org-settings-users.component.ts
src/organization/organization.route.ajs.ts
src/scss/gio-material-theme.scss
src/scss/material-layout-compatibility.scss
src/services-ngx/users.service.spec.ts
src/services-ngx/users.service.ts

**Issue**
gravitee-io/issues#6061
finish refactoring or user list page

6061 migrate org users list step 5

---

.storybook/main.ts
conf/webpack-dist.conf.js
conf/webpack.conf.js
src/index.scss
src/organization/configuration/console/org-settings-general.component.html
src/organization/configuration/console/org-settings-general.component.scss
src/organization/configuration/console/org-settings-general.component.ts
src/organization/configuration/user/new/org-settings-new-user.component.html
src/organization/configuration/user/new/org-settings-new-user.component.scss
src/organization/configuration/user/new/org-settings-new-user.component.ts
src/organization/configuration/users/org-settings-users.component.html
src/organization/configuration/users/org-settings-users.component.scss
src/organization/configuration/users/org-settings-users.component.ts
src/scss/gio-global-style.scss
src/scss/gio-layout.scss
src/scss/gio-material-theme.scss
src/scss/gio-palettes.scss
src/services-ngx/snack-bar.service.ts
src/shared/components/confirm-dialog/confirm-dialog.component.html

**Issue**
NA
Update design of screens migrated to Angular
Go to the deployed app to see the diff 😉

Update design of screens migrated to Angular

---

src/management/application/_applications.scss
src/management/application/details/subscribe/application-subscribe.html
src/management/application/details/subscribe/application-subscribe.scss

**Issue**
https://github.com/gravitee-io/issues/issues/6150
Use CSS flex to avoid background alignment issue
Before
After

Use CSS flex to avoid background alignment issue

---

.circleci/config.yml

**Issue**
n/a
comment chromatic storybook url in gh pull request

chore: comment chromatic storybook url in gh pull request

---

src/management/api/portal/plans/plan/plan-wizard-restrictions.component.ts

fix: be able to save a plan with restrictions

---

.storybook/preview.ts
src/organization/configuration/console/org-settings-general.component.scss
src/organization/configuration/user/new/org-settings-new-user.component.scss
src/organization/configuration/users/org-settings-users.component.scss
src/scss/gio-global-style.scss
src/scss/gio-material-theme.scss
src/scss/gio-palettes.scss
src/scss/material-layout-compatibility.scss
src/shared/components/form-slide-toogle/gio-form-slide-toggle.component.scss
src/shared/components/gio-table-of-contents/gio-table-of-contents.component.scss
src/shared/stories/gio-palettes.scss
src/shared/stories/gio-palettes.scss.d.ts
src/shared/stories/showcase-color.component.html
src/shared/stories/showcase-color.component.scss
src/shared/stories/showcase-color.component.ts
src/shared/stories/showcase-material.component.html
src/shared/stories/showcase-material.component.scss
src/shared/stories/showcase-material.component.ts
src/shared/stories/showcase-typography.component.html
src/shared/stories/showcase-typography.component.ts
src/shared/stories/showcase.stories.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6158
Showcase for color, some angular component and typography used in apim
see link below

Sb showcase

---

src/management/api/apis.controller.ts
src/management/api/apis.html

https://github.com/gravitee-io/issues/issues/2839

2839 portal advanced search

---

package-lock.json
package.json

**Issue**
NA
Update some dependencies marked as vulnerable by Snyk, it will replace:
- https://github.com/gravitee-io/gravitee-management-webui/pull/1609
- https://github.com/gravitee-io/gravitee-management-webui/pull/1618
- https://github.com/gravitee-io/gravitee-management-webui/pull/1626

Update some vulnerable dependencies

---

package.json
src/components/identityProviders/identity-providers.component.ts
src/entities/identity-provider/identityProvider.ts
src/entities/identity-provider/identityProviderActivation.fixture.ts
src/entities/identity-provider/identityProviderActivation.ts
src/entities/identity-provider/index.ts
src/management/management.module.ajs.ts
src/organization/configuration/console/org-settings-general.component.spec.ts
src/organization/configuration/identity-providers/org-settings-identity-providers.component.html
src/organization/configuration/identity-providers/org-settings-identity-providers.component.scss
src/organization/configuration/identity-providers/org-settings-identity-providers.component.spec.ts
src/organization/configuration/identity-providers/org-settings-identity-providers.component.ts
src/organization/configuration/organization-settings.module.ts
src/organization/organization.route.ajs.ts
src/services-ngx/console-settings.service.spec.ts
src/services-ngx/console-settings.service.ts
src/services-ngx/organization.service.spec.ts
src/services-ngx/organization.service.ts
src/services/environment.service.ts
src/services/organization.service.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6058
- Created a new Angular component for Identity Providers settings, this component display the list of IdP but doesn't have all the interaction yet
- Created a new Angular service for OrganizationService and improve related types

Start migration of Identity Providers settings screen

---

src/index.scss
src/management/management.module.ajs.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-github/org-settings-identity-provider-github.component.html
src/organization/configuration/identity-provider/org-settings-identity-provider-github/org-settings-identity-provider-github.component.spec.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-github/org-settings-identity-provider-github.component.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-google/org-settings-identity-provider-google.component.html
src/organization/configuration/identity-provider/org-settings-identity-provider-google/org-settings-identity-provider-google.component.spec.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-google/org-settings-identity-provider-google.component.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-graviteeio-am/org-settings-identity-provider-graviteeio-am.component.html
src/organization/configuration/identity-provider/org-settings-identity-provider-graviteeio-am/org-settings-identity-provider-graviteeio-am.component.spec.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-graviteeio-am/org-settings-identity-provider-graviteeio-am.component.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-oidc/org-settings-identity-provider-oidc.component.html
src/organization/configuration/identity-provider/org-settings-identity-provider-oidc/org-settings-identity-provider-oidc.component.spec.ts
src/organization/configuration/identity-provider/org-settings-identity-provider-oidc/org-settings-identity-provider-oidc.component.ts
src/organization/configuration/identity-provider/org-settings-identity-provider.component.html
src/organization/configuration/identity-provider/org-settings-identity-provider.component.scss
src/organization/configuration/identity-provider/org-settings-identity-provider.component.spec.ts
src/organization/configuration/identity-provider/org-settings-identity-provider.component.ts
src/organization/configuration/organization-settings.module.ts
src/organization/organization.route.ajs.ts
src/shared/components/form-card-group/gio-form-card-group.component.html
src/shared/components/form-card-group/gio-form-card-group.component.scss
src/shared/components/form-card-group/gio-form-card-group.component.ts
src/shared/components/form-card-group/gio-form-card-group.harness.ts
src/shared/components/form-card-group/gio-form-card-group.module.spec.ts
src/shared/components/form-card-group/gio-form-card-group.module.ts
src/shared/components/form-card-group/gio-form-card-group.stories.ts
src/shared/components/form-card-group/gio-form-card.component.scss
src/shared/components/form-card-group/gio-form-card.component.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6060
first step to migrate identity provider create page 
- add new component to select provider 
- init angular component for identity provider with common form (only template)
- init provider's component (only empty component)

6060 identity provider

---

conf/webpack.conf.js
package-lock.json
package.json

**Issue**
NA
Replace https://github.com/gravitee-io/gravitee-management-webui/pull/1684
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908

Update `webpack-dev-server` to reduce vulnerabilities

---

src/entities/identity-provider/identityProvider.fixture.ts
src/entities/identity-provider/identityProvider.ts
src/management/management.interceptor.ts
src/organization/configuration/identity-provider/org-settings-identity-provider.component.html
src/organization/configuration/identity-provider/org-settings-identity-provider.component.spec.ts
src/organization/configuration/identity-provider/org-settings-identity-provider.component.ts
src/organization/configuration/identity-providers/org-settings-identity-providers.component.spec.ts
src/organization/configuration/identity-providers/org-settings-identity-providers.component.ts
src/organization/organization.route.ajs.ts
src/services-ngx/identity-provider.service.spec.ts
src/services-ngx/identity-provider.service.ts
src/shared/interceptors/csrf.interceptor.ts

**Issue**
https://github.com/gravitee-io/issues/issues/6060
allow to create and edit identity provider with same form 

Edit identity provider
